// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// Spec sources (Apache-2.0 Carbon Design System; see NOTICE):
//   styles/scss/components/slug/_slug.scss   (the real AILabel styles)
//   react/src/components/AILabel/index.tsx
//
// AILabel ("slug") marks AI-generated content. The trigger is a small "AI"
// button (bordered square, or an inline text affordance) that opens an
// AI-tinted callout — a CarbonPopover whose surface uses the ai-* tokens. When
// `revertActive`, it instead shows a ghost Undo button to revert AI input.

import 'dart:math' as math;

import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

import '../../foundations/fonts.dart';
import '../../foundations/layout.dart';
import '../../foundations/motion.dart';
import '../../foundations/typography.dart';
import '../../icons/carbon_icons.dart';
import '../../theme/carbon_theme.dart';
import '../../theme/carbon_theme_data.dart';
import '../../utils/focus_ring.dart';
import '../button/carbon_button.dart';
import '../popover/carbon_popover.dart';

/// The size of a [CarbonAILabel] trigger button.
enum CarbonAILabelSize {
  /// 16px (Carbon `mini`).
  mini(16, 9, 12),

  /// 20px (Carbon `2xs`).
  xxs(20, 12, 16),

  /// 24px (Carbon `xs`) — the default.
  xs(24, 12, 16),

  /// 32px (Carbon `sm`).
  sm(32, 16, 21),

  /// 40px (Carbon `md`).
  md(40, 16, 21),

  /// 48px (Carbon `lg`).
  lg(48, 16, 21),

  /// 64px (Carbon `xl`).
  xl(64, 20, 26);

  const CarbonAILabelSize(this.dimension, this.fontSize, this.lineHeight);

  /// The square edge length in logical pixels.
  final double dimension;

  /// The "AI" text size in logical pixels.
  final double fontSize;

  /// The "AI" text line height in logical pixels.
  final double lineHeight;

  bool get _isLarge => this == lg || this == xl;
}

/// Marks AI-generated content with an "AI" affordance that opens an explanatory
/// callout.
///
/// The trigger is a bordered "AI" square ([inline] renders a compact text
/// affordance instead). Tapping it (or Enter/Space) opens an AI-tinted
/// [CarbonPopover] holding [content] and an optional [actions] row. When
/// [revertActive] is true the trigger is replaced by a ghost Undo button that
/// calls [onRevert].
///
/// The callout opens instantly (Carbon defines no popover motion); the
/// trigger's hover/focus tints ease at `fast-01`, applied instantly under
/// reduced motion (`MediaQueryData.disableAnimations`).
///
/// ```dart
/// CarbonAILabel(
///   content: const Text('This text was generated by AI.'),
///   actions: <Widget>[CarbonLink(text: 'View details', onPressed: _open)],
/// )
/// ```
class CarbonAILabel extends StatefulWidget {
  /// Creates an AI label.
  const CarbonAILabel({
    super.key,
    this.content,
    this.actions,
    this.aiText = 'AI',
    this.textLabel,
    this.inline = false,
    this.size = CarbonAILabelSize.xs,
    this.align = CarbonPopoverAlignment.bottom,
    this.autoAlign = true,
    this.label = 'Show information',
    this.revertActive = false,
    this.onRevert,
    this.revertLabel = 'Revert to AI input',
    this.defaultOpen = false,
    this.focusNode,
  });

  /// The callout body.
  final Widget? content;

  /// An optional row of actions shown beneath [content].
  final List<Widget>? actions;

  /// The label text; defaults to `AI`.
  final String aiText;

  /// Extra text shown after [aiText] in the [inline] variant.
  final String? textLabel;

  /// Whether to render the compact inline affordance instead of the square
  /// button.
  final bool inline;

  /// The trigger size.
  final CarbonAILabelSize size;

  /// Where the callout opens relative to the trigger.
  final CarbonPopoverAlignment align;

  /// Whether the callout flips to stay in view.
  final bool autoAlign;

  /// The accessible description appended after [aiText] for the button.
  final String label;

  /// Whether to show the revert (Undo) button instead of the AI trigger.
  final bool revertActive;

  /// Called when the revert button is activated.
  final VoidCallback? onRevert;

  /// The accessible label and tooltip for the revert button.
  final String revertLabel;

  /// Whether the callout starts open.
  final bool defaultOpen;

  /// An optional external focus node for the trigger.
  final FocusNode? focusNode;

  @override
  State<CarbonAILabel> createState() => _CarbonAILabelState();
}

class _CarbonAILabelState extends State<CarbonAILabel> {
  late bool _open = widget.defaultOpen;
  FocusNode? _ownFocus;
  // Shared with the popover so tapping the trigger while open is not an
  // "outside tap" (which would close-then-reopen).
  final Object _group = UniqueKey();

  FocusNode get _triggerFocus =>
      widget.focusNode ?? (_ownFocus ??= FocusNode());

  @override
  void dispose() {
    _ownFocus?.dispose();
    super.dispose();
  }

  void _toggle() => setState(() => _open = !_open);

  void _close() {
    setState(() => _open = false);
    _triggerFocus.requestFocus();
  }

  String get _ariaLabel => widget.textLabel == null
      ? '${widget.aiText} ${widget.label}'
      : '${widget.aiText} ${widget.textLabel}';

  @override
  Widget build(BuildContext context) {
    if (widget.revertActive) {
      return CarbonButton.iconOnly(
        icon: CarbonIcons.undo,
        iconDescription: widget.revertLabel,
        kind: CarbonButtonKind.ghost,
        size: CarbonButtonSize.sm,
        onPressed: widget.onRevert,
      );
    }

    final CarbonThemeData theme = CarbonTheme.of(context);
    return CarbonPopover(
      open: _open,
      align: widget.align,
      autoAlign: widget.autoAlign,
      onRequestClose: _close,
      tapRegionGroupId: _group,
      // The AI callout: ai-popover-background fill with an ai-border-start edge.
      surfaceColor: theme.aiPopoverBackground,
      surfaceBorderColor: theme.aiBorderStart,
      content: _AILabelCallout(
        content: widget.content,
        actions: widget.actions,
      ),
      child: TapRegion(
        groupId: _group,
        child: _AILabelButton(
          focusNode: _triggerFocus,
          size: widget.size,
          inline: widget.inline,
          aiText: widget.aiText,
          textLabel: widget.textLabel,
          label: _ariaLabel,
          onTap: _toggle,
        ),
      ),
    );
  }
}

/// The AI trigger: a bordered "AI" square, or the inline text affordance.
class _AILabelButton extends StatefulWidget {
  const _AILabelButton({
    required this.focusNode,
    required this.size,
    required this.inline,
    required this.aiText,
    required this.textLabel,
    required this.label,
    required this.onTap,
  });

  final FocusNode focusNode;
  final CarbonAILabelSize size;
  final bool inline;
  final String aiText;
  final String? textLabel;
  final String label;
  final VoidCallback onTap;

  @override
  State<_AILabelButton> createState() => _AILabelButtonState();
}

class _AILabelButtonState extends State<_AILabelButton> {
  bool _hovered = false;
  bool _focused = false;
  bool _pressed = false;

  KeyEventResult _onKey(FocusNode node, KeyEvent event) {
    if (event is KeyDownEvent &&
        (event.logicalKey == LogicalKeyboardKey.enter ||
            event.logicalKey == LogicalKeyboardKey.space)) {
      widget.onTap();
      return KeyEventResult.handled;
    }
    return KeyEventResult.ignored;
  }

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData theme = CarbonTheme.of(context);
    return Semantics(
      button: true,
      label: widget.label,
      child: ExcludeSemantics(
        child: MouseRegion(
          cursor: SystemMouseCursors.click,
          onEnter: (_) => setState(() => _hovered = true),
          onExit: (_) => setState(() => _hovered = false),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: widget.onTap,
            onTapDown: (_) => setState(() => _pressed = true),
            onTapUp: (_) => setState(() => _pressed = false),
            onTapCancel: () => setState(() => _pressed = false),
            child: Focus(
              focusNode: widget.focusNode,
              onKeyEvent: _onKey,
              onFocusChange: (bool value) => setState(() => _focused = value),
              child: widget.inline ? _buildInline(theme) : _buildDefault(theme),
            ),
          ),
        ),
      ),
    );
  }

  TextStyle _textStyle(double fontSize, double lineHeight, Color color) =>
      TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontWeight: FontWeight.w600,
        fontSize: fontSize,
        height: lineHeight / fontSize,
        color: color,
      );

  Widget _buildDefault(CarbonThemeData theme) {
    final CarbonAILabelSize size = widget.size;
    final bool filled = _hovered || _pressed;
    final TextStyle style = _textStyle(
      size.fontSize,
      size.lineHeight,
      filled ? theme.textInverse : theme.textPrimary,
    );
    final TextPainter painter = TextPainter(
      text: TextSpan(text: widget.aiText, style: style),
      textDirection: Directionality.of(context),
      textScaler: MediaQuery.textScalerOf(context),
      locale: Localizations.maybeLocaleOf(context),
    )..layout();
    // Preserve the compact spec size while admitting the actual scaled glyph
    // line and the two border pixels. Custom AI text also retains its width.
    final double dimension = math.max(
      size.dimension,
      math.max(painter.width, painter.height) + 2,
    );
    painter.dispose();
    // reset border 1px border-inverse; hover fills border-inverse + text-inverse.
    // `_slug.scss`: color/border/background $duration-fast-01
    // motion(entrance, productive); instant under reduced motion.
    final Widget box = AnimatedContainer(
      duration: carbonDuration(context, CarbonDuration.fast01),
      curve: CarbonEasing.entranceProductive,
      width: dimension,
      height: dimension,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: filled ? theme.borderInverse : const Color(0x00000000),
        border: Border.all(color: theme.borderInverse),
      ),
      child: Text(widget.aiText, style: style),
    );
    // mini / 2xs keep a 24px hit target around the smaller visual.
    final double hit = math.max(24, dimension);
    return SizedBox.square(
      dimension: hit,
      child: Center(
        child: CarbonFocusRing(visible: _focused, child: box),
      ),
    );
  }

  Widget _buildInline(CarbonThemeData theme) {
    final bool large = widget.size._isLarge;
    final double dot = large ? 8 : 4;
    final double fontSize = large ? 14 : 12;
    final Color borderColor = _focused
        ? theme.focus
        : _hovered
        ? theme.iconSecondary
        : const Color(0x00000000);
    final String text = widget.textLabel == null
        ? widget.aiText
        : '${widget.aiText} ${widget.textLabel}';
    // `_slug.scss` inline affordance: background/box-shadow $duration-fast-01
    // motion(entrance, productive); instant under reduced motion.
    return AnimatedContainer(
      duration: carbonDuration(context, CarbonDuration.fast01),
      curve: CarbonEasing.entranceProductive,
      padding: const EdgeInsets.symmetric(horizontal: 4),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(1),
        border: Border.all(color: borderColor),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          // The AI dot (icon-primary square), centered with the text.
          Container(width: dot, height: dot, color: theme.iconPrimary),
          const SizedBox(width: 4),
          Flexible(
            child: Text(
              text,
              style: _textStyle(fontSize, fontSize * 1.3, theme.textPrimary),
            ),
          ),
        ],
      ),
    );
  }
}

/// The AI callout body: padded content with an optional actions row.
class _AILabelCallout extends StatelessWidget {
  const _AILabelCallout({required this.content, required this.actions});

  final Widget? content;
  final List<Widget>? actions;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData theme = CarbonTheme.of(context);
    final List<Widget>? actions = this.actions;
    return Padding(
      padding: const EdgeInsets.all(CarbonSpacing.spacing05),
      child: DefaultTextStyle.merge(
        style: CarbonTypeStyles.body01.copyWith(color: theme.textPrimary),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            ?content,
            if (actions != null && actions.isNotEmpty) ...<Widget>[
              const SizedBox(height: CarbonSpacing.spacing05),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  for (int i = 0; i < actions.length; i++) ...<Widget>[
                    if (i > 0) const SizedBox(width: CarbonSpacing.spacing05),
                    actions[i],
                  ],
                ],
              ),
            ],
          ],
        ),
      ),
    );
  }
}
