// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the GNU Affero General
// Public License v3.0 or later. See the LICENSE file in the project root.

import 'package:carbide/carbide.dart';
import 'package:flutter/services.dart' show LogicalKeyboardKey;
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../support/a11y.dart';
import '../../support/golden.dart';

/// OverlayPortal needs an Overlay ancestor; TapRegion needs a surface.
Widget _host(Widget child) => Directionality(
  textDirection: TextDirection.ltr,
  child: TapRegionSurface(
    child: CarbonTheme(
      data: CarbonThemeData.white,
      child: Overlay(
        initialEntries: <OverlayEntry>[
          OverlayEntry(
            builder: (BuildContext context) => Stack(
              children: <Widget>[
                Positioned.fill(
                  child: GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: () {},
                  ),
                ),
                Center(child: child),
              ],
            ),
          ),
        ],
      ),
    ),
  ),
);

void main() {
  setUp(() {
    FocusManager.instance.highlightStrategy =
        FocusHighlightStrategy.alwaysTraditional;
  });
  tearDown(() {
    FocusManager.instance.highlightStrategy = FocusHighlightStrategy.automatic;
  });

  group('layout / spec-lock', () {
    testWidgets('the default trigger box matches each size', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        _host(
          Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              for (final CarbonAILabelSize size in CarbonAILabelSize.values)
                CarbonAILabel(
                  key: ValueKey<CarbonAILabelSize>(size),
                  size: size,
                ),
            ],
          ),
        ),
      );
      for (final CarbonAILabelSize size in CarbonAILabelSize.values) {
        expect(
          tester.getSize(
            find.descendant(
              of: find.byKey(ValueKey<CarbonAILabelSize>(size)),
              matching: find.byType(AnimatedContainer),
            ),
          ),
          Size(size.dimension, size.dimension),
          reason: '$size box should be ${size.dimension}px',
        );
      }
    });

    testWidgets('mini and 2xs keep a 24px hit target', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        _host(const CarbonAILabel(size: CarbonAILabelSize.mini)),
      );
      expect(tester.getSize(find.byType(CarbonAILabel)).width, 24);
    });

    testWidgets('renders the AI text', (WidgetTester tester) async {
      await tester.pumpWidget(_host(const CarbonAILabel()));
      expect(find.text('AI'), findsOneWidget);
    });

    testWidgets('the callout surface uses the AI popover tokens', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(_host(const CarbonAILabel()));
      final CarbonPopover popover = tester.widget<CarbonPopover>(
        find.byType(CarbonPopover),
      );
      expect(popover.surfaceColor, CarbonThemeData.white.aiPopoverBackground);
      expect(popover.surfaceBorderColor, CarbonThemeData.white.aiBorderStart);
    });
  });

  group('open / close', () {
    testWidgets('tap toggles the callout', (WidgetTester tester) async {
      await tester.pumpWidget(
        _host(const CarbonAILabel(content: Text('Generated by AI'))),
      );
      expect(find.text('Generated by AI'), findsNothing);
      await tester.tap(find.text('AI'));
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsOneWidget);
      await tester.tap(find.text('AI'));
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsNothing);
    });

    testWidgets('Enter opens the callout', (WidgetTester tester) async {
      final FocusNode node = FocusNode();
      addTearDown(node.dispose);
      await tester.pumpWidget(
        _host(
          CarbonAILabel(
            focusNode: node,
            content: const Text('Generated by AI'),
          ),
        ),
      );
      node.requestFocus();
      await tester.pump();
      await tester.sendKeyEvent(LogicalKeyboardKey.enter);
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsOneWidget);
    });

    testWidgets('outside tap and Escape close it', (WidgetTester tester) async {
      final FocusNode node = FocusNode();
      addTearDown(node.dispose);
      await tester.pumpWidget(
        _host(
          CarbonAILabel(
            focusNode: node,
            defaultOpen: true,
            content: const Text('Generated by AI'),
          ),
        ),
      );
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsOneWidget);

      await tester.tapAt(const Offset(5, 5));
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsNothing);

      // Reopen and dismiss with Escape.
      await tester.tap(find.text('AI'));
      await tester.pumpAndSettle();
      node.requestFocus();
      await tester.pump();
      await tester.sendKeyEvent(LogicalKeyboardKey.escape);
      await tester.pumpAndSettle();
      expect(find.text('Generated by AI'), findsNothing);
    });

    testWidgets('actions render beneath the content', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        _host(
          const CarbonAILabel(
            defaultOpen: true,
            content: Text('Body'),
            actions: <Widget>[Text('Cancel'), Text('Apply')],
          ),
        ),
      );
      await tester.pumpAndSettle();
      expect(find.text('Apply'), findsOneWidget);
      expect(
        tester.getTopLeft(find.text('Apply')).dy,
        greaterThan(tester.getTopLeft(find.text('Body')).dy),
      );
    });
  });

  group('revert', () {
    testWidgets('shows a revert button instead of the trigger', (
      WidgetTester tester,
    ) async {
      bool reverted = false;
      await tester.pumpWidget(
        _host(
          CarbonAILabel(revertActive: true, onRevert: () => reverted = true),
        ),
      );
      expect(find.byType(CarbonPopover), findsNothing);
      expect(find.text('AI'), findsNothing);

      await tester.tap(find.byType(CarbonButton));
      await tester.pumpAndSettle();
      expect(reverted, isTrue);
    });
  });

  group('inline', () {
    testWidgets('renders the AI text with the optional label', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        _host(
          const CarbonAILabel(
            inline: true,
            textLabel: 'Beta',
            size: CarbonAILabelSize.lg,
          ),
        ),
      );
      expect(find.text('AI Beta'), findsOneWidget);
    });
  });

  group('semantics', () {
    testWidgets('the trigger is a labelled button', (
      WidgetTester tester,
    ) async {
      final SemanticsHandle handle = tester.ensureSemantics();
      await tester.pumpWidget(_host(const CarbonAILabel()));
      expect(find.bySemanticsLabel('AI Show information'), findsOneWidget);
      handle.dispose();
    });

    testWidgets('a text label is reflected in the accessible name', (
      WidgetTester tester,
    ) async {
      final SemanticsHandle handle = tester.ensureSemantics();
      await tester.pumpWidget(_host(const CarbonAILabel(textLabel: 'summary')));
      expect(find.bySemanticsLabel('AI summary'), findsOneWidget);
      handle.dispose();
    });
  });

  group('accessibility guidelines (#226)', () {
    testWidgets('meets tap-target and label guidelines', (
      WidgetTester tester,
    ) async {
      final SemanticsHandle handle = tester.ensureSemantics();
      // The plain host (no unlabeled backdrop fixture): the backdrop in
      // [_host] exists only for tap-outside tests and would fail the
      // labeled sweep on scaffolding rather than product code.
      await tester.pumpWidget(
        Directionality(
          textDirection: TextDirection.ltr,
          child: TapRegionSurface(
            child: CarbonTheme(
              data: CarbonThemeData.white,
              child: Overlay(
                initialEntries: <OverlayEntry>[
                  OverlayEntry(
                    builder: (BuildContext context) =>
                        const Center(child: CarbonAILabel()),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
      // Tap-target gate off: every AI label chip is 16–32px by design
      // (`_ai-label.scss` sizes mini…xl), with a padded 24px hit target —
      // all below the 48dp guideline.
      await expectA11y(tester, tapTargets: false);
      handle.dispose();
    });
  });

  group('motion (#235)', () {
    // Spec source: `slug/_slug.scss` (the real AILabel styles): the trigger
    // transitions color/border/box-shadow/background at $duration-fast-01
    // motion(entrance, productive). The callout itself has no motion.
    testWidgets('spec lock: trigger tint is fast-01 × entrance-productive', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(_host(const CarbonAILabel()));
      final AnimatedContainer box = tester.widget<AnimatedContainer>(
        find.byType(AnimatedContainer),
      );
      expect(box.duration, CarbonDuration.fast01);
      expect(box.curve, CarbonEasing.entranceProductive);
    });

    testWidgets('reduced motion: trigger tints apply instantly', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MediaQuery(
          data: const MediaQueryData(disableAnimations: true),
          child: _host(const CarbonAILabel()),
        ),
      );
      expect(
        tester
            .widget<AnimatedContainer>(find.byType(AnimatedContainer))
            .duration,
        Duration.zero,
      );
    });

    testWidgets('reduced motion: inline affordance tints apply instantly', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MediaQuery(
          data: const MediaQueryData(disableAnimations: true),
          child: _host(const CarbonAILabel(inline: true)),
        ),
      );
      expect(
        tester
            .widget<AnimatedContainer>(find.byType(AnimatedContainer))
            .duration,
        Duration.zero,
      );
    });
  });

  group('goldens', () {
    Widget overlaid(Widget child) => Overlay(
      initialEntries: <OverlayEntry>[
        OverlayEntry(builder: (BuildContext context) => Center(child: child)),
      ],
    );

    testWidgets('default triggers across sizes', (WidgetTester tester) async {
      await expectThemeGoldens(
        tester,
        name: 'ai_label_sizes',
        containsText: true,
        size: const Size(420, 96),
        builder: (BuildContext context) => overlaid(
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              for (final CarbonAILabelSize size in CarbonAILabelSize.values)
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 6),
                  child: CarbonAILabel(size: size),
                ),
            ],
          ),
        ),
      );
    });

    testWidgets('open callout', (WidgetTester tester) async {
      await expectThemeGoldens(
        tester,
        name: 'ai_label_open',
        containsText: true,
        size: const Size(300, 220),
        builder: (BuildContext context) => overlaid(
          const CarbonAILabel(
            defaultOpen: true,
            size: CarbonAILabelSize.md,
            content: Text('This content was generated by AI.'),
          ),
        ),
        afterPump: (WidgetTester tester) async {
          await tester.pumpAndSettle();
        },
      );
    });

    testWidgets('inline variant', (WidgetTester tester) async {
      await expectThemeGoldens(
        tester,
        name: 'ai_label_inline',
        containsText: true,
        size: const Size(160, 80),
        builder: (BuildContext context) => overlaid(
          const CarbonAILabel(
            inline: true,
            textLabel: 'Generated',
            size: CarbonAILabelSize.lg,
          ),
        ),
      );
    });

    testWidgets('focus ring', (WidgetTester tester) async {
      final FocusNode node = FocusNode();
      addTearDown(node.dispose);
      await expectThemeGoldens(
        tester,
        name: 'ai_label_focus',
        containsText: true,
        size: const Size(96, 96),
        builder: (BuildContext context) => overlaid(
          CarbonAILabel(focusNode: node, size: CarbonAILabelSize.md),
        ),
        afterPump: (WidgetTester tester) async {
          node.requestFocus();
          await tester.pumpAndSettle();
        },
      );
    });

    testWidgets('revert button', (WidgetTester tester) async {
      await expectThemeGoldens(
        tester,
        name: 'ai_label_revert',
        size: const Size(72, 72),
        builder: (BuildContext context) =>
            overlaid(CarbonAILabel(revertActive: true, onRevert: () {})),
      );
    });
  });
}
