// Copyright 2026 Bizjak Tech OÜ

// GENERATED by tool/generate_gallery_examples.py. Do not edit.

part of 'tier_a_pages.dart';

extension _TagPageStateSource on _TagPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_type': 'CarbonTagType.${_type.name}',
        '_selected': sourceValue(_selected),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class TagExample extends StatefulWidget {
  const TagExample();
  @override
  State<TagExample> createState() => _TagExampleState();
}

class _TagExampleState extends State<TagExample> {
  CarbonTagType _type = @@_type@@;
  bool _selected = @@_selected@@;

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: CarbonSpacing.spacing03,
      runSpacing: CarbonSpacing.spacing03,
      children: <Widget>[
        CarbonTag(label: 'Read-only', type: _type, icon: CarbonIcons.user),
        CarbonDismissibleTag(label: 'Dismissible', type: _type, onClose: () {}),
        CarbonSelectableTag(
          label: 'Selectable',
          selected: _selected,
          onChanged: (bool v) => setState(() => _selected = v),
        ),
        CarbonOperationalTag(
          label: 'Operational',
          type: _type,
          onPressed: () {},
        ),
      ],
    );
  }
}
''');
  }
}

extension _LinkPageStateSource on _LinkPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_size': 'CarbonLinkSize.${_size.name}',
        '_inline': sourceValue(_inline),
        '_withIcon': sourceValue(_withIcon),
        '_enabled': sourceValue(_enabled),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class LinkExample extends StatefulWidget {
  const LinkExample();
  @override
  State<LinkExample> createState() => _LinkExampleState();
}

class _LinkExampleState extends State<LinkExample> {
  CarbonLinkSize _size = @@_size@@;
  bool _inline = @@_inline@@;
  bool _withIcon = @@_withIcon@@;
  bool _enabled = @@_enabled@@;

  @override
  Widget build(BuildContext context) {
    return CarbonLink(
      label: 'Learn more',
      size: _size,
      inline: _inline,
      icon: _withIcon ? CarbonIcons.launch : null,
      onPressed: _enabled ? () {} : null,
    );
  }
}
''');
  }
}

extension _TilePageStateSource on _TilePageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_selected': sourceValue(_selected),
        '_expanded': sourceValue(_expanded),
        '_ai': sourceValue(_ai),
        '_radio': sourceValue(_radio),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class TileExample extends StatefulWidget {
  const TileExample();
  @override
  State<TileExample> createState() => _TileExampleState();
}

class _TileExampleState extends State<TileExample> {
  bool _selected = @@_selected@@;
  bool _expanded = @@_expanded@@;
  bool _ai = @@_ai@@;
  int _radio = @@_radio@@;

  Widget? get _aiLabel =>
      _ai ? const CarbonAILabel(size: CarbonAILabelSize.mini) : null;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    Widget body(String s) => Text(
      s,
      style: CarbonTypeStyles.bodyCompact01.copyWith(color: t.textPrimary),
    );
    return Wrap(
      spacing: CarbonSpacing.spacing05,
      runSpacing: CarbonSpacing.spacing05,
      children: <Widget>[
        SizedBox(
          width: 220,
          child: CarbonTile(aiLabel: _aiLabel, child: body('Base tile')),
        ),
        SizedBox(
          width: 220,
          child: CarbonClickableTile(
            icon: CarbonIcons.launch,
            onPressed: () {},
            aiLabel: _aiLabel,
            child: body('Clickable tile'),
          ),
        ),
        SizedBox(
          width: 220,
          child: CarbonSelectableTile(
            selected: _selected,
            onChanged: (bool v) => setState(() => _selected = v),
            aiLabel: _aiLabel,
            child: body('Selectable tile'),
          ),
        ),
        SizedBox(
          width: 220,
          child: Column(
            children: <Widget>[
              for (int i = 0; i < 2; i++)
                Padding(
                  padding: EdgeInsets.only(
                    top: i == 0 ? 0 : CarbonSpacing.spacing02,
                  ),
                  child: CarbonRadioTile(
                    selected: _radio == i,
                    onSelected: () => setState(() => _radio = i),
                    aiLabel: _aiLabel,
                    child: body('Radio tile ${i + 1}'),
                  ),
                ),
            ],
          ),
        ),
        SizedBox(
          width: 220,
          child: CarbonExpandableTile(
            expanded: _expanded,
            onExpandedChanged: (bool v) => setState(() => _expanded = v),
            aiLabel: _aiLabel,
            aboveTheFold: body('Expandable tile'),
            belowTheFold: body('Hidden detail revealed on expand.'),
          ),
        ),
      ],
    );
  }
}
''');
  }
}

extension _LoadingPageSource on _LoadingPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class LoadingExample extends StatelessWidget {
  const LoadingExample();
  @override
  Widget build(BuildContext context) {
    return const Wrap(
      spacing: CarbonSpacing.spacing09,
      runSpacing: CarbonSpacing.spacing07,
      crossAxisAlignment: WrapCrossAlignment.center,
      children: <Widget>[
        CarbonLoading(),
        CarbonLoading(small: true),
        CarbonInlineLoading(description: 'Loading…'),
        CarbonInlineLoading(
          status: CarbonInlineLoadingStatus.finished,
          description: 'Done',
        ),
      ],
    );
  }
}
''');
  }
}

extension _ProgressBarPageStateSource on _ProgressBarPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_value': sourceValue(_value),
        '_indeterminate': sourceValue(_indeterminate),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ProgressBarExample extends StatefulWidget {
  const ProgressBarExample();
  @override
  State<ProgressBarExample> createState() => _ProgressBarExampleState();
}

class _ProgressBarExampleState extends State<ProgressBarExample> {
  double _value = @@_value@@;
  bool _indeterminate = @@_indeterminate@@;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: CarbonProgressBar(
        label: 'Uploading',
        helperText: _indeterminate ? null : '${_value.round()}%',
        value: _indeterminate ? null : _value,
      ),
    );
  }
}
''');
  }
}

extension _ListPageSource on _ListPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ListExample extends StatelessWidget {
  const ListExample();
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    CarbonListItem item(String s) => CarbonListItem(
      child: Text(
        s,
        style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary),
      ),
    );
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Expanded(
          child: CarbonUnorderedList(
            children: <CarbonListItem>[
              item('Apples'),
              item('Oranges'),
              item('Pears'),
            ],
          ),
        ),
        Expanded(
          child: CarbonOrderedList(
            children: <CarbonListItem>[
              item('First'),
              item('Second'),
              item('Third'),
            ],
          ),
        ),
      ],
    );
  }
}
''');
  }
}

extension _StackPageStateSource on _StackPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_gap': sourceValue(_gap)},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class StackExample extends StatefulWidget {
  const StackExample();
  @override
  State<StackExample> createState() => _StackExampleState();
}

class _StackExampleState extends State<StackExample> {
  double _gap = @@_gap@@;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    Widget box(String s) => DecoratedBox(
      decoration: BoxDecoration(color: t.layerAccent01),
      child: Padding(
        padding: const EdgeInsets.all(CarbonSpacing.spacing03),
        child: Text(
          s,
          style: CarbonTypeStyles.bodyCompact01.copyWith(color: t.textPrimary),
        ),
      ),
    );
    return CarbonStack(
      gapStep: _gap.round(),
      children: <Widget>[box('One'), box('Two'), box('Three')],
    );
  }
}
''');
  }
}

extension _HeadingPageSource on _HeadingPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class HeadingExample extends StatelessWidget {
  const HeadingExample();
  @override
  Widget build(BuildContext context) {
    return const CarbonSection(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          CarbonHeading('Level 1 heading'),
          SizedBox(height: CarbonSpacing.spacing05),
          CarbonSection(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[CarbonHeading('Nested level 2 heading')],
            ),
          ),
        ],
      ),
    );
  }
}
''');
  }
}

extension _CopyButtonPageStateSource on _CopyButtonPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_size': 'CarbonCopySize.${_size.name}',
        '_enabled': sourceValue(_enabled),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class CopyButtonExample extends StatefulWidget {
  const CopyButtonExample();
  @override
  State<CopyButtonExample> createState() => _CopyButtonExampleState();
}

class _CopyButtonExampleState extends State<CopyButtonExample> {
  CarbonCopySize _size = @@_size@@;
  bool _enabled = @@_enabled@@;

  @override
  Widget build(BuildContext context) {
    return CarbonCopyButton(
      value: 'npm i @carbon/react',
      size: _size,
      enabled: _enabled,
    );
  }
}
''');
  }
}

extension _CodeSnippetPageStateSource on _CodeSnippetPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_type': 'CarbonCodeSnippetType.${_type.name}'},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class CodeSnippetExample extends StatefulWidget {
  const CodeSnippetExample();
  @override
  State<CodeSnippetExample> createState() => _CodeSnippetExampleState();
}

class _CodeSnippetExampleState extends State<CodeSnippetExample> {
  CarbonCodeSnippetType _type = @@_type@@;

  String get _code => switch (_type) {
    CarbonCodeSnippetType.inline => 'carbide',
    CarbonCodeSnippetType.single => 'flutter pub add carbide',
    CarbonCodeSnippetType.multi =>
      "import 'package:carbide/carbide.dart';\n\n"
          'void main() {\n  runApp(const MyApp());\n}',
  };

  @override
  Widget build(BuildContext context) {
    final CarbonCodeSnippet snippet = CarbonCodeSnippet(
      code: _code,
      type: _type,
    );
    return _type == CarbonCodeSnippetType.inline
        ? snippet
        : SizedBox(width: 320, child: snippet);
  }
}
''');
  }
}

extension _IconButtonPageStateSource on _IconButtonPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_kind': 'CarbonButtonKind.${_kind.name}'},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class IconButtonExample extends StatefulWidget {
  const IconButtonExample();
  @override
  State<IconButtonExample> createState() => _IconButtonExampleState();
}

class _IconButtonExampleState extends State<IconButtonExample> {
  CarbonButtonKind _kind = @@_kind@@;

  @override
  Widget build(BuildContext context) {
    return CarbonIconButton(
      icon: CarbonIcons.add,
      label: 'Add item',
      kind: _kind,
      onPressed: () {},
    );
  }
}
''');
  }
}

extension _IndicatorsPageSource on _IndicatorsPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class IndicatorsExample extends StatelessWidget {
  const IndicatorsExample();
  @override
  Widget build(BuildContext context) {
    return const Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Row(
          children: <Widget>[
            CarbonBadgeIndicator(),
            SizedBox(width: 16),
            CarbonBadgeIndicator(count: 8),
            SizedBox(width: 16),
            CarbonBadgeIndicator(count: 4000),
          ],
        ),
        SizedBox(height: 16),
        CarbonIconIndicator(
          kind: CarbonIconIndicatorKind.failed,
          label: 'Failed',
        ),
        SizedBox(height: 8),
        CarbonIconIndicator(
          kind: CarbonIconIndicatorKind.succeeded,
          label: 'Succeeded',
        ),
        SizedBox(height: 16),
        CarbonShapeIndicator(
          kind: CarbonShapeIndicatorKind.critical,
          label: 'Critical',
        ),
        SizedBox(height: 8),
        CarbonShapeIndicator(
          kind: CarbonShapeIndicatorKind.stable,
          label: 'Stable',
        ),
      ],
    );
  }
}
''');
  }
}

extension _AspectRatioPageStateSource on _AspectRatioPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_ratio': 'CarbonAspectRatioValue.${_ratio.name}'},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class AspectRatioExample extends StatefulWidget {
  const AspectRatioExample();
  @override
  State<AspectRatioExample> createState() => _AspectRatioExampleState();
}

class _AspectRatioExampleState extends State<AspectRatioExample> {
  CarbonAspectRatioValue _ratio = @@_ratio@@;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return SizedBox(
      width: 240,
      child: CarbonAspectRatio(
        ratio: _ratio,
        child: ColoredBox(color: t.layerAccent01),
      ),
    );
  }
}
''');
  }
}

extension _GridPageStateSource on _GridPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_mode': 'CarbonGridMode.${_mode.name}',
        '_fullWidth': sourceValue(_fullWidth),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class GridExample extends StatefulWidget {
  const GridExample();

  @override
  State<GridExample> createState() => _GridExampleState();
}

class _GridExampleState extends State<GridExample> {
  CarbonGridMode _mode = @@_mode@@;
  bool _fullWidth = @@_fullWidth@@;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return CarbonGrid(
      mode: _mode,
      fullWidth: _fullWidth,
      rowSpacing: 8,
      children: <Widget>[
        for (int i = 0; i < 4; i++)
          CarbonColumn(
            sm: 2,
            md: 4,
            lg: 4,
            child: SizedBox(
              height: 48,
              child: ColoredBox(color: t.layerAccent01),
            ),
          ),
      ],
    );
  }
}
''');
  }
}

extension _SkeletonsPageSource on _SkeletonsPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class SkeletonsExample extends StatelessWidget {
  const SkeletonsExample();
  @override
  Widget build(BuildContext context) {
    return const Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        SizedBox(width: 240, child: CarbonTextInputSkeleton()),
        SizedBox(height: 24),
        CarbonCheckboxSkeleton(),
        SizedBox(height: 24),
        SizedBox(
          width: 280,
          child: CarbonDataTableSkeleton(rowCount: 3, columnCount: 3),
        ),
        SizedBox(height: 24),
        SizedBox(width: 240, child: CarbonAISkeletonText(paragraph: true)),
        SizedBox(height: 24),
        Row(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            CarbonAISkeletonIcon(),
            SizedBox(width: 24),
            CarbonAISkeletonPlaceholder(width: 64, height: 64),
          ],
        ),
      ],
    );
  }
}
''');
  }
}
