// Copyright 2026 Bizjak Tech OÜ

// GENERATED by tool/generate_gallery_examples.py. Do not edit.

part of 'tier_c_pages.dart';

extension _DropdownPageStateSource on _DropdownPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_readOnly': sourceValue(_readOnly),
        '_disabled': sourceValue(_disabled),
        '_value': sourceValue(_value),
        '_ai': sourceValue(_ai),
        '_fluid': sourceValue(_fluid),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class DropdownExample extends StatefulWidget {
  const DropdownExample();
  @override
  State<DropdownExample> createState() => _DropdownExampleState();
}

class _DropdownExampleState extends State<DropdownExample> {
  bool _readOnly = @@_readOnly@@;
  bool _disabled = @@_disabled@@;
  String _value = @@_value@@;
  bool _ai = @@_ai@@;
  bool _fluid = @@_fluid@@;
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: CarbonDropdown<String>(
        readOnly: _readOnly,
        disabled: _disabled,
        titleText: 'Favourite colour',
        selectedItem: _value,
        onChanged: (String v) => setState(() => _value = v),
        aiLabel: _ai ? const CarbonAILabel(size: CarbonAILabelSize.mini) : null,
        fluid: _fluid,
        items: const <CarbonDropdownItem<String>>[
          CarbonDropdownItem<String>(value: 'cyan', label: 'Cyan'),
          CarbonDropdownItem<String>(value: 'magenta', label: 'Magenta'),
          CarbonDropdownItem<String>(value: 'teal', label: 'Teal'),
        ],
      ),
    );
  }
}
''');
  }
}

extension _ComboBoxPageStateSource on _ComboBoxPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_readOnly': sourceValue(_readOnly),
        '_disabled': sourceValue(_disabled),
        '_value': sourceValue(_value),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ComboBoxExample extends StatefulWidget {
  const ComboBoxExample();
  @override
  State<ComboBoxExample> createState() => _ComboBoxExampleState();
}

class _ComboBoxExampleState extends State<ComboBoxExample> {
  bool _readOnly = @@_readOnly@@;
  bool _disabled = @@_disabled@@;
  String? _value = @@_value@@;
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: CarbonComboBox<String>(
        readOnly: _readOnly,
        disabled: _disabled,
        titleText: 'Country',
        selectedItem: _value,
        onChanged: (String? v) => setState(() => _value = v),
        items: const <CarbonComboBoxItem<String>>[
          CarbonComboBoxItem<String>(value: 'ee', label: 'Estonia'),
          CarbonComboBoxItem<String>(value: 'fi', label: 'Finland'),
          CarbonComboBoxItem<String>(value: 'se', label: 'Sweden'),
          CarbonComboBoxItem<String>(value: 'no', label: 'Norway'),
        ],
      ),
    );
  }
}
''');
  }
}

extension _MultiSelectPageStateSource on _MultiSelectPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_readOnly': sourceValue(_readOnly),
        '_disabled': sourceValue(_disabled),
        '_filterable': sourceValue(_filterable),
        '_selected': sourceSet(_selected, 'String'),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class MultiSelectExample extends StatefulWidget {
  const MultiSelectExample();
  @override
  State<MultiSelectExample> createState() => _MultiSelectExampleState();
}

class _MultiSelectExampleState extends State<MultiSelectExample> {
  bool _readOnly = @@_readOnly@@;
  bool _disabled = @@_disabled@@;
  bool _filterable = @@_filterable@@;
  Set<String> _selected = @@_selected@@;
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: CarbonMultiSelect<String>(
        readOnly: _readOnly,
        disabled: _disabled,
        titleText: 'Permissions',
        filterable: _filterable,
        label: 'Choose permissions',
        selectedValues: _selected,
        onChanged: (Set<String> v) => setState(() => _selected = v),
        items: const <CarbonMultiSelectItem<String>>[
          CarbonMultiSelectItem<String>(value: 'read', label: 'Read'),
          CarbonMultiSelectItem<String>(value: 'write', label: 'Write'),
          CarbonMultiSelectItem<String>(value: 'admin', label: 'Admin'),
        ],
      ),
    );
  }
}
''');
  }
}

extension _TooltipPageSource on _TooltipPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class TooltipExample extends StatelessWidget {
  const TooltipExample();
  @override
  Widget build(BuildContext context) {
    return CarbonTooltip(
      label: 'Carbide is an unofficial Carbon port.',
      child: CarbonButton(label: 'Hover me', onPressed: () {}),
    );
  }
}
''');
  }
}

extension _ToggletipPageSource on _ToggletipPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ToggletipExample extends StatelessWidget {
  const ToggletipExample();
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return CarbonToggletip(
      content: Text(
        'Toggletips hold interactive content and stay open until dismissed.',
        style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary),
      ),
    );
  }
}
''');
  }
}

extension _OverflowMenuPageSource on _OverflowMenuPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class OverflowMenuExample extends StatelessWidget {
  const OverflowMenuExample();
  @override
  Widget build(BuildContext context) {
    return CarbonOverflowMenu(
      items: <Widget>[
        CarbonMenuItem(label: 'Edit', icon: CarbonIcons.edit, onPressed: () {}),
        CarbonMenuItem(
          label: 'Duplicate',
          icon: CarbonIcons.copy,
          onPressed: () {},
        ),
        const CarbonMenuItemDivider(),
        CarbonMenuItem(
          label: 'Delete',
          icon: CarbonIcons.trashCan,
          kind: CarbonMenuItemKind.danger,
          onPressed: () {},
        ),
      ],
    );
  }
}
''');
  }
}

extension _TabsPageStateSource on _TabsPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_vertical': sourceValue(_vertical),
        '_many': sourceValue(_many),
        '_manual': sourceValue(_manual),
        '_variant': 'CarbonTabVariant.${_variant.name}',
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class TabsExample extends StatefulWidget {
  const TabsExample();
  @override
  State<TabsExample> createState() => _TabsExampleState();
}

class _TabsExampleState extends State<TabsExample> {
  bool _vertical = @@_vertical@@;
  bool _many = @@_many@@;
  bool _manual = @@_manual@@;
  CarbonTabVariant _variant = @@_variant@@;
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    Widget panel(String s) => Padding(
      padding: const EdgeInsets.only(top: CarbonSpacing.spacing05),
      child: Text(
        s,
        style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary),
      ),
    );
    final List<CarbonTab> tabs = _many
        ? <CarbonTab>[
            for (int i = 0; i < 18; i++)
              CarbonTab(label: 'Category ${i + 1}', disabled: i == 2),
          ]
        : const <CarbonTab>[
            CarbonTab(label: 'Overview'),
            CarbonTab(label: 'Specs'),
            CarbonTab(label: 'Reviews'),
          ];
    final List<Widget> panels = _many
        ? <Widget>[
            for (int i = 0; i < 18; i++) panel('Category ${i + 1} content.'),
          ]
        : <Widget>[
            panel('Overview content.'),
            panel('Technical specifications.'),
            panel('Customer reviews.'),
          ];
    final CarbonTabActivationMode activation = _manual
        ? CarbonTabActivationMode.manual
        : CarbonTabActivationMode.automatic;
    return SizedBox(
      width: _many && !_vertical ? 320 : 480,
      child: _vertical
          ? SizedBox(
              height: 260,
              child: CarbonTabsVertical(
                tabs: tabs,
                panels: panels,
                activation: activation,
              ),
            )
          : CarbonTabs(
              tabs: tabs,
              panels: panels,
              activation: activation,
              variant: _variant,
            ),
    );
  }
}
''');
  }
}

extension _AccordionPageSource on _AccordionPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class AccordionExample extends StatelessWidget {
  const AccordionExample();
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    Widget body(String s) =>
        Text(s, style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary));
    return SizedBox(
      width: 480,
      child: CarbonAccordion(
        children: <CarbonAccordionItem>[
          CarbonAccordionItem(
            title: 'Shipping',
            initiallyOpen: true,
            child: body('Free standard shipping on orders over €50.'),
          ),
          CarbonAccordionItem(title: 'Returns', child: body('30-day returns.')),
          CarbonAccordionItem(
            title: 'Warranty',
            child: body('Two-year warranty.'),
          ),
        ],
      ),
    );
  }
}
''');
  }
}

extension _ContentSwitcherPageStateSource on _ContentSwitcherPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_index': sourceValue(_index),
        '_iconOnly': sourceValue(_iconOnly),
        '_disabled': sourceValue(_disabled),
        '_width': sourceValue(_width),
        '_textScale': sourceValue(_textScale),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ContentSwitcherExample extends StatefulWidget {
  const ContentSwitcherExample();
  @override
  State<ContentSwitcherExample> createState() => _ContentSwitcherExampleState();
}

class _ContentSwitcherExampleState extends State<ContentSwitcherExample> {
  int _index = @@_index@@;
  bool _iconOnly = @@_iconOnly@@;
  bool _disabled = @@_disabled@@;
  double _width = @@_width@@;
  double _textScale = @@_textScale@@;
  @override
  Widget build(BuildContext context) {
    return MediaQuery(
      data: MediaQuery.of(context)
          .copyWith(textScaler: TextScaler.linear(_textScale)),
      child: SizedBox(
        width: _iconOnly ? null : _width,
        child: CarbonContentSwitcher(
          selectedIndex: _index,
          onChanged: (int i) => setState(() => _index = i),
          switches: _iconOnly
              ? <CarbonSwitch>[
                  const CarbonSwitch(
                    icon: CarbonIcons.list,
                    semanticLabel: 'List view',
                  ),
                  const CarbonSwitch(
                    icon: CarbonIcons.grid,
                    semanticLabel: 'Grid view',
                  ),
                  CarbonSwitch(
                    icon: CarbonIcons.archive,
                    semanticLabel: 'Archived view',
                    disabled: _disabled,
                  ),
                ]
              : <CarbonSwitch>[
                  const CarbonSwitch(text: 'Day'),
                  const CarbonSwitch(text: 'Week'),
                  CarbonSwitch(text: 'Month', disabled: _disabled),
                ],
        ),
      ),
    );
  }
}
''');
  }
}

extension _BreadcrumbPageStateSource on _BreadcrumbPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_many': sourceValue(_many),
        '_narrow': sourceValue(_narrow),
        '_rtl': sourceValue(_rtl),
        '_trailing': sourceValue(_trailing),
        '_opened': sourceValue(_opened),
        '_size': 'CarbonLinkSize.${_size.name}',
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class BreadcrumbExample extends StatefulWidget {
  const BreadcrumbExample();
  @override
  State<BreadcrumbExample> createState() => _BreadcrumbExampleState();
}

class _BreadcrumbExampleState extends State<BreadcrumbExample> {
  bool _many = @@_many@@;
  bool _narrow = @@_narrow@@;
  bool _rtl = @@_rtl@@;
  bool _trailing = @@_trailing@@;
  String _opened = @@_opened@@;
  CarbonLinkSize _size = @@_size@@;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData theme = CarbonTheme.of(context);
    final List<String> labels = _many
        ? <String>[
            'Home',
            'Organization',
            'Projects',
            'Research',
            'Reports',
            'Quarter',
            'Breadcrumb',
          ]
        : <String>['Home', 'Components', 'Breadcrumb'];
    final List<CarbonBreadcrumbItem> items = <CarbonBreadcrumbItem>[
      for (int i = 0; i < labels.length; i++)
        CarbonBreadcrumbItem(
          label: labels[i],
          isCurrentPage: i == labels.length - 1,
          onPressed: () => setState(() => _opened = labels[i]),
        ),
    ];
    return Directionality(
      textDirection: _rtl ? TextDirection.rtl : TextDirection.ltr,
      child: SizedBox(
        width: _narrow ? 320 : 760,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            CarbonBreadcrumb(
              items: items,
              size: _size,
              noTrailingSlash: !_trailing,
            ),
            const SizedBox(height: CarbonSpacing.spacing05),
            Text(
              'Opened: $_opened',
              style: CarbonTypeStyles.body01.copyWith(color: theme.textPrimary),
            ),
          ],
        ),
      ),
    );
  }
}
''');
  }
}

extension _PaginationPageStateSource on _PaginationPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_page': sourceValue(_page),
        '_pageSize': sourceValue(_pageSize),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class PaginationExample extends StatefulWidget {
  const PaginationExample();
  @override
  State<PaginationExample> createState() => _PaginationExampleState();
}

class _PaginationExampleState extends State<PaginationExample> {
  int _page = @@_page@@;
  int _pageSize = @@_pageSize@@;
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SizedBox(
        width: 1040,
        child: CarbonPagination(
          page: _page,
          pageSize: _pageSize,
          totalItems: 248,
          onPageChanged: (int p) => setState(() => _page = p),
          onPageSizeChanged: (int s) => setState(() {
            _pageSize = s;
            _page = 1;
          }),
        ),
      ),
    );
  }
}
''');
  }
}

extension _ModalPageStateSource on _ModalPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_open': sourceValue(_open),
        '_fullWidth': sourceValue(_fullWidth),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ModalExample extends StatefulWidget {
  const ModalExample();
  @override
  State<ModalExample> createState() => _ModalExampleState();
}

class _ModalExampleState extends State<ModalExample> {
  bool _open = @@_open@@;
  bool _fullWidth = @@_fullWidth@@;
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return Stack(
      children: <Widget>[
        CarbonButton(
          label: 'Open modal',
          onPressed: () => setState(() => _open = true),
        ),
        CarbonModal(
          open: _open,
          title: _fullWidth ? 'Members' : 'Delete service?',
          onClose: () => setState(() => _open = false),
          danger: !_fullWidth,
          isFullWidth: _fullWidth,
          primaryButton: CarbonModalAction(
            label: _fullWidth ? 'Add member' : 'Delete',
            onPressed: () => setState(() => _open = false),
          ),
          secondaryButton: CarbonModalAction(
            label: 'Cancel',
            onPressed: () => setState(() => _open = false),
          ),
          child: _fullWidth
              ? const CarbonDataTable(
                  columns: <CarbonTableColumn>[
                    CarbonTableColumn(title: 'Name'),
                    CarbonTableColumn(title: 'Role'),
                  ],
                  rows: <CarbonTableRow>[
                    CarbonTableRow(cells: <Widget>[Text('Ada'), Text('Admin')]),
                    CarbonTableRow(
                      cells: <Widget>[Text('Grace'), Text('Editor')],
                    ),
                  ],
                )
              : Text(
                  'This action cannot be undone.',
                  style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary),
                ),
        ),
      ],
    );
  }
}
''');
  }
}

extension _DialogPageStateSource on _DialogPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_open': sourceValue(_open),
        '_modal': sourceValue(_modal),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class DialogExample extends StatefulWidget {
  const DialogExample();
  @override
  State<DialogExample> createState() => _DialogExampleState();
}

class _DialogExampleState extends State<DialogExample> {
  bool _open = @@_open@@;
  bool _modal = @@_modal@@;
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        CarbonButton(
          label: 'Open dialog',
          onPressed: () => setState(() => _open = true),
        ),
        CarbonDialog(
          open: _open,
          modal: _modal,
          onRequestClose: () => setState(() => _open = false),
          children: <Widget>[
            CarbonDialogHeader(
              controls: CarbonDialogControls(
                children: <Widget>[
                  CarbonDialogCloseButton(
                    onPressed: () => setState(() => _open = false),
                  ),
                ],
              ),
              children: const <Widget>[
                CarbonDialogSubtitle('Account'),
                CarbonDialogTitle('Update billing details'),
              ],
            ),
            const CarbonDialogBody(
              child: Text(
                'Changing the billing contact updates every invoice '
                'issued after the change.',
              ),
            ),
            CarbonDialogFooter(
              children: <Widget>[
                CarbonButton(
                  label: 'Cancel',
                  kind: CarbonButtonKind.secondary,
                  size: CarbonButtonSize.xl,
                  onPressed: () => setState(() => _open = false),
                ),
                CarbonButton(
                  label: 'Save',
                  size: CarbonButtonSize.xl,
                  onPressed: () => setState(() => _open = false),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }
}
''');
  }
}

extension _NotificationPageStateSource on _NotificationPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_narrow': sourceValue(_narrow),
        '_rtl': sourceValue(_rtl),
        '_scaled': sourceValue(_scaled),
        '_lowContrast': sourceValue(_lowContrast),
        '_actions': sourceValue(_actions),
        '_closes': sourceValue(_closes),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class NotificationExample extends StatefulWidget {
  const NotificationExample();

  @override
  State<NotificationExample> createState() => _NotificationExampleState();
}

class _NotificationExampleState extends State<NotificationExample> {
  bool _narrow = @@_narrow@@;
  bool _rtl = @@_rtl@@;
  bool _scaled = @@_scaled@@;
  bool _lowContrast = @@_lowContrast@@;
  int _actions = @@_actions@@;
  int _closes = @@_closes@@;

  @override
  Widget build(BuildContext context) {
    return MediaQuery(
      data: MediaQuery.of(context)
          .copyWith(textScaler: TextScaler.linear(_scaled ? 2 : 1)),
      child: Directionality(
        textDirection: _rtl ? TextDirection.rtl : TextDirection.ltr,
        child: SizedBox(
          width: _narrow ? 320 : 760,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text('Actions: $_actions; closes: $_closes'),
              const SizedBox(height: 16),
              for (final CarbonNotificationKind kind
                  in CarbonNotificationKind.values)
                Padding(
                  padding: const EdgeInsets.only(
                    bottom: CarbonSpacing.spacing05,
                  ),
                  child: CarbonInlineNotification(
                    kind: kind,
                    title:
                        '${kind.name[0].toUpperCase()}${kind.name.substring(1)}',
                    subtitle: 'An inline ${kind.name} notification.',
                    lowContrast: _lowContrast,
                    onClose: () => setState(() => _closes++),
                  ),
                ),
              Padding(
                padding: const EdgeInsets.only(bottom: CarbonSpacing.spacing05),
                child: CarbonActionableNotification(
                  kind: CarbonNotificationKind.warning,
                  title: 'Connection lost',
                  subtitle: 'Supporting detail for the optional action.',
                  actionLabel: 'Retry operation',
                  lowContrast: _lowContrast,
                  onAction: () => setState(() => _actions++),
                  onClose: () => setState(() => _closes++),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(bottom: CarbonSpacing.spacing05),
                child: CarbonToastNotification(
                  kind: CarbonNotificationKind.success,
                  title: 'Changes saved',
                  subtitle: 'Your changes are available.',
                  caption: 'Just now',
                  lowContrast: _lowContrast,
                  onClose: () => setState(() => _closes++),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(bottom: CarbonSpacing.spacing05),
                child: CarbonCallout(
                  title: 'Callout',
                  subtitle: 'A static, non-dismissible callout.',
                  actionLabel: 'Review',
                  lowContrast: _lowContrast,
                  onAction: () => setState(() => _actions++),
                ),
              ),
              const CarbonCallout(
                kind: CarbonNotificationKind.warning,
                title: 'Callout',
                subtitle: 'A low-contrast warning callout.',
                lowContrast: true,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
''');
  }
}

extension _ProgressIndicatorPageStateSource on _ProgressIndicatorPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_currentIndex': sourceValue(_currentIndex),
        '_vertical': sourceValue(_vertical),
        '_interactive': sourceValue(_interactive),
        '_narrow': sourceValue(_narrow),
        '_scale': sourceValue(_scale),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ProgressIndicatorExample extends StatefulWidget {
  const ProgressIndicatorExample();

  @override
  State<ProgressIndicatorExample> createState() =>
      _ProgressIndicatorExampleState();
}

class _ProgressIndicatorExampleState extends State<ProgressIndicatorExample> {
  int _currentIndex = @@_currentIndex@@;
  bool _vertical = @@_vertical@@;
  bool _interactive = @@_interactive@@;
  bool _narrow = @@_narrow@@;
  double _scale = @@_scale@@;

  @override
  Widget build(BuildContext context) {
    return MediaQuery(
      data: MediaQuery.of(context)
          .copyWith(textScaler: TextScaler.linear(_scale)),
      child: SizedBox(
        width: _narrow ? 160 : 640,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            CarbonProgressIndicator(
              currentIndex: _currentIndex,
              vertical: _vertical,
              interactive: _interactive,
              onStepSelected: (int index) =>
                  setState(() => _currentIndex = index),
              steps: const <CarbonProgressStep>[
                CarbonProgressStep(label: 'Account'),
                CarbonProgressStep(
                  label: 'Profile',
                  secondaryLabel: 'Optional',
                ),
                CarbonProgressStep(
                  label: 'Confirm with a deliberately long name',
                ),
                CarbonProgressStep(label: 'Problem', invalid: true),
                CarbonProgressStep(label: 'Locked', disabled: true),
              ],
            ),
            Text(
              'Current step: ${_currentIndex + 1}',
              style: CarbonTypeStyles.body01.copyWith(
                color: CarbonTheme.of(context).textPrimary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
''');
  }
}

extension _StructuredListPageSource on _StructuredListPage {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class StructuredListExample extends StatelessWidget {
  const StructuredListExample();
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    Widget cell(String s) => Text(
      s,
      style: CarbonTypeStyles.bodyCompact01.copyWith(color: t.textPrimary),
    );
    return SizedBox(
      width: 520,
      child: CarbonStructuredList(
        headers: const <String>['Name', 'Type', 'Status'],
        rows: <CarbonStructuredListRow>[
          CarbonStructuredListRow(
            cells: <Widget>[
              cell('api-gateway'),
              cell('Service'),
              cell('Running'),
            ],
          ),
          CarbonStructuredListRow(
            cells: <Widget>[cell('worker-01'), cell('Job'), cell('Idle')],
          ),
        ],
      ),
    );
  }
}
''');
  }
}

extension _AILabelPageStateSource on _AILabelPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_size': 'CarbonAILabelSize.${_size.name}',
        '_inline': sourceValue(_inline),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class AILabelExample extends StatefulWidget {
  const AILabelExample();
  @override
  State<AILabelExample> createState() => _AILabelExampleState();
}

class _AILabelExampleState extends State<AILabelExample> {
  CarbonAILabelSize _size = @@_size@@;
  bool _inline = @@_inline@@;

  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return CarbonAILabel(
      size: _size,
      inline: _inline,
      textLabel: _inline ? 'Generated' : null,
      content: Text(
        'This content was generated by AI.',
        style: CarbonTypeStyles.body01.copyWith(color: t.textPrimary),
      ),
    );
  }
}
''');
  }
}

extension _ChatButtonPageStateSource on _ChatButtonPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{
        '_kind': 'CarbonButtonKind.${_kind.name}',
        '_size': 'CarbonChatButtonSize.${_size.name}',
        '_quickAction': sourceValue(_quickAction),
        '_selected': sourceValue(_selected),
        '_icon': sourceValue(_icon),
        '_disabled': sourceValue(_disabled),
      },
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ChatButtonExample extends StatefulWidget {
  const ChatButtonExample();
  @override
  State<ChatButtonExample> createState() => _ChatButtonExampleState();
}

class _ChatButtonExampleState extends State<ChatButtonExample> {
  CarbonButtonKind _kind = @@_kind@@;
  CarbonChatButtonSize _size = @@_size@@;
  bool _quickAction = @@_quickAction@@;
  bool _selected = @@_selected@@;
  bool _icon = @@_icon@@;
  bool _disabled = @@_disabled@@;

  @override
  Widget build(BuildContext context) {
    return CarbonChatButton(
      label: _quickAction ? 'Summarize the chat' : 'Ask a question',
      kind: _kind,
      size: _size,
      quickAction: _quickAction,
      isSelected: _quickAction && _selected,
      icon: _icon ? CarbonIcons.send : null,
      onPressed: _disabled ? null : () {},
    );
  }
}
''');
  }
}

extension _ContainedListPageStateSource on _ContainedListPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_size': 'CarbonContainedListSize.${_size.name}'},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ContainedListExample extends StatefulWidget {
  const ContainedListExample();
  @override
  State<ContainedListExample> createState() => _ContainedListExampleState();
}

class _ContainedListExampleState extends State<ContainedListExample> {
  CarbonContainedListSize _size = @@_size@@;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: CarbonContainedList(
        label: const Text('Recent files'),
        size: _size,
        children: <Widget>[
          const CarbonContainedListItem(
            icon: CarbonIcons.document,
            child: Text('report.pdf'),
          ),
          CarbonContainedListItem(
            icon: CarbonIcons.document,
            onPressed: () {},
            child: const Text('notes.txt'),
          ),
          const CarbonContainedListItem(
            icon: CarbonIcons.document,
            child: Text('archive.zip'),
          ),
        ],
      ),
    );
  }
}
''');
  }
}

extension _ContextMenuPageStateSource on _ContextMenuPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_focusVisible': sourceValue(_focusVisible)},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class ContextMenuExample extends StatefulWidget {
  const ContextMenuExample();

  @override
  State<ContextMenuExample> createState() => _ContextMenuExampleState();
}

class _ContextMenuExampleState extends State<ContextMenuExample> {
  bool _focusVisible = @@_focusVisible@@;
  @override
  Widget build(BuildContext context) {
    final CarbonThemeData t = CarbonTheme.of(context);
    return CarbonContextMenu(
      items: <Widget>[
        CarbonMenuItem(label: 'Cut', icon: CarbonIcons.cut, onPressed: () {}),
        CarbonMenuItem(label: 'Copy', icon: CarbonIcons.copy, onPressed: () {}),
        CarbonMenuItem(
          label: 'Paste',
          icon: CarbonIcons.paste,
          onPressed: () {},
        ),
      ],
      child: FocusableActionDetector(
        onShowFocusHighlight: (bool visible) =>
            setState(() => _focusVisible = visible),
        child: Semantics(
          hint: 'Press Shift+F10 or the Context Menu key for actions',
          child: CarbonFocusRing(
            visible: _focusVisible,
            inset: true,
            child: Container(
              width: 280,
              height: 120,
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: t.layer01,
                border: Border.all(color: t.borderSubtle00),
              ),
              child: Text(
                'Context menu target',
                style: CarbonTypeStyles.body01.copyWith(color: t.textSecondary),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
''');
  }
}

extension _PaginationNavPageStateSource on _PaginationNavPageState {
  String get exampleSource {
    final ExampleConfiguration configuration = ExampleConfiguration(
      <String, String>{'_page': sourceValue(_page)},
    );
    return configuration.fill(r'''import 'package:carbide/carbide.dart';
import 'package:flutter/widgets.dart';

class PaginationNavExample extends StatefulWidget {
  const PaginationNavExample();
  @override
  State<PaginationNavExample> createState() => _PaginationNavExampleState();
}

class _PaginationNavExampleState extends State<PaginationNavExample> {
  int _page = @@_page@@;

  @override
  Widget build(BuildContext context) {
    return CarbonPaginationNav(
      totalItems: 12,
      page: _page,
      itemsShown: 7,
      onChange: (int p) => setState(() => _page = p),
    );
  }
}
''');
  }
}
