// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_colors.py — do not edit by hand.
//
// Color values are ported verbatim from the Apache-2.0 licensed Carbon Design
// System (@carbon/colors). See the NOTICE file for attribution.

import 'dart:ui' show Color;

/// The complete Carbon color palette as immutable [Color] constants.
///
/// Names mirror Carbon's swatches: a family and a step from 10
/// (lightest) to 100 (darkest), plus `*Hover` interaction variants —
/// for example [blue60] and [blue60Hover]. These are the raw palette;
/// semantic theme tokens (background, text, …) map onto them per theme.
abstract final class CarbonColors {
  // black
  /// Carbon `black` swatch (#000000).
  static const Color black = Color(0xFF000000);

  /// Carbon `black100` swatch (#000000).
  static const Color black100 = Color(0xFF000000);

  /// Hover-state variant of [black] (#212121).
  static const Color blackHover = Color(0xFF212121);

  // white
  /// Carbon `white` swatch (#FFFFFF).
  static const Color white = Color(0xFFFFFFFF);

  /// Carbon `white0` swatch (#FFFFFF).
  static const Color white0 = Color(0xFFFFFFFF);

  /// Hover-state variant of [white] (#E8E8E8).
  static const Color whiteHover = Color(0xFFE8E8E8);

  // yellow
  /// Carbon `yellow10` swatch (#FCF4D6).
  static const Color yellow10 = Color(0xFFFCF4D6);

  /// Carbon `yellow20` swatch (#FDDC69).
  static const Color yellow20 = Color(0xFFFDDC69);

  /// Carbon `yellow30` swatch (#F1C21B).
  static const Color yellow30 = Color(0xFFF1C21B);

  /// Carbon `yellow40` swatch (#D2A106).
  static const Color yellow40 = Color(0xFFD2A106);

  /// Carbon `yellow50` swatch (#B28600).
  static const Color yellow50 = Color(0xFFB28600);

  /// Carbon `yellow60` swatch (#8E6A00).
  static const Color yellow60 = Color(0xFF8E6A00);

  /// Carbon `yellow70` swatch (#684E00).
  static const Color yellow70 = Color(0xFF684E00);

  /// Carbon `yellow80` swatch (#483700).
  static const Color yellow80 = Color(0xFF483700);

  /// Carbon `yellow90` swatch (#302400).
  static const Color yellow90 = Color(0xFF302400);

  /// Carbon `yellow100` swatch (#1C1500).
  static const Color yellow100 = Color(0xFF1C1500);

  /// Hover-state variant of [yellow10] (#F8E6A0).
  static const Color yellow10Hover = Color(0xFFF8E6A0);

  /// Hover-state variant of [yellow20] (#FCCD27).
  static const Color yellow20Hover = Color(0xFFFCCD27);

  /// Hover-state variant of [yellow30] (#DDB00E).
  static const Color yellow30Hover = Color(0xFFDDB00E);

  /// Hover-state variant of [yellow40] (#BC9005).
  static const Color yellow40Hover = Color(0xFFBC9005);

  /// Hover-state variant of [yellow50] (#9E7700).
  static const Color yellow50Hover = Color(0xFF9E7700);

  /// Hover-state variant of [yellow60] (#755800).
  static const Color yellow60Hover = Color(0xFF755800);

  /// Hover-state variant of [yellow70] (#806000).
  static const Color yellow70Hover = Color(0xFF806000);

  /// Hover-state variant of [yellow80] (#5C4600).
  static const Color yellow80Hover = Color(0xFF5C4600);

  /// Hover-state variant of [yellow90] (#3D2E00).
  static const Color yellow90Hover = Color(0xFF3D2E00);

  /// Hover-state variant of [yellow100] (#332600).
  static const Color yellow100Hover = Color(0xFF332600);

  // orange
  /// Carbon `orange10` swatch (#FFF2E8).
  static const Color orange10 = Color(0xFFFFF2E8);

  /// Carbon `orange20` swatch (#FFD9BE).
  static const Color orange20 = Color(0xFFFFD9BE);

  /// Carbon `orange30` swatch (#FFB784).
  static const Color orange30 = Color(0xFFFFB784);

  /// Carbon `orange40` swatch (#FF832B).
  static const Color orange40 = Color(0xFFFF832B);

  /// Carbon `orange50` swatch (#EB6200).
  static const Color orange50 = Color(0xFFEB6200);

  /// Carbon `orange60` swatch (#BA4E00).
  static const Color orange60 = Color(0xFFBA4E00);

  /// Carbon `orange70` swatch (#8A3800).
  static const Color orange70 = Color(0xFF8A3800);

  /// Carbon `orange80` swatch (#5E2900).
  static const Color orange80 = Color(0xFF5E2900);

  /// Carbon `orange90` swatch (#3E1A00).
  static const Color orange90 = Color(0xFF3E1A00);

  /// Carbon `orange100` swatch (#231000).
  static const Color orange100 = Color(0xFF231000);

  /// Hover-state variant of [orange10] (#FFE2CC).
  static const Color orange10Hover = Color(0xFFFFE2CC);

  /// Hover-state variant of [orange20] (#FFC69E).
  static const Color orange20Hover = Color(0xFFFFC69E);

  /// Hover-state variant of [orange30] (#FF9D57).
  static const Color orange30Hover = Color(0xFFFF9D57);

  /// Hover-state variant of [orange40] (#FA6800).
  static const Color orange40Hover = Color(0xFFFA6800);

  /// Hover-state variant of [orange50] (#CC5500).
  static const Color orange50Hover = Color(0xFFCC5500);

  /// Hover-state variant of [orange60] (#9E4200).
  static const Color orange60Hover = Color(0xFF9E4200);

  /// Hover-state variant of [orange70] (#A84400).
  static const Color orange70Hover = Color(0xFFA84400);

  /// Hover-state variant of [orange80] (#753300).
  static const Color orange80Hover = Color(0xFF753300);

  /// Hover-state variant of [orange90] (#522200).
  static const Color orange90Hover = Color(0xFF522200);

  /// Hover-state variant of [orange100] (#421E00).
  static const Color orange100Hover = Color(0xFF421E00);

  // red
  /// Carbon `red10` swatch (#FFF1F1).
  static const Color red10 = Color(0xFFFFF1F1);

  /// Carbon `red20` swatch (#FFD7D9).
  static const Color red20 = Color(0xFFFFD7D9);

  /// Carbon `red30` swatch (#FFB3B8).
  static const Color red30 = Color(0xFFFFB3B8);

  /// Carbon `red40` swatch (#FF8389).
  static const Color red40 = Color(0xFFFF8389);

  /// Carbon `red50` swatch (#FA4D56).
  static const Color red50 = Color(0xFFFA4D56);

  /// Carbon `red60` swatch (#DA1E28).
  static const Color red60 = Color(0xFFDA1E28);

  /// Carbon `red70` swatch (#A2191F).
  static const Color red70 = Color(0xFFA2191F);

  /// Carbon `red80` swatch (#750E13).
  static const Color red80 = Color(0xFF750E13);

  /// Carbon `red90` swatch (#520408).
  static const Color red90 = Color(0xFF520408);

  /// Carbon `red100` swatch (#2D0709).
  static const Color red100 = Color(0xFF2D0709);

  /// Hover-state variant of [red100] (#540D11).
  static const Color red100Hover = Color(0xFF540D11);

  /// Hover-state variant of [red90] (#66050A).
  static const Color red90Hover = Color(0xFF66050A);

  /// Hover-state variant of [red80] (#921118).
  static const Color red80Hover = Color(0xFF921118);

  /// Hover-state variant of [red70] (#C21E25).
  static const Color red70Hover = Color(0xFFC21E25);

  /// Hover-state variant of [red60] (#B81922).
  static const Color red60Hover = Color(0xFFB81922);

  /// Hover-state variant of [red50] (#EE0713).
  static const Color red50Hover = Color(0xFFEE0713);

  /// Hover-state variant of [red40] (#FF6168).
  static const Color red40Hover = Color(0xFFFF6168);

  /// Hover-state variant of [red30] (#FF99A0).
  static const Color red30Hover = Color(0xFFFF99A0);

  /// Hover-state variant of [red20] (#FFC2C5).
  static const Color red20Hover = Color(0xFFFFC2C5);

  /// Hover-state variant of [red10] (#FFE0E0).
  static const Color red10Hover = Color(0xFFFFE0E0);

  // magenta
  /// Carbon `magenta10` swatch (#FFF0F7).
  static const Color magenta10 = Color(0xFFFFF0F7);

  /// Carbon `magenta20` swatch (#FFD6E8).
  static const Color magenta20 = Color(0xFFFFD6E8);

  /// Carbon `magenta30` swatch (#FFAFD2).
  static const Color magenta30 = Color(0xFFFFAFD2);

  /// Carbon `magenta40` swatch (#FF7EB6).
  static const Color magenta40 = Color(0xFFFF7EB6);

  /// Carbon `magenta50` swatch (#EE5396).
  static const Color magenta50 = Color(0xFFEE5396);

  /// Carbon `magenta60` swatch (#D02670).
  static const Color magenta60 = Color(0xFFD02670);

  /// Carbon `magenta70` swatch (#9F1853).
  static const Color magenta70 = Color(0xFF9F1853);

  /// Carbon `magenta80` swatch (#740937).
  static const Color magenta80 = Color(0xFF740937);

  /// Carbon `magenta90` swatch (#510224).
  static const Color magenta90 = Color(0xFF510224);

  /// Carbon `magenta100` swatch (#2A0A18).
  static const Color magenta100 = Color(0xFF2A0A18);

  /// Hover-state variant of [magenta100] (#53142F).
  static const Color magenta100Hover = Color(0xFF53142F);

  /// Hover-state variant of [magenta90] (#68032E).
  static const Color magenta90Hover = Color(0xFF68032E);

  /// Hover-state variant of [magenta80] (#8E0B43).
  static const Color magenta80Hover = Color(0xFF8E0B43);

  /// Hover-state variant of [magenta70] (#BF1D63).
  static const Color magenta70Hover = Color(0xFFBF1D63);

  /// Hover-state variant of [magenta60] (#B0215F).
  static const Color magenta60Hover = Color(0xFFB0215F);

  /// Hover-state variant of [magenta50] (#E3176F).
  static const Color magenta50Hover = Color(0xFFE3176F);

  /// Hover-state variant of [magenta40] (#FF57A0).
  static const Color magenta40Hover = Color(0xFFFF57A0);

  /// Hover-state variant of [magenta30] (#FF94C3).
  static const Color magenta30Hover = Color(0xFFFF94C3);

  /// Hover-state variant of [magenta20] (#FFBDDA).
  static const Color magenta20Hover = Color(0xFFFFBDDA);

  /// Hover-state variant of [magenta10] (#FFE0EF).
  static const Color magenta10Hover = Color(0xFFFFE0EF);

  // purple
  /// Carbon `purple10` swatch (#F6F2FF).
  static const Color purple10 = Color(0xFFF6F2FF);

  /// Carbon `purple20` swatch (#E8DAFF).
  static const Color purple20 = Color(0xFFE8DAFF);

  /// Carbon `purple30` swatch (#D4BBFF).
  static const Color purple30 = Color(0xFFD4BBFF);

  /// Carbon `purple40` swatch (#BE95FF).
  static const Color purple40 = Color(0xFFBE95FF);

  /// Carbon `purple50` swatch (#A56EFF).
  static const Color purple50 = Color(0xFFA56EFF);

  /// Carbon `purple60` swatch (#8A3FFC).
  static const Color purple60 = Color(0xFF8A3FFC);

  /// Carbon `purple70` swatch (#6929C4).
  static const Color purple70 = Color(0xFF6929C4);

  /// Carbon `purple80` swatch (#491D8B).
  static const Color purple80 = Color(0xFF491D8B);

  /// Carbon `purple90` swatch (#31135E).
  static const Color purple90 = Color(0xFF31135E);

  /// Carbon `purple100` swatch (#1C0F30).
  static const Color purple100 = Color(0xFF1C0F30);

  /// Hover-state variant of [purple100] (#341C59).
  static const Color purple100Hover = Color(0xFF341C59);

  /// Hover-state variant of [purple90] (#40197B).
  static const Color purple90Hover = Color(0xFF40197B);

  /// Hover-state variant of [purple80] (#5B24AD).
  static const Color purple80Hover = Color(0xFF5B24AD);

  /// Hover-state variant of [purple70] (#7C3DD6).
  static const Color purple70Hover = Color(0xFF7C3DD6);

  /// Hover-state variant of [purple60] (#7822FB).
  static const Color purple60Hover = Color(0xFF7822FB);

  /// Hover-state variant of [purple50] (#9352FF).
  static const Color purple50Hover = Color(0xFF9352FF);

  /// Hover-state variant of [purple40] (#AE7AFF).
  static const Color purple40Hover = Color(0xFFAE7AFF);

  /// Hover-state variant of [purple30] (#C5A3FF).
  static const Color purple30Hover = Color(0xFFC5A3FF);

  /// Hover-state variant of [purple20] (#DCC7FF).
  static const Color purple20Hover = Color(0xFFDCC7FF);

  /// Hover-state variant of [purple10] (#EDE5FF).
  static const Color purple10Hover = Color(0xFFEDE5FF);

  // blue
  /// Carbon `blue10` swatch (#EDF5FF).
  static const Color blue10 = Color(0xFFEDF5FF);

  /// Carbon `blue20` swatch (#D0E2FF).
  static const Color blue20 = Color(0xFFD0E2FF);

  /// Carbon `blue30` swatch (#A6C8FF).
  static const Color blue30 = Color(0xFFA6C8FF);

  /// Carbon `blue40` swatch (#78A9FF).
  static const Color blue40 = Color(0xFF78A9FF);

  /// Carbon `blue50` swatch (#4589FF).
  static const Color blue50 = Color(0xFF4589FF);

  /// Carbon `blue60` swatch (#0F62FE).
  static const Color blue60 = Color(0xFF0F62FE);

  /// Carbon `blue70` swatch (#0043CE).
  static const Color blue70 = Color(0xFF0043CE);

  /// Carbon `blue80` swatch (#002D9C).
  static const Color blue80 = Color(0xFF002D9C);

  /// Carbon `blue90` swatch (#001D6C).
  static const Color blue90 = Color(0xFF001D6C);

  /// Carbon `blue100` swatch (#001141).
  static const Color blue100 = Color(0xFF001141);

  /// Hover-state variant of [blue100] (#001F75).
  static const Color blue100Hover = Color(0xFF001F75);

  /// Hover-state variant of [blue90] (#00258A).
  static const Color blue90Hover = Color(0xFF00258A);

  /// Hover-state variant of [blue80] (#0039C7).
  static const Color blue80Hover = Color(0xFF0039C7);

  /// Hover-state variant of [blue70] (#0053FF).
  static const Color blue70Hover = Color(0xFF0053FF);

  /// Hover-state variant of [blue60] (#0050E6).
  static const Color blue60Hover = Color(0xFF0050E6);

  /// Hover-state variant of [blue50] (#1F70FF).
  static const Color blue50Hover = Color(0xFF1F70FF);

  /// Hover-state variant of [blue40] (#5C97FF).
  static const Color blue40Hover = Color(0xFF5C97FF);

  /// Hover-state variant of [blue30] (#8AB6FF).
  static const Color blue30Hover = Color(0xFF8AB6FF);

  /// Hover-state variant of [blue20] (#B8D3FF).
  static const Color blue20Hover = Color(0xFFB8D3FF);

  /// Hover-state variant of [blue10] (#DBEBFF).
  static const Color blue10Hover = Color(0xFFDBEBFF);

  // cyan
  /// Carbon `cyan10` swatch (#E5F6FF).
  static const Color cyan10 = Color(0xFFE5F6FF);

  /// Carbon `cyan20` swatch (#BAE6FF).
  static const Color cyan20 = Color(0xFFBAE6FF);

  /// Carbon `cyan30` swatch (#82CFFF).
  static const Color cyan30 = Color(0xFF82CFFF);

  /// Carbon `cyan40` swatch (#33B1FF).
  static const Color cyan40 = Color(0xFF33B1FF);

  /// Carbon `cyan50` swatch (#1192E8).
  static const Color cyan50 = Color(0xFF1192E8);

  /// Carbon `cyan60` swatch (#0072C3).
  static const Color cyan60 = Color(0xFF0072C3);

  /// Carbon `cyan70` swatch (#00539A).
  static const Color cyan70 = Color(0xFF00539A);

  /// Carbon `cyan80` swatch (#003A6D).
  static const Color cyan80 = Color(0xFF003A6D);

  /// Carbon `cyan90` swatch (#012749).
  static const Color cyan90 = Color(0xFF012749);

  /// Carbon `cyan100` swatch (#061727).
  static const Color cyan100 = Color(0xFF061727);

  /// Hover-state variant of [cyan10] (#CCEEFF).
  static const Color cyan10Hover = Color(0xFFCCEEFF);

  /// Hover-state variant of [cyan20] (#99DAFF).
  static const Color cyan20Hover = Color(0xFF99DAFF);

  /// Hover-state variant of [cyan30] (#57BEFF).
  static const Color cyan30Hover = Color(0xFF57BEFF);

  /// Hover-state variant of [cyan40] (#059FFF).
  static const Color cyan40Hover = Color(0xFF059FFF);

  /// Hover-state variant of [cyan50] (#0F7EC8).
  static const Color cyan50Hover = Color(0xFF0F7EC8);

  /// Hover-state variant of [cyan60] (#005FA3).
  static const Color cyan60Hover = Color(0xFF005FA3);

  /// Hover-state variant of [cyan70] (#0066BD).
  static const Color cyan70Hover = Color(0xFF0066BD);

  /// Hover-state variant of [cyan80] (#00498A).
  static const Color cyan80Hover = Color(0xFF00498A);

  /// Hover-state variant of [cyan90] (#013360).
  static const Color cyan90Hover = Color(0xFF013360);

  /// Hover-state variant of [cyan100] (#0B2947).
  static const Color cyan100Hover = Color(0xFF0B2947);

  // teal
  /// Carbon `teal10` swatch (#D9FBFB).
  static const Color teal10 = Color(0xFFD9FBFB);

  /// Carbon `teal20` swatch (#9EF0F0).
  static const Color teal20 = Color(0xFF9EF0F0);

  /// Carbon `teal30` swatch (#3DDBD9).
  static const Color teal30 = Color(0xFF3DDBD9);

  /// Carbon `teal40` swatch (#08BDBA).
  static const Color teal40 = Color(0xFF08BDBA);

  /// Carbon `teal50` swatch (#009D9A).
  static const Color teal50 = Color(0xFF009D9A);

  /// Carbon `teal60` swatch (#007D79).
  static const Color teal60 = Color(0xFF007D79);

  /// Carbon `teal70` swatch (#005D5D).
  static const Color teal70 = Color(0xFF005D5D);

  /// Carbon `teal80` swatch (#004144).
  static const Color teal80 = Color(0xFF004144);

  /// Carbon `teal90` swatch (#022B30).
  static const Color teal90 = Color(0xFF022B30);

  /// Carbon `teal100` swatch (#081A1C).
  static const Color teal100 = Color(0xFF081A1C);

  /// Hover-state variant of [teal10] (#ACF6F6).
  static const Color teal10Hover = Color(0xFFACF6F6);

  /// Hover-state variant of [teal20] (#57E5E5).
  static const Color teal20Hover = Color(0xFF57E5E5);

  /// Hover-state variant of [teal30] (#25CAC8).
  static const Color teal30Hover = Color(0xFF25CAC8);

  /// Hover-state variant of [teal40] (#07ABA9).
  static const Color teal40Hover = Color(0xFF07ABA9);

  /// Hover-state variant of [teal50] (#008A87).
  static const Color teal50Hover = Color(0xFF008A87);

  /// Hover-state variant of [teal60] (#006B68).
  static const Color teal60Hover = Color(0xFF006B68);

  /// Hover-state variant of [teal70] (#007070).
  static const Color teal70Hover = Color(0xFF007070);

  /// Hover-state variant of [teal80] (#005357).
  static const Color teal80Hover = Color(0xFF005357);

  /// Hover-state variant of [teal90] (#033940).
  static const Color teal90Hover = Color(0xFF033940);

  /// Hover-state variant of [teal100] (#0F3034).
  static const Color teal100Hover = Color(0xFF0F3034);

  // green
  /// Carbon `green10` swatch (#DEFBE6).
  static const Color green10 = Color(0xFFDEFBE6);

  /// Carbon `green20` swatch (#A7F0BA).
  static const Color green20 = Color(0xFFA7F0BA);

  /// Carbon `green30` swatch (#6FDC8C).
  static const Color green30 = Color(0xFF6FDC8C);

  /// Carbon `green40` swatch (#42BE65).
  static const Color green40 = Color(0xFF42BE65);

  /// Carbon `green50` swatch (#24A148).
  static const Color green50 = Color(0xFF24A148);

  /// Carbon `green60` swatch (#198038).
  static const Color green60 = Color(0xFF198038);

  /// Carbon `green70` swatch (#0E6027).
  static const Color green70 = Color(0xFF0E6027);

  /// Carbon `green80` swatch (#044317).
  static const Color green80 = Color(0xFF044317);

  /// Carbon `green90` swatch (#022D0D).
  static const Color green90 = Color(0xFF022D0D);

  /// Carbon `green100` swatch (#071908).
  static const Color green100 = Color(0xFF071908);

  /// Hover-state variant of [green10] (#B6F6C8).
  static const Color green10Hover = Color(0xFFB6F6C8);

  /// Hover-state variant of [green20] (#74E792).
  static const Color green20Hover = Color(0xFF74E792);

  /// Hover-state variant of [green30] (#36CE5E).
  static const Color green30Hover = Color(0xFF36CE5E);

  /// Hover-state variant of [green40] (#3BAB5A).
  static const Color green40Hover = Color(0xFF3BAB5A);

  /// Hover-state variant of [green50] (#208E3F).
  static const Color green50Hover = Color(0xFF208E3F);

  /// Hover-state variant of [green60] (#166F31).
  static const Color green60Hover = Color(0xFF166F31);

  /// Hover-state variant of [green70] (#11742F).
  static const Color green70Hover = Color(0xFF11742F);

  /// Hover-state variant of [green80] (#05521C).
  static const Color green80Hover = Color(0xFF05521C);

  /// Hover-state variant of [green90] (#033B11).
  static const Color green90Hover = Color(0xFF033B11);

  /// Hover-state variant of [green100] (#0D300F).
  static const Color green100Hover = Color(0xFF0D300F);

  // coolGray
  /// Carbon `coolGray10` swatch (#F2F4F8).
  static const Color coolGray10 = Color(0xFFF2F4F8);

  /// Carbon `coolGray20` swatch (#DDE1E6).
  static const Color coolGray20 = Color(0xFFDDE1E6);

  /// Carbon `coolGray30` swatch (#C1C7CD).
  static const Color coolGray30 = Color(0xFFC1C7CD);

  /// Carbon `coolGray40` swatch (#A2A9B0).
  static const Color coolGray40 = Color(0xFFA2A9B0);

  /// Carbon `coolGray50` swatch (#878D96).
  static const Color coolGray50 = Color(0xFF878D96);

  /// Carbon `coolGray60` swatch (#697077).
  static const Color coolGray60 = Color(0xFF697077);

  /// Carbon `coolGray70` swatch (#4D5358).
  static const Color coolGray70 = Color(0xFF4D5358);

  /// Carbon `coolGray80` swatch (#343A3F).
  static const Color coolGray80 = Color(0xFF343A3F);

  /// Carbon `coolGray90` swatch (#21272A).
  static const Color coolGray90 = Color(0xFF21272A);

  /// Carbon `coolGray100` swatch (#121619).
  static const Color coolGray100 = Color(0xFF121619);

  /// Hover-state variant of [coolGray10] (#E4E9F1).
  static const Color coolGray10Hover = Color(0xFFE4E9F1);

  /// Hover-state variant of [coolGray20] (#CDD3DA).
  static const Color coolGray20Hover = Color(0xFFCDD3DA);

  /// Hover-state variant of [coolGray30] (#ADB5BD).
  static const Color coolGray30Hover = Color(0xFFADB5BD);

  /// Hover-state variant of [coolGray40] (#9199A1).
  static const Color coolGray40Hover = Color(0xFF9199A1);

  /// Hover-state variant of [coolGray50] (#757B85).
  static const Color coolGray50Hover = Color(0xFF757B85);

  /// Hover-state variant of [coolGray60] (#585E64).
  static const Color coolGray60Hover = Color(0xFF585E64);

  /// Hover-state variant of [coolGray70] (#5D646A).
  static const Color coolGray70Hover = Color(0xFF5D646A);

  /// Hover-state variant of [coolGray80] (#434A51).
  static const Color coolGray80Hover = Color(0xFF434A51);

  /// Hover-state variant of [coolGray90] (#2B3236).
  static const Color coolGray90Hover = Color(0xFF2B3236);

  /// Hover-state variant of [coolGray100] (#222A2F).
  static const Color coolGray100Hover = Color(0xFF222A2F);

  // gray
  /// Carbon `gray10` swatch (#F4F4F4).
  static const Color gray10 = Color(0xFFF4F4F4);

  /// Carbon `gray20` swatch (#E0E0E0).
  static const Color gray20 = Color(0xFFE0E0E0);

  /// Carbon `gray30` swatch (#C6C6C6).
  static const Color gray30 = Color(0xFFC6C6C6);

  /// Carbon `gray40` swatch (#A8A8A8).
  static const Color gray40 = Color(0xFFA8A8A8);

  /// Carbon `gray50` swatch (#8D8D8D).
  static const Color gray50 = Color(0xFF8D8D8D);

  /// Carbon `gray60` swatch (#6F6F6F).
  static const Color gray60 = Color(0xFF6F6F6F);

  /// Carbon `gray70` swatch (#525252).
  static const Color gray70 = Color(0xFF525252);

  /// Carbon `gray80` swatch (#393939).
  static const Color gray80 = Color(0xFF393939);

  /// Carbon `gray90` swatch (#262626).
  static const Color gray90 = Color(0xFF262626);

  /// Carbon `gray100` swatch (#161616).
  static const Color gray100 = Color(0xFF161616);

  /// Hover-state variant of [gray10] (#E8E8E8).
  static const Color gray10Hover = Color(0xFFE8E8E8);

  /// Hover-state variant of [gray20] (#D1D1D1).
  static const Color gray20Hover = Color(0xFFD1D1D1);

  /// Hover-state variant of [gray30] (#B5B5B5).
  static const Color gray30Hover = Color(0xFFB5B5B5);

  /// Hover-state variant of [gray40] (#999999).
  static const Color gray40Hover = Color(0xFF999999);

  /// Hover-state variant of [gray50] (#7A7A7A).
  static const Color gray50Hover = Color(0xFF7A7A7A);

  /// Hover-state variant of [gray60] (#5E5E5E).
  static const Color gray60Hover = Color(0xFF5E5E5E);

  /// Hover-state variant of [gray70] (#636363).
  static const Color gray70Hover = Color(0xFF636363);

  /// Hover-state variant of [gray80] (#474747).
  static const Color gray80Hover = Color(0xFF474747);

  /// Hover-state variant of [gray90] (#333333).
  static const Color gray90Hover = Color(0xFF333333);

  /// Hover-state variant of [gray100] (#292929).
  static const Color gray100Hover = Color(0xFF292929);

  // warmGray
  /// Carbon `warmGray10` swatch (#F7F3F2).
  static const Color warmGray10 = Color(0xFFF7F3F2);

  /// Carbon `warmGray20` swatch (#E5E0DF).
  static const Color warmGray20 = Color(0xFFE5E0DF);

  /// Carbon `warmGray30` swatch (#CAC5C4).
  static const Color warmGray30 = Color(0xFFCAC5C4);

  /// Carbon `warmGray40` swatch (#ADA8A8).
  static const Color warmGray40 = Color(0xFFADA8A8);

  /// Carbon `warmGray50` swatch (#8F8B8B).
  static const Color warmGray50 = Color(0xFF8F8B8B);

  /// Carbon `warmGray60` swatch (#726E6E).
  static const Color warmGray60 = Color(0xFF726E6E);

  /// Carbon `warmGray70` swatch (#565151).
  static const Color warmGray70 = Color(0xFF565151);

  /// Carbon `warmGray80` swatch (#3C3838).
  static const Color warmGray80 = Color(0xFF3C3838);

  /// Carbon `warmGray90` swatch (#272525).
  static const Color warmGray90 = Color(0xFF272525);

  /// Carbon `warmGray100` swatch (#171414).
  static const Color warmGray100 = Color(0xFF171414);

  /// Hover-state variant of [warmGray10] (#F0E8E6).
  static const Color warmGray10Hover = Color(0xFFF0E8E6);

  /// Hover-state variant of [warmGray20] (#D8D0CF).
  static const Color warmGray20Hover = Color(0xFFD8D0CF);

  /// Hover-state variant of [warmGray30] (#B9B3B1).
  static const Color warmGray30Hover = Color(0xFFB9B3B1);

  /// Hover-state variant of [warmGray40] (#9C9696).
  static const Color warmGray40Hover = Color(0xFF9C9696);

  /// Hover-state variant of [warmGray50] (#7F7B7B).
  static const Color warmGray50Hover = Color(0xFF7F7B7B);

  /// Hover-state variant of [warmGray60] (#605D5D).
  static const Color warmGray60Hover = Color(0xFF605D5D);

  /// Hover-state variant of [warmGray70] (#696363).
  static const Color warmGray70Hover = Color(0xFF696363);

  /// Hover-state variant of [warmGray80] (#4C4848).
  static const Color warmGray80Hover = Color(0xFF4C4848);

  /// Hover-state variant of [warmGray90] (#343232).
  static const Color warmGray90Hover = Color(0xFF343232);

  /// Hover-state variant of [warmGray100] (#2C2626).
  static const Color warmGray100Hover = Color(0xFF2C2626);
}
