// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_fluid_type.py — do not edit by hand.
//
// Values are ported verbatim from the Apache-2.0 licensed Carbon Design System
// (@carbon/type). See the NOTICE file for attribution.

import 'package:flutter/painting.dart' show FontWeight, TextStyle;

import 'fluid_text_style.dart';
import 'fonts.dart';

/// The Carbon fluid (responsive) type styles.
///
/// Resolve one for a viewport width with [CarbonFluidTextStyle.resolve].
abstract final class CarbonFluidTypeStyles {
  /// The `expressiveHeading01` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading01 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 14,
      fontWeight: FontWeight.w600,
      height: 1.25,
      letterSpacing: 0.16,
    ),
  );

  /// The `expressiveHeading02` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading02 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      height: 1.5,
      letterSpacing: 0,
    ),
  );

  /// The `expressiveHeading03` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading03 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 20,
      fontWeight: FontWeight.w400,
      height: 1.4,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'xlg': TextStyle(fontSize: 20, height: 1.4),
      'max': TextStyle(fontSize: 24, height: 1.334),
    },
  );

  /// The `expressiveHeading04` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading04 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 28,
      fontWeight: FontWeight.w400,
      height: 1.28572,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'xlg': TextStyle(fontSize: 32, fontWeight: FontWeight.w400, height: 1.25),
      'max': TextStyle(fontSize: 32, fontWeight: FontWeight.w400),
    },
  );

  /// The `expressiveHeading05` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading05 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 32,
      fontWeight: FontWeight.w400,
      height: 1.25,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(
        fontSize: 36,
        fontWeight: FontWeight.w300,
        height: 1.22,
        letterSpacing: 0,
      ),
      'lg': TextStyle(fontSize: 42, height: 1.19, letterSpacing: 0),
      'xlg': TextStyle(fontSize: 48, height: 1.17, letterSpacing: 0),
      'max': TextStyle(fontSize: 60, letterSpacing: 0),
    },
  );

  /// The `expressiveHeading06` fluid type style.
  static const CarbonFluidTextStyle expressiveHeading06 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 32,
      fontWeight: FontWeight.w600,
      height: 1.25,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(
        fontSize: 36,
        fontWeight: FontWeight.w600,
        height: 1.22,
        letterSpacing: 0,
      ),
      'lg': TextStyle(
        fontSize: 42,
        fontWeight: FontWeight.w600,
        height: 1.19,
        letterSpacing: 0,
      ),
      'xlg': TextStyle(
        fontSize: 48,
        fontWeight: FontWeight.w600,
        height: 1.17,
        letterSpacing: 0,
      ),
      'max': TextStyle(
        fontSize: 60,
        fontWeight: FontWeight.w600,
        letterSpacing: 0,
      ),
    },
  );

  /// The `expressiveParagraph01` fluid type style.
  static const CarbonFluidTextStyle expressiveParagraph01 =
      CarbonFluidTextStyle(
        base: TextStyle(
          fontFamily: CarbonFontFamily.sans,
          fontSize: 24,
          fontWeight: FontWeight.w300,
          height: 1.334,
          letterSpacing: 0,
        ),
        overrides: <String, TextStyle>{
          'lg': TextStyle(fontSize: 28, height: 1.28572),
          'max': TextStyle(fontSize: 32, height: 1.25),
        },
      );

  /// The `quotation01` fluid type style.
  static const CarbonFluidTextStyle quotation01 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.serif,
      fontSize: 20,
      fontWeight: FontWeight.w400,
      height: 1.3,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
      ),
      'lg': TextStyle(
        fontSize: 24,
        fontWeight: FontWeight.w400,
        height: 1.334,
        letterSpacing: 0,
      ),
      'xlg': TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
      'max': TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    },
  );

  /// The `quotation02` fluid type style.
  static const CarbonFluidTextStyle quotation02 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.serif,
      fontSize: 32,
      fontWeight: FontWeight.w300,
      height: 1.25,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(fontSize: 36, height: 1.22),
      'lg': TextStyle(fontSize: 42, height: 1.19),
      'xlg': TextStyle(fontSize: 48, height: 1.17),
      'max': TextStyle(fontSize: 60),
    },
  );

  /// The `display01` fluid type style.
  static const CarbonFluidTextStyle display01 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 42,
      fontWeight: FontWeight.w300,
      height: 1.19,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(fontSize: 42),
      'lg': TextStyle(fontSize: 54),
      'xlg': TextStyle(fontSize: 60, height: 1.17),
      'max': TextStyle(fontSize: 76, height: 1.13),
    },
  );

  /// The `display02` fluid type style.
  static const CarbonFluidTextStyle display02 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 42,
      fontWeight: FontWeight.w600,
      height: 1.19,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(fontSize: 42),
      'lg': TextStyle(fontSize: 54),
      'xlg': TextStyle(fontSize: 60, height: 1.16),
      'max': TextStyle(fontSize: 76, height: 1.13),
    },
  );

  /// The `display03` fluid type style.
  static const CarbonFluidTextStyle display03 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 42,
      fontWeight: FontWeight.w300,
      height: 1.19,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(fontSize: 54, height: 1.18),
      'lg': TextStyle(fontSize: 60, height: 1.16, letterSpacing: -0.64),
      'xlg': TextStyle(fontSize: 76, height: 1.13),
      'max': TextStyle(fontSize: 84, height: 1.11, letterSpacing: -0.96),
    },
  );

  /// The `display04` fluid type style.
  static const CarbonFluidTextStyle display04 = CarbonFluidTextStyle(
    base: TextStyle(
      fontFamily: CarbonFontFamily.sans,
      fontSize: 42,
      fontWeight: FontWeight.w300,
      height: 1.19,
      letterSpacing: 0,
    ),
    overrides: <String, TextStyle>{
      'md': TextStyle(fontSize: 68, height: 1.15),
      'lg': TextStyle(fontSize: 92, height: 1.11, letterSpacing: -0.64),
      'xlg': TextStyle(fontSize: 122, height: 1.07, letterSpacing: -0.64),
      'max': TextStyle(fontSize: 156, height: 1.05, letterSpacing: -0.96),
    },
  );

  /// The `fluidHeading03` fluid type style (an alias of [expressiveHeading03]).
  static const CarbonFluidTextStyle fluidHeading03 = expressiveHeading03;

  /// The `fluidHeading04` fluid type style (an alias of [expressiveHeading04]).
  static const CarbonFluidTextStyle fluidHeading04 = expressiveHeading04;

  /// The `fluidHeading05` fluid type style (an alias of [expressiveHeading05]).
  static const CarbonFluidTextStyle fluidHeading05 = expressiveHeading05;

  /// The `fluidHeading06` fluid type style (an alias of [expressiveHeading06]).
  static const CarbonFluidTextStyle fluidHeading06 = expressiveHeading06;

  /// The `fluidParagraph01` fluid type style (an alias of [expressiveParagraph01]).
  static const CarbonFluidTextStyle fluidParagraph01 = expressiveParagraph01;

  /// The `fluidQuotation01` fluid type style (an alias of [quotation01]).
  static const CarbonFluidTextStyle fluidQuotation01 = quotation01;

  /// The `fluidQuotation02` fluid type style (an alias of [quotation02]).
  static const CarbonFluidTextStyle fluidQuotation02 = quotation02;

  /// The `fluidDisplay01` fluid type style (an alias of [display01]).
  static const CarbonFluidTextStyle fluidDisplay01 = display01;

  /// The `fluidDisplay02` fluid type style (an alias of [display02]).
  static const CarbonFluidTextStyle fluidDisplay02 = display02;

  /// The `fluidDisplay03` fluid type style (an alias of [display03]).
  static const CarbonFluidTextStyle fluidDisplay03 = display03;

  /// The `fluidDisplay04` fluid type style (an alias of [display04]).
  static const CarbonFluidTextStyle fluidDisplay04 = display04;
}
