// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_layout.py — do not edit by hand.
//
// Values come from @carbon/layout/src/dtcg/layout.json (Apache-2.0).
// See NOTICE for attribution.

/// @docImport 'layout.dart';
library;

/// Viewport-relative Carbon spacing tokens.
///
/// Resolve a token against the viewport width in logical pixels:
///
/// ```dart
/// final gap = CarbonFluidSpacing.spacing02.resolve(
///   MediaQuery.sizeOf(context).width,
/// );
/// ```
///
/// These tokens use the viewport, independent of a narrow enclosing column.
/// Fixed spacing remains available through [CarbonSpacing].
enum CarbonFluidSpacing {
  /// The `fluid-spacing-01` token (0% of viewport width).
  spacing01(0),

  /// The `fluid-spacing-02` token (2% of viewport width).
  spacing02(2),

  /// The `fluid-spacing-03` token (5% of viewport width).
  spacing03(5),

  /// The `fluid-spacing-04` token (10% of viewport width).
  spacing04(10);

  const CarbonFluidSpacing(this.viewportPercent);

  /// The percentage of viewport width this token represents.
  final double viewportPercent;

  /// Resolves the spacing in logical pixels for [viewportWidth].
  ///
  /// Throws an [ArgumentError] if the width is negative or not finite.
  double resolve(double viewportWidth) {
    if (!viewportWidth.isFinite || viewportWidth < 0) {
      throw ArgumentError.value(
        viewportWidth,
        'viewportWidth',
        'Must be finite and nonnegative',
      );
    }
    return viewportWidth * (viewportPercent / 100);
  }
}
