#!/usr/bin/env python3
"""Check the pinned Carbon component-module review and render its parity matrix."""
import argparse
import hashlib
import json
from pathlib import Path
import re
from public_surface import inventory, mask_source

ROOT = Path(__file__).resolve().parents[1]
POLICY = ROOT / 'tool/carbon_parity.json'
REPORT = ROOT / 'docs/carbon-parity.md'
STATES = {'Present', 'Consolidated', 'Partial', 'Deferred', 'Out of scope'}
TIERS = {'curated story', 'golden-locked', 'behavior-tested', 'not implemented', 'not applicable'}


def upstream_snapshot(carbon):
    entrypoint = carbon / 'packages/react/src/index.ts'
    source = entrypoint.read_text()
    masked = mask_source(source)
    modules = {}
    for match in re.finditer(r'\bexport\s+(?!type\b)', masked):
        directive = source[match.start():].split(';', 1)[0]
        uri = re.search(r"from\s+'\./components/([^']+)'", directive)
        if not uri:
            continue
        module = uri[1]
        base = entrypoint.parent / 'components' / module
        paths = [base.with_name(base.name + suffix) for suffix in ['.ts', '.tsx', '.js']]
        paths += [base / 'index.ts', base / 'index.tsx', base / 'index.js']
        target = next((p for p in paths if p.is_file()), None)
        if not target:
            raise ValueError(f'Cannot resolve upstream component module {module}')
        modules[module] = {
            'source': target.relative_to(carbon).as_posix(),
            'sha256': hashlib.sha256(target.read_bytes()).hexdigest(),
        }
    return {'entrypointSha256': hashlib.sha256(entrypoint.read_bytes()).hexdigest(),
            'modules': dict(sorted(modules.items()))}


def validate(data, exports, curated, reference):
    if data['carbonCommit'] != reference['carbonCommit'] or data['carbonTag'] != reference['carbonTag']:
        raise ValueError('Carbon parity review does not match the reference pin')
    if set(data['modules']) != set(data['components']):
        raise ValueError('Every upstream value-export component module needs a decision')
    for name, item in data['components'].items():
        if item['state'] not in STATES or item['tier'] not in TIERS:
            raise ValueError(f'{name}: invalid parity state or fidelity tier')
        if not item.get('note', '').strip():
            raise ValueError(f'{name}: missing review note')
        if any(api not in exports for api in item['apis']):
            raise ValueError(f'{name}: undocumented or nonexistent Carbide equivalent')
        if item['state'] in {'Present', 'Consolidated', 'Partial'} and not item['apis']:
            raise ValueError(f'{name}: implemented states need a real API')
        if item['state'] == 'Partial' and not item.get('issue'):
            raise ValueError(f'{name}: partial parity needs a tracking issue')
        if item['tier'] == 'curated story' and item.get('story') not in curated:
            raise ValueError(f'{name}: no curated story supports the claim')


def render(data):
    lines = ['# Carbon parity', '', '<!-- Generated by tool/carbon_parity.py. Review tool/carbon_parity.json. -->', '',
        f"Reviewed against Carbon `{data['carbonTag']}` (`{data['carbonCommit']}`).",
        f"All {len(data['modules'])} component modules reached by value exports in the React entrypoint are classified, "
        'including preview/unstable modules and explicit skeleton modules. Type-only prop exports are not components. '
        'Aliases share the decision for their source module; nested item/section wrappers are described as compositions.', '',
        '**Present** describes the released family contract, not every React prop or wrapper. '
        '**Consolidated** names the Flutter composition/option replacing separate React components. '
        '**Partial** identifies a remaining behavior and its implementation issue. '
        '**Deferred** is unimplemented release scope; **Out of scope** describes an intentional platform/architecture boundary.', '',
        'Fidelity tiers identify the strongest reviewed evidence for the named family: curated default-story comparison, '
        'Linux golden regression baseline, or behavior contract. A curated story does not establish all-variant or pixel-perfect parity. '
        'Golden-locked means comparison against the port baseline, not an independent upstream image. Deferred/platform-only rows '
        'have no implementation claim.', '',
        '| Upstream module | State | Carbide equivalent | Fidelity | Boundary / tracking |',
        '| --- | --- | --- | --- | --- |']
    for name, item in sorted(data['components'].items()):
        src = data['modules'][name]['source']
        link = f"https://github.com/carbon-design-system/carbon/blob/{data['carbonTag']}/{src}"
        apis = ', '.join(f'`{api}`' for api in item['apis']) or '—'
        note = item['note'] + (f" [#{item['issue']}](https://github.com/sunderee/carbide/issues/{item['issue']})." if item.get('issue') else '')
        lines.append(f"| [{name}]({link}) | {item['state']} | {apis} | {item['tier']} | {note} |")
    lines += ['', '## Boundaries beyond the React entrypoint', '',
        '- The newer compound PageHeader source exists in core but its v11 entrypoint export is deferred to v12. '
        'Carbide retains constructor composition and historical band geometry, with responsive action/tag disclosure, '
        'truncated-title help and a caller-owned hero slot. Sticky scroll/collapse orchestration is deferred.',
        '- CSS subgrid/FlexGrid internals are outside the Wrap-based grid architecture; CarbonGrid/CarbonColumn '
        'provide breakpoints, margins, gutters, spans and column hang in Flutter composition.',
        '- Next-major tile defaults and structured-list visible icons are deferred together under '
        '[ADR 0002](adr/0002-carbon-v12-feature-flag-posture.md). Current v11 controls remain implemented.',
        '- Carbon Charts is a separate package/scope decision tracked in [M19 / #357](https://github.com/sunderee/carbide/issues/357). '
        'The 0.5.0 pass makes no Charts implementation or fidelity claim.', '',
        'On a Carbon bump, re-review every changed component module, update the policy snapshot and equivalents, '
        'and run `python3 tool/carbon_parity.py --check-upstream` with the reference checked out. '
        'The Carbon reference workflow verifies the snapshot; normal CI checks the pinned review and rendered matrix offline.', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--check-upstream', action='store_true')
    args = parser.parse_args()
    data = json.loads(POLICY.read_text())
    reference = json.loads((ROOT / 'tool/carbon_reference.lock.json').read_text())
    stories = {s['component'] for s in json.loads((ROOT / 'tool/fidelity/stories.json').read_text())['stories']}
    validate(data, inventory(), stories, reference)
    if args.check_upstream:
        actual = upstream_snapshot(ROOT / 'documentation/carbon')
        if actual['modules'] != data['modules'] or actual['entrypointSha256'] != data['entrypointSha256']:
            raise ValueError('Upstream entrypoint/module changed without a reviewed parity decision')
    generated = render(data)
    if args.check or args.check_upstream:
        if not REPORT.is_file() or REPORT.read_text() != generated:
            raise SystemExit('Stale Carbon parity matrix: run python3 tool/carbon_parity.py')
    else:
        REPORT.write_text(generated)
    print(f"Carbon parity: {len(data['modules'])} modules reviewed at {data['carbonTag']}.")

if __name__ == '__main__': main()
