#!/usr/bin/env python3
"""Generate source-derived documentation facts and reject known stale claims."""
import argparse
import json
from pathlib import Path
import re
from public_surface import inventory, mask_source
from sdk_floor import read_floor

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'docs/reference-facts.md'


def artwork_count(source):
    names = re.findall(r'static\s+const\s+CarbonIconData\s+([\w$]+)\s*=', mask_source(source))
    if len(names) != len(set(names)):
        raise ValueError('Duplicate artwork declaration')
    return len(names)


def facts(root=ROOT):
    reference = json.loads((root / 'tool/carbon_reference.lock.json').read_text())
    pubspec = (root / 'pubspec.yaml').read_text()
    fonts = re.findall(r'asset:\s*(fonts/\S+\.ttf)\s*\n\s*weight:\s*(\d+)', pubspec)
    if {p for p, _ in fonts} != {p.relative_to(root).as_posix() for p in (root / 'fonts').glob('*.ttf')}:
        raise ValueError('Font files and pubspec declarations differ')
    return {
        'icons': artwork_count((root / 'lib/src/icons/carbon_icons.dart').read_text()),
        'pictograms': artwork_count((root / 'lib/src/pictograms/carbon_pictograms.dart').read_text()),
        'fonts': fonts,
        'floor': read_floor(pubspec),
        'reference': reference,
        'exports': len(inventory(root)),
    }


def render(data):
    ref = data['reference']
    # Keep the lockfile as the sole reference version authority.
    version = ref['carbonTag']
    commit = ref['carbonCommit']
    if not version or not commit:
        raise ValueError('Unknown Carbon reference lock schema')
    lines = ['# Reference facts', '', '<!-- Generated by tool/documentation_facts.py; do not hand edit. -->', '',
        '| Source-derived fact | Value |', '| --- | --- |',
        f"| Carbon review pin | `{version}` (`{commit}`) |",
        f"| Public icon constants | {data['icons']:,} |",
        f"| Public pictogram constants | {data['pictograms']:,} |",
        f"| Barrel declarations | {data['exports']} |",
        f"| Minimum Flutter / Dart | {data['floor']['flutter']} / {data['floor']['sdk']} |",
        f"| Bundled font files | {len(data['fonts'])} |", '',
        '| Font asset | Weight |', '| --- | --- |']
    lines += [f'| `{path}` | {weight} |' for path, weight in data['fonts']]
    lines += ['', 'Counts describe the current checkout. Historical benchmarks and spike measurements',
              'describe their recorded source/engine and are not regenerated as current performance claims.', '']
    return '\n'.join(lines)


def check_claims(text, data):
    if 'CarbideThemeData' in text or 'once it is available' in text:
        raise ValueError('Stale theme name or unavailable API-reference claim')
    for number, kind in re.findall(r'([\d,]+) Carbon (icons|pictograms)', text):
        if int(number.replace(',', '')) != data[kind]:
            raise ValueError(f'Stale {kind} count {number}')
    if re.search(r'\b(?:built|implemented)\b[^.]{0,110}\b(?:only|strictly)\b[^.]{0,70}package:flutter/widgets', text, re.I):
        raise ValueError('Widgets-only claim omits other Flutter SDK libraries')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = facts()
    generated = render(data)
    for path in [ROOT / 'README.md', *sorted((ROOT / 'docs').rglob('*.md'))]:
        check_claims(path.read_text(), data)
    for path in (ROOT / 'lib').rglob('*.dart'):
        source = path.read_text()
        masked = mask_source(source)
        for match in re.finditer(r'\bimport\s+', masked):
            directive = source[match.start():].split(';', 1)[0]
            if re.search(r"package:flutter/(?:material|cupertino)\.dart", directive):
                raise ValueError(f'Forbidden library import: {path}')
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != generated:
            raise SystemExit('Stale reference facts: run python3 tool/documentation_facts.py')
    else:
        TARGET.write_text(generated)
    print('Documentation facts: artwork, fonts, exports and SDK/reference versions match source.')


if __name__ == '__main__': main()
