#!/usr/bin/env python3
"""Check explicit public-API gallery coverage and generate its review table.

Lexical references prove discovery coverage, not execution or visual parity.
Flutter's route, widget and copied-source tests provide those separate checks.
"""
import argparse
import json
from pathlib import Path
import re
from generate_gallery_examples import declarations
from public_surface import inventory, mask_source

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'tool/gallery_coverage.json'
REPORT = ROOT / 'docs/testing/gallery-coverage.md'


def catalog(root=ROOT):
    pages = root / 'example/lib/src/pages'
    actual = {}
    for path in sorted(pages.glob('*_pages.dart')):
        source = path.read_text()
        classes = declarations(source)
        for match in re.finditer(r"GalleryEntry\(\s*slug:\s*'([^']+)'[\s\S]*?builder:\s*\(\)\s*=>\s*(?:const\s+)?(_\w+Page)\(\)", source):
            slug, widget = match.groups()
            if slug in actual:
                raise ValueError(f'duplicate route {slug}')
            if widget not in classes:
                raise ValueError(f'missing page builder {widget}')
            actual[slug] = mask_source(classes[widget] + classes.get(widget + 'State', ''))
    return actual


def validate(exports, policy, routes, shell):
    if set(exports) != set(policy):
        raise ValueError(f'unclassified/removed public APIs: {sorted(set(exports) ^ set(policy))}')
    for name, entry in policy.items():
        if entry.get('mode') not in {'demonstrated', 'composition', 'nonvisual'}:
            raise ValueError(f'{name}: unknown coverage mode')
        if not entry.get('routes') or any(route not in routes for route in entry['routes']):
            raise ValueError(f'{name}: unknown or missing gallery route')
        if entry['mode'] == 'demonstrated':
            source = '\n'.join(routes[route] for route in entry['routes'])
            if not re.search(rf'\b{re.escape(name)}\b', source):
                raise ValueError(f'{name}: no live reference on its documented routes')
        elif not entry.get('reason', '').strip():
            raise ValueError(f'{name}: composition/nonvisual coverage needs a reason')
        if entry.get('shell_reference') and not re.search(rf'\b{re.escape(name)}\b', shell):
            raise ValueError(f'{name}: claimed gallery-shell reference is absent')


def report(exports, policy, routes):
    direct = sum(v['mode'] == 'demonstrated' for v in policy.values())
    lines = ['# Gallery coverage', '', '<!-- Generated by tool/gallery_coverage.py. Edit its JSON policy, not this table. -->', '',
             f'{len(exports)} public declarations are classified across {len(routes)} catalog routes: '
             f'{direct} have a lexical reference in their documented live page; '
             f'{len(exports) - direct} have an explicit composition or nonvisual policy.', '',
             'This is discovery coverage. It does not claim that every state or variant has a dedicated demo, golden, '
             'or upstream comparison. The specimen registry, accessibility inventory, all-page tests, real-router browser '
             'sweep and compilation of copied examples are separate gates.', '',
             '| Public API | Gallery routes | Coverage |', '| --- | --- | --- |']
    for name, entry in sorted(policy.items()):
        links = ', '.join(f'[{slug}](https://sunderee.github.io/carbide/#/components/{slug})' for slug in entry['routes'])
        detail = entry['mode'] + (': ' + entry['reason'] if entry.get('reason') else '')
        lines.append(f'| `{name}` | {links} | {detail} |')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    exports = inventory()
    policy = json.loads(MANIFEST.read_text())['exports']
    routes = catalog()
    shell = mask_source((ROOT / 'example/lib/src/gallery_shell.dart').read_text())
    validate(exports, policy, routes, shell)
    generated = report(exports, policy, routes)
    if args.check:
        if not REPORT.is_file() or REPORT.read_text() != generated:
            raise SystemExit('Stale gallery coverage report: run python3 tool/gallery_coverage.py')
    else:
        REPORT.write_text(generated)
    print(f'Gallery coverage: {len(exports)} declarations, {len(routes)} routes; all gaps classified.')


if __name__ == '__main__':
    main()
