#!/usr/bin/env python3
"""Generate Carbide's fluid (responsive) type tokens from the Carbon source.

Reads @carbon/type styles.ts (Apache-2.0) and emits:
  - lib/src/foundations/fluid_typography.dart    (CarbonFluidTypeStyles)
  - test/foundations/fluid_typography_test.dart  (cascade value lock)

Fluid styles have a base plus per-breakpoint overrides that cascade (a property
set at one breakpoint persists at wider ones). The CarbonFluidTextStyle model
applies that cascade; this generator ports the data and locks resolve() at each
breakpoint width.

Run from the repository root:  python3 tool/generate_carbon_fluid_type.py
"""

from __future__ import annotations

import re
from pathlib import Path

from generate_carbon_type import normalize_styles, scale_steps, weights

ROOT = Path(__file__).resolve().parent.parent
TYPE_DIR = ROOT / "documentation/carbon/packages/type/src"
LIB_OUT = ROOT / "lib/src/foundations/fluid_typography.dart"
TEST_OUT = ROOT / "test/foundations/fluid_typography_test.dart"

OBJECTS = [
    "expressiveHeading01", "expressiveHeading02", "expressiveHeading03",
    "expressiveHeading04", "expressiveHeading05", "expressiveHeading06",
    "expressiveParagraph01", "quotation01", "quotation02",
    "display01", "display02", "display03", "display04",
]
ALIASES = {
    "fluidHeading03": "expressiveHeading03",
    "fluidHeading04": "expressiveHeading04",
    "fluidHeading05": "expressiveHeading05",
    "fluidHeading06": "expressiveHeading06",
    "fluidParagraph01": "expressiveParagraph01",
    "fluidQuotation01": "quotation01",
    "fluidQuotation02": "quotation02",
    "fluidDisplay01": "display01",
    "fluidDisplay02": "display02",
    "fluidDisplay03": "display03",
    "fluidDisplay04": "display04",
}
FAMILY = {
    "sans": "CarbonFontFamily.sans",
    "mono": "CarbonFontFamily.mono",
    "serif": "CarbonFontFamily.serif",
}
BREAKPOINTS = {"md": 672, "lg": 1056, "xlg": 1312, "max": 1584}
TEST_WIDTHS = [("sm", 320), ("md", 672), ("lg", 1056), ("xlg", 1312), ("max", 1584)]

HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_fluid_type.py — do not edit by hand.
//
// Values are ported verbatim from the Apache-2.0 licensed Carbon Design System
// (@carbon/type). See the NOTICE file for attribution.
"""




SCALE = scale_steps()
WEIGHTS = weights()


def braces(text: str, open_at: int) -> str:
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_at : i + 1]
    raise ValueError("unbalanced braces")


def extract(text: str, name: str) -> str:
    m = re.search(rf"export const {name} = \{{", text)
    return braces(text, m.end() - 1)


def fields(block: str) -> dict[str, object]:
    out: dict[str, object] = {}
    fam = re.search(r"fontFamily:\s*fontFamilies\.(\w+)", block)
    if fam:
        out["family"] = fam.group(1)
    size = re.search(r"fontSize:\s*rem\(scale\[(\d+)\]\)", block)
    if size:
        out["size"] = SCALE[int(size.group(1))]
    weight = re.search(r"fontWeight:\s*fontWeights\.(\w+)", block)
    if weight:
        out["weight"] = WEIGHTS[weight.group(1)]
    height = re.search(r"lineHeight:\s*([\d.]+)", block)
    if height:
        out["height"] = height.group(1)
    spacing = re.search(r"letterSpacing:\s*(?:px\((-?[\d.]+)\)|(0))", block)
    if spacing:
        out["spacing"] = spacing.group(1) if spacing.group(1) is not None else "0"
    return out


def parse(text: str, name: str) -> tuple[dict, dict[str, dict]]:
    full = extract(text, name)
    spread = re.search(r"\.\.\.(\w+)", full)
    bp_index = full.find("breakpoints:")
    base_text = full[:bp_index] if bp_index != -1 else full
    base = fields(extract(text, spread.group(1))) if spread else {}
    base.update(fields(base_text))
    overrides: dict[str, dict] = {}
    if bp_index != -1:
        bp_obj = braces(full, full.index("{", bp_index))
        for m in re.finditer(r"\b(md|lg|xlg|max):\s*\{", bp_obj):
            overrides[m.group(1)] = fields(braces(bp_obj, m.end() - 1))
    return base, overrides


def full_base(base: dict) -> dict:
    return {
        "family": base.get("family", "sans"),
        "size": base["size"],
        "weight": base.get("weight", WEIGHTS["regular"]),
        "height": base["height"],
        "spacing": base.get("spacing", "0"),
    }


def emit_style(f: dict, *, base: bool) -> str:
    a: list[str] = []
    if base or "family" in f:
        a.append(f"fontFamily: {FAMILY[f.get('family', 'sans')]}")
    if "size" in f:
        a.append(f"fontSize: {f['size']}")
    if base or "weight" in f:
        a.append(f"fontWeight: FontWeight.w{f.get('weight', WEIGHTS['regular'])}")
    if "height" in f:
        a.append(f"height: {f['height']}")
    if base or "spacing" in f:
        a.append(f"letterSpacing: {f.get('spacing', '0')}")
    return "TextStyle(" + ", ".join(a) + ")"


def cascade(base: dict, overrides: dict[str, dict], width: int) -> dict:
    acc = dict(full_base(base))
    for name, minimum in BREAKPOINTS.items():
        if name in overrides and width >= minimum:
            acc.update(overrides[name])
    return acc


def emit_lib(parsed: dict[str, tuple]) -> str:
    L = [
        HEADER,
        "import 'package:flutter/painting.dart' show FontWeight, TextStyle;",
        "",
        "import 'fluid_text_style.dart';",
        "import 'fonts.dart';",
        "",
        "/// The Carbon fluid (responsive) type styles.",
        "///",
        "/// Resolve one for a viewport width with"
        " [CarbonFluidTextStyle.resolve].",
        "abstract final class CarbonFluidTypeStyles {",
    ]
    for name in OBJECTS:
        base, overrides = parsed[name]
        L.append(f"  /// The `{name}` fluid type style.")
        L.append(f"  static const CarbonFluidTextStyle {name} = CarbonFluidTextStyle(")
        L.append(f"    base: {emit_style(full_base(base), base=True)},")
        if overrides:
            L.append("    overrides: <String, TextStyle>{")
            for bp, f in overrides.items():
                L.append(f"      '{bp}': {emit_style(f, base=False)},")
            L.append("    },")
        L.append("  );")
        L.append("")
    for alias, target in ALIASES.items():
        L.append(f"  /// The `{alias}` fluid type style (an alias of [{target}]).")
        L.append(f"  static const CarbonFluidTextStyle {alias} = {target};")
        L.append("")
    L.append("}")
    L.append("")
    return "\n".join(L)


def emit_test(parsed: dict[str, tuple]) -> str:
    L = [
        "// Copyright 2026 Bizjak Tech OÜ",
        "//",
        "// This file is part of Carbide and is licensed under the Apache License,",
        "// Version 2.0. See the LICENSE file in the project root.",
        "//",
        "// GENERATED by tool/generate_carbon_fluid_type.py — do not edit.",
        "",
        "import 'package:carbide/carbide.dart';",
        "import 'package:flutter/painting.dart';",
        "import 'package:flutter_test/flutter_test.dart';",
        "",
        "void main() {",
    ]
    for name in OBJECTS:
        base, overrides = parsed[name]
        L.append(f"  test('{name} cascades correctly across breakpoints', () {{")
        for _, width in TEST_WIDTHS:
            expected = emit_style(cascade(base, overrides, width), base=True)
            L.append(
                f"    expect(CarbonFluidTypeStyles.{name}.resolve({width}), "
                f"const {expected});"
            )
        L.append("  });")
        L.append("")
    L.append("  test('fluid aliases reference their base style', () {")
    for alias, target in ALIASES.items():
        L.append(
            f"    expect(CarbonFluidTypeStyles.{alias}, "
            f"same(CarbonFluidTypeStyles.{target}));"
        )
    L.append("  });")
    L.append("}")
    L.append("")
    return "\n".join(L)


def main() -> None:
    text = normalize_styles((TYPE_DIR / "styles.ts").read_text())
    parsed = {name: parse(text, name) for name in OBJECTS}
    LIB_OUT.write_text(emit_lib(parsed))
    TEST_OUT.write_text(emit_test(parsed))
    print(f"fluid styles: {len(OBJECTS)} objects + {len(ALIASES)} aliases")
    print(f"wrote {LIB_OUT.relative_to(ROOT)} and {TEST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
