#!/usr/bin/env python3
"""Generate viewport-relative spacing from Carbon's authoritative DTCG layout.

Reads packages/layout/src/dtcg/layout.json and emits the four fluid spacing
tokens and their independent percentage/resolution locks. Fixed spacing,
breakpoints and containers remain in layout.dart; no values are hand-copied.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "documentation/carbon/packages/layout/src/dtcg/layout.json"
LIB_OUT = ROOT / "lib/src/foundations/fluid_spacing.dart"
TEST_OUT = ROOT / "test/foundations/fluid_spacing_test.dart"
NAMES = tuple(f"fluid-spacing-{index:02}" for index in range(1, 5))
HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_layout.py — do not edit by hand.
//
// Values come from @carbon/layout/src/dtcg/layout.json (Apache-2.0).
// See NOTICE for attribution.
"""


def parse(source: Path = SOURCE) -> dict[str, float]:
    group = json.loads(source.read_text())["fluid-spacing"]
    tokens = {name: value for name, value in group.items() if not name.startswith("$")}
    if set(tokens) != set(NAMES):
        raise ValueError("fluid spacing family changed; update the public scope")
    result = {}
    for index, name in enumerate(NAMES, 1):
        token = tokens[name]
        if token.get("$type") != "dimension":
            raise ValueError(f"expected dimension for {name}")
        raw = token["$value"]
        if raw == "0":
            percent = 0.0
        else:
            match = re.fullmatch(r"(\d+(?:\.\d+)?)vw", str(raw))
            if not match:
                raise ValueError(f"unsupported viewport dimension: {raw}")
            percent = float(match[1])
        result[f"spacing{index:02}"] = percent
    return result


def number(value: float) -> str:
    return str(int(value)) if value.is_integer() else repr(value)


def emit_lib(values: dict[str, float]) -> str:
    lines = [HEADER, "/// @docImport 'layout.dart';", "library;", "",
             "/// Viewport-relative Carbon spacing tokens.", "///",
             "/// Resolve a token against the viewport width in logical pixels:",
             "///", "/// ```dart",
             "/// final gap = CarbonFluidSpacing.spacing02.resolve(",
             "///   MediaQuery.sizeOf(context).width,", "/// );", "/// ```",
             "///", "/// These tokens use the viewport, independent of a narrow enclosing column.",
             "/// Fixed spacing remains available through [CarbonSpacing].",
             "enum CarbonFluidSpacing {"]
    for index, (name, value) in enumerate(values.items()):
        end = ";" if index == len(values) - 1 else ","
        lines += [f"  /// The `{NAMES[index]}` token ({number(value)}% of viewport width).",
                  f"  {name}({number(value)}){end}", ""]
    lines += ["  const CarbonFluidSpacing(this.viewportPercent);", "",
              "  /// The percentage of viewport width this token represents.",
              "  final double viewportPercent;", "",
              "  /// Resolves the spacing in logical pixels for [viewportWidth].", "  ///",
              "  /// Throws an [ArgumentError] if the width is negative or not finite.",
              "  double resolve(double viewportWidth) {",
              "    if (!viewportWidth.isFinite || viewportWidth < 0) {",
              "      throw ArgumentError.value(", "        viewportWidth,",
              "        'viewportWidth',", "        'Must be finite and nonnegative',",
              "      );", "    }",
              "    return viewportWidth * (viewportPercent / 100);", "  }", "}", ""]
    return "\n".join(lines)


def emit_test(values: dict[str, float]) -> str:
    lines = [HEADER, "import 'package:carbide/carbide.dart';",
             "import 'package:flutter_test/flutter_test.dart';", "", "void main() {"]
    for name, percent in values.items():
        lines += [f"  test('{name} matches the Carbon viewport token', () {{",
                  f"    expect(CarbonFluidSpacing.{name}.viewportPercent, {number(percent)});"]
        for width in (0, 320, 672, 1056, 1312, 1584):
            expected = width * percent / 100
            lines.append(f"    expect(CarbonFluidSpacing.{name}.resolve({width}), closeTo({number(expected)}, 1e-9));")
        lines += ["  });", ""]
    lines += ["  test('fluid spacing rejects invalid viewport widths', () {",
              "    for (final CarbonFluidSpacing token in CarbonFluidSpacing.values) {",
              "      for (final double width in <double>[",
              "        -1, double.infinity, double.negativeInfinity, double.nan,",
              "      ]) {",
              "        expect(() => token.resolve(width), throwsArgumentError);",
              "      }", "    }", "  });", "",
              "  test('finite large widths do not overflow during resolution', () {",
              "    for (final CarbonFluidSpacing token in CarbonFluidSpacing.values) {",
              "      expect(token.resolve(1e308).isFinite, isTrue);", "    }",
              "  });", "}", ""]
    return "\n".join(lines)


def main() -> None:
    values = parse()
    LIB_OUT.write_text(emit_lib(values))
    TEST_OUT.write_text(emit_test(values))
    print(f"generated {len(values)} viewport spacing tokens from DTCG layout")


if __name__ == "__main__":
    main()
