#!/usr/bin/env python3
"""Generate viewport-relative spacing from Carbon's authoritative DTCG layout.

Reads packages/layout/src/dtcg/layout.json and emits the four fluid spacing
tokens and their independent percentage/resolution locks. Fixed spacing,
breakpoints and containers remain in layout.dart; no values are hand-copied.
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

from generation_check import run_generation, write_generated, remove_generated

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "documentation/carbon/packages/layout/src/dtcg/layout.json"
LIB_OUT = ROOT / "lib/src/foundations/fluid_spacing.dart"
TEST_OUT = ROOT / "test/foundations/fluid_spacing_test.dart"
NAMES = tuple(f"fluid-spacing-{index:02}" for index in range(1, 5))
HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_layout.py — do not edit by hand.
//
// Values come from @carbon/layout/src/dtcg/layout.json (Apache-2.0).
// See NOTICE for attribution.
"""


def parse(source: Path = SOURCE) -> dict[str, float]:
    group = json.loads(source.read_text())["fluid-spacing"]
    tokens = {name: value for name, value in group.items() if not name.startswith("$")}
    if set(tokens) != set(NAMES):
        raise ValueError("fluid spacing family changed; update the public scope")
    result = {}
    for index, name in enumerate(NAMES, 1):
        token = tokens[name]
        if token.get("$type") != "dimension":
            raise ValueError(f"expected dimension for {name}")
        raw = token["$value"]
        if raw == "0":
            percent = 0.0
        else:
            match = re.fullmatch(r"(\d+(?:\.\d+)?)vw", str(raw))
            if not match:
                raise ValueError(f"unsupported viewport dimension: {raw}")
            percent = float(match[1])
        result[f"spacing{index:02}"] = percent
    return result


def number(value: float) -> str:
    return str(int(value)) if value.is_integer() else repr(value)


def emit_lib(values: dict[str, float]) -> str:
    lines = [HEADER, "/// @docImport 'layout.dart';", "library;", "",
             "/// Viewport-relative Carbon spacing tokens.", "///",
             "/// Resolve a token against the viewport width in logical pixels:",
             "///", "/// ```dart",
             "/// final gap = CarbonFluidSpacing.spacing02.resolve(",
             "///   MediaQuery.sizeOf(context).width,", "/// );", "/// ```",
             "///", "/// These tokens use the viewport, independent of a narrow enclosing column.",
             "/// Fixed spacing remains available through [CarbonSpacing].",
             "enum CarbonFluidSpacing {"]
    for index, (name, value) in enumerate(values.items()):
        end = ";" if index == len(values) - 1 else ","
        lines += [f"  /// The `{NAMES[index]}` token ({number(value)}% of viewport width).",
                  f"  {name}({number(value)}){end}", ""]
    lines += ["  const CarbonFluidSpacing(this.viewportPercent);", "",
              "  /// The percentage of viewport width this token represents.",
              "  final double viewportPercent;", "",
              "  /// Resolves the spacing in logical pixels for [viewportWidth].", "  ///",
              "  /// Throws an [ArgumentError] if the width is negative or not finite.",
              "  double resolve(double viewportWidth) {",
              "    if (!viewportWidth.isFinite || viewportWidth < 0) {",
              "      throw ArgumentError.value(", "        viewportWidth,",
              "        'viewportWidth',", "        'Must be finite and nonnegative',",
              "      );", "    }",
              "    return viewportWidth * (viewportPercent / 100);", "  }", "}", ""]
    return "\n".join(lines)


def emit_test(values: dict[str, float]) -> str:
    lines = [HEADER, "import 'package:carbide/carbide.dart';",
             "import 'package:flutter_test/flutter_test.dart';", "", "void main() {"]
    for name, percent in values.items():
        lines += [f"  test('{name} matches the Carbon viewport token', () {{",
                  f"    expect(CarbonFluidSpacing.{name}.viewportPercent, {number(percent)});"]
        for width in (0, 320, 672, 1056, 1312, 1584):
            expected = width * percent / 100
            lines.append(f"    expect(CarbonFluidSpacing.{name}.resolve({width}), closeTo({number(expected)}, 1e-9));")
        lines += ["  });", ""]
    lines += ["  test('fluid spacing rejects invalid viewport widths', () {",
              "    for (final CarbonFluidSpacing token in CarbonFluidSpacing.values) {",
              "      for (final double width in <double>[",
              "        -1, double.infinity, double.negativeInfinity, double.nan,",
              "      ]) {",
              "        expect(() => token.resolve(width), throwsArgumentError);",
              "      }", "    }", "  });", "",
              "  test('finite large widths do not overflow during resolution', () {",
              "    for (final CarbonFluidSpacing token in CarbonFluidSpacing.values) {",
              "      expect(token.resolve(1e308).isFinite, isTrue);", "    }",
              "  });", "}", ""]
    return "\n".join(lines)


def main() -> None:
    values = parse()
    write_generated(LIB_OUT, emit_lib(values))
    write_generated(TEST_OUT, emit_test(values))
    fixed = ROOT / 'lib/src/foundations/layout.dart'
    write_generated(fixed, emit_fixed_layout(fixed.read_text()))
    print(f"prepared {len(values)} viewport spacing tokens from DTCG layout")


def camel(name):
    return re.sub(r'-([a-z0-9]+)', lambda match: match[1].capitalize(), name)


def dimension(token):
    if token['$type'] != 'dimension':
        raise ValueError('Expected layout dimension')
    value = token['$value']
    if type(value) in (int, float) and (not math.isfinite(value) or value < 0):
        raise ValueError(f'Unsupported layout number: {value}')
    converter = token.get('$extensions', {}).get('carbon.layout', {}).get('converter')
    if converter == 'miniUnits' and type(value) in (int, float):
        return float(value) * 8
    if converter == 'rem' and type(value) in (int, float):
        return float(value)
    match = re.fullmatch(r'(\d+(?:\.\d+)?)rem', str(value))
    if match and converter is None:
        return float(match[1]) * 16
    raise ValueError(f'Unsupported layout conversion: {value}/{converter}')


def emit_fixed_layout(source, layout_source=SOURCE, grid_source=ROOT / 'documentation/carbon/packages/grid/scss/_config.scss'):
    data = json.loads(layout_source.read_text())
    size_names = {'size-xs': 'xSmall', 'size-sm': 'small', 'size-md': 'medium', 'size-lg': 'large', 'size-xl': 'xLarge', 'size-2xl': 'xxLarge'}
    groups = {'spacing': 'CarbonSpacing', 'container': 'CarbonContainer', 'size': 'CarbonSize', 'icon-size': 'CarbonIconSize'}
    for group, class_name in groups.items():
        values = {(size_names[name] if group == 'size' else camel(name)): dimension(token)
                  for name, token in data[group].items() if not name.startswith('$')}
        pattern = rf'(abstract final class {class_name} \{{)(.*?)(\n\}})'
        body = re.search(pattern, source, re.S)
        if body is None:
            raise ValueError(f'Missing layout class {class_name}')
        fields = r'static const double (\w+) = ([\d.]+);'
        if {name for name, _ in re.findall(fields, body[2])} != set(values):
            raise ValueError(f'{class_name} family changed; review the public API')
        generated = re.sub(fields, lambda m: f'static const double {m[1]} = {number(values[m[1]])};', body[2])
        source = source[:body.start(2)] + generated + source[body.end(2):]
    scss = grid_source.read_text()
    grid = re.search(r'\$grid-breakpoints:\s*\((.*?)\n\) !default;', scss, re.S)
    if grid is None:
        raise ValueError('Grid breakpoint source format changed')
    breakpoints = {}
    for name, body in re.findall(r'^  (\w+): \(\n(.*?)^  \),', grid[1], re.M | re.S):
        values = {}
        for key, expression in re.findall(r'^    (\w+): (.*),$', body, re.M):
            pixels = re.fullmatch(r'convert\.to-rem\((\d+)px\)', expression)
            if pixels:
                value = int(pixels[1])
            elif re.fullmatch(r'\d+', expression):
                value = int(expression)
            else:
                raise ValueError(f'Unsupported breakpoint expression: {expression}')
            values[key] = value
        if set(values) != {'columns', 'margin', 'width'}:
            raise ValueError(f'Breakpoint fields changed: {name}')
        breakpoints[name] = values
    pattern = r'static const CarbonBreakpoint (\w+) = CarbonBreakpoint\((.*?)\n  \);'
    if {name for name, _ in re.findall(pattern, source, re.S)} != set(breakpoints):
        raise ValueError('Breakpoint family changed; review the public API')
    def replace(match):
        body = match[2]
        for key, value in breakpoints[match[1]].items():
            body, count = re.subn(rf'({key}: )\d+', lambda m: m[1] + str(value), body)
            if count != 1:
                raise ValueError(f'Missing/duplicated breakpoint field: {key}')
        return f'static const CarbonBreakpoint {match[1]} = CarbonBreakpoint({body}\n  );'
    return re.sub(pattern, replace, source, flags=re.S)


if __name__ == "__main__":
    run_generation(main)
