#!/usr/bin/env python3
"""Generate Carbide's icon data from the pinned Carbon sources.

Reads every SVG in documentation/carbon/packages/icons/src/svg (sizes
16/20/24/32 including the watson-health and Q namespaces, plus bespoke
"glyph" assets at the root), validates the set two-way against icons.yml
exactly like the upstream registry does, and emits:

  - lib/src/icons/generated/icons_<bucket>.dart  (heavy const shape data)
  - lib/src/icons/carbon_icons.dart              (the CarbonIcons index)
  - test/icons/all_icons.dart                    (the full list, test-only)

Identifier rules: kebab-case -> lowerCamelCase; namespaced icons get a
`watsonHealth`/`q` prefix; the few non-namespaced names starting with a digit
get a `$` prefix (e.g. `$4k`). Deprecated icons (deprecated.yml) carry
@Deprecated with the upstream reason on their CarbonIcons entry.

Run from the repository root:  python3 tool/generate_carbon_icons.py
Re-run when bumping the Carbon submodule; review the diff.
"""

from __future__ import annotations

import re
from pathlib import Path

import icons_lock
from carbon_svg import IDENTITY, extract, fnum

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "documentation/carbon/packages/icons"
SVG = PKG / "src/svg"
GEN_DIR = ROOT / "lib/src/icons/generated"
INDEX = ROOT / "lib/src/icons/carbon_icons.dart"
ALL_LIST = ROOT / "test/icons/all_icons.dart"

SIZES = (16, 20, 24, 32)

HEADER = """\
// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_icons.py — do not edit by hand.
//
// Icon artwork is ported from the Apache-2.0 licensed Carbon Design System
// (@carbon/icons). See the NOTICE file for attribution.
"""


# --- registry -----------------------------------------------------------


def parse_icons_yml() -> dict[str, set]:
    """Returns name -> declared sizes (ints and the string 'glyph')."""
    entries: dict[str, set] = {}
    name = None
    in_sizes = False
    for line in (PKG / "icons.yml").read_text().splitlines():
        m = re.match(r"^- name: (.+)$", line)
        if m:
            name = m.group(1).strip().strip("'\"")
            entries[name] = set()
            in_sizes = False
            continue
        if re.match(r"^  \w", line):
            in_sizes = line.strip() == "sizes:"
            continue
        if in_sizes and name is not None:
            m = re.match(r"^    - (.+)$", line)
            if m:
                value = m.group(1).strip()
                entries[name].add(
                    int(value) if value.isdigit() else value
                )
    return entries


def parse_deprecated_yml(path: Path = PKG / "deprecated.yml") -> dict[str, str]:
    """Returns deprecated icon name -> single-line reason."""
    out: dict[str, str] = {}
    name = None
    reason_lines: list[str] = []

    def flush() -> None:
        if name is not None:
            out[name] = " ".join(" ".join(reason_lines).split())

    for line in path.read_text().splitlines():
        m = re.match(r"^  - name: (.+)$", line)
        if m:
            flush()
            name = m.group(1).strip()
            reason_lines = []
            continue
        m = re.match(r"^    reason:\s*(.*)$", line)
        if m:
            reason_lines = [m.group(1)] if m.group(1) else []
            continue
        if name is not None and line.startswith("      "):
            reason_lines.append(line.strip())
    flush()
    return out


def collect_assets() -> dict[str, dict]:
    """Returns name -> {'namespace': str, 'assets': {size_or_glyph: Path}}."""
    icons: dict[str, dict] = {}

    def add(name: str, namespace: str, size, path: Path) -> None:
        entry = icons.setdefault(name, {"namespace": namespace, "assets": {}})
        assert entry["namespace"] == namespace, f"namespace clash: {name}"
        assert size not in entry["assets"], f"duplicate asset: {name} {size}"
        entry["assets"][size] = path

    for path in sorted(SVG.glob("*.svg")):
        add(path.stem, "", "glyph", path)
    for size in SIZES:
        base = SVG / str(size)
        if not base.is_dir():
            continue
        for path in sorted(base.glob("*.svg")):
            add(path.stem, "", size, path)
        for sub in sorted(p for p in base.iterdir() if p.is_dir()):
            for path in sorted(sub.glob("*.svg")):
                add(path.stem, sub.name, size, path)
    return icons


def validate(icons: dict[str, dict], registry: dict[str, set]) -> None:
    """Two-way validation mirroring the upstream icons metadata extension."""
    problems: list[str] = []
    for name, entry in icons.items():
        if name not in registry:
            problems.append(f"asset `{name}` missing from icons.yml")
            continue
        declared = set(registry[name])
        # Upstream auto-adds 'glyph' for assets without a size.
        if "glyph" in entry["assets"]:
            declared.add("glyph")
        actual = set(entry["assets"])
        if actual != declared:
            problems.append(
                f"`{name}`: assets {sorted(map(str, actual))} != "
                f"declared {sorted(map(str, declared))}"
            )
    for name in registry:
        if name not in icons:
            problems.append(f"icons.yml entry `{name}` has no asset")
    if problems:
        raise SystemExit(
            "registry validation failed:\n  " + "\n  ".join(problems[:20])
        )


# --- naming -------------------------------------------------------------

NAMESPACE_PREFIX = {"": "", "watson-health": "watson-health", "Q": "q"}

# Dart reserved words (plus await/yield) cannot be identifiers; like
# digit-leading names they get a `$` prefix (e.g. the `continue` icon).
DART_RESERVED = {
    "assert", "await", "break", "case", "catch", "class", "const",
    "continue", "default", "do", "else", "enum", "extends", "false",
    "final", "finally", "for", "if", "in", "is", "new", "null", "rethrow",
    "return", "super", "switch", "this", "throw", "true", "try", "var",
    "void", "while", "with", "yield",
}


def identifier(name: str, namespace: str) -> str:
    tokens = [t for t in re.split(r"[-_.]+", name) if t]
    if namespace:
        tokens = [t for t in re.split(r"[-_.]+", namespace) if t] + tokens
    first = tokens[0][0].lower() + tokens[0][1:]
    rest = [t[0].upper() + t[1:] for t in tokens[1:]]
    ident = first + "".join(rest)
    if ident[0].isdigit() or ident in DART_RESERVED:
        ident = "$" + ident
    return ident


def bucket_of(ident: str) -> str:
    first = ident[0]
    return "num" if first == "$" else first


# --- emission -----------------------------------------------------------


def matrix_close_to_identity(m) -> bool:
    return all(abs(a - b) < 1e-12 for a, b in zip(m, IDENTITY))


def shape_dart(shape, indent: str) -> list[str]:
    d, evenodd, matrix = shape
    d = " ".join(d.split())
    assert "'" not in d and "$" not in d and "\\" not in d, f"unsafe d: {d!r}"
    lines = [f"{indent}CarbonIconShape("]
    lines.append(f"{indent}  d: '{d}',")
    if evenodd:
        lines.append(f"{indent}  evenOdd: true,")
    if not matrix_close_to_identity(matrix):
        values = ", ".join(fnum(v) for v in matrix)
        lines.append(f"{indent}  matrix: <double>[{values}],")
    lines.append(f"{indent}),")
    return lines


def artwork_dart(size, vbw, vbh, shapes, indent: str) -> list[str]:
    lines = [f"{indent}CarbonIconArtwork("]
    if size != "glyph":
        lines.append(f"{indent}  size: {size},")
    lines.append(f"{indent}  viewBoxWidth: {fnum(vbw)},")
    lines.append(f"{indent}  viewBoxHeight: {fnum(vbh)},")
    lines.append(f"{indent}  shapes: <CarbonIconShape>[")
    for shape in shapes:
        lines += shape_dart(shape, indent + "    ")
    lines.append(f"{indent}  ],")
    lines.append(f"{indent}),")
    return lines


def sort_key(size):
    return -1 if size == "glyph" else size


def main() -> None:
    registry = parse_icons_yml()
    deprecated = parse_deprecated_yml()
    icons = collect_assets()
    validate(icons, registry)

    entries = []
    seen: dict[str, str] = {}
    for name in sorted(icons, key=str.lower):
        namespace = icons[name]["namespace"]
        ident = identifier(name, NAMESPACE_PREFIX[namespace])
        assert ident not in seen, f"identifier clash: {ident} ({name}, {seen[ident]})"
        seen[ident] = name
        artwork = []
        for size in sorted(icons[name]["assets"], key=sort_key):
            vbw, vbh, shapes = extract(icons[name]["assets"][size])
            assert vbw > 0 and vbh > 0, f"invalid viewBox: {name}"
            artwork.append((size, vbw, vbh, shapes))
        entries.append((ident, name, artwork))
    entries.sort(key=lambda e: e[0].lower().lstrip("$"))

    # Heavy data files, bucketed by identifier initial.
    buckets: dict[str, list] = {}
    for entry in entries:
        buckets.setdefault(bucket_of(entry[0]), []).append(entry)

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    for old in GEN_DIR.glob("icons_*.dart"):
        old.unlink()
    for bucket, items in sorted(buckets.items()):
        lines = [
            HEADER,
            "import '../carbon_icon_data.dart';",
            "",
        ]
        for ident, name, artwork in items:
            lines.append(f"/// The Carbon `{name}` icon data.")
            lines.append(f"const CarbonIconData {ident} = CarbonIconData(")
            lines.append(f"  name: '{name}',")
            lines.append("  artwork: <CarbonIconArtwork>[")
            for size, vbw, vbh, shapes in artwork:
                lines += artwork_dart(size, vbw, vbh, shapes, "    ")
            lines.append("  ],")
            lines.append(");")
            lines.append("")
        (GEN_DIR / f"icons_{bucket}.dart").write_text("\n".join(lines))

    # The light index class.
    lines = [
        HEADER,
        "import 'carbon_icon_data.dart';",
    ]
    for bucket in sorted(buckets):
        lines.append(f"import 'generated/icons_{bucket}.dart' as {bucket}_;")
    lines += [
        "",
        "/// Every Carbon icon, as generated [CarbonIconData] constants.",
        "///",
        "/// Each entry is an independent constant, so unused icons are",
        "/// tree-shaken from release builds. Render one with the icon widget;",
        "/// names mirror Carbon's (kebab-case to lowerCamelCase, with",
        "/// `watsonHealth`/`q` namespace prefixes).",
        "abstract final class CarbonIcons {",
    ]
    for ident, name, _ in entries:
        bucket = bucket_of(ident)
        lines.append(f"  /// The Carbon `{name}` icon.")
        if name in deprecated:
            reason = deprecated[name].replace(r"$", r"\$").replace("'", r"\'")
            lines.append(f"  @Deprecated('{reason}')")
        lines.append(
            f"  static const CarbonIconData {ident} = {bucket}_.{ident};"
        )
        lines.append("")
    lines.append("}")
    INDEX.write_text("\n".join(lines))

    # The exhaustive list, for tests only (would defeat tree-shaking in lib).
    lines = [
        HEADER.replace("lib/", "test/"),
        "// Test-only: referencing every icon here would defeat tree-shaking",
        "// in an app, which is why this list does not live in lib/.",
        "",
        "import 'package:carbide/carbide.dart';",
    ]
    for bucket in sorted(buckets):
        lines.append(
            "import 'package:carbide/src/icons/generated/"
            f"icons_{bucket}.dart' as {bucket}_;"
        )
    lines += [
        "",
        "/// Every generated Carbon icon.",
        "const List<CarbonIconData> allCarbonIcons = <CarbonIconData>[",
    ]
    for ident, _, _ in entries:
        lines.append(f"  {bucket_of(ident)}_.{ident},")
    lines += ["];", ""]
    ALL_LIST.write_text("\n".join(lines))

    # Lockfile: record what this generation was produced from, and report
    # what changed relative to the previous generation (see icons_lock.py).
    previous = icons_lock.read_lock()
    lock = icons_lock.compute_lock(icons, deprecated)
    icons_lock.write_lock(lock)
    if previous is not None:
        print(icons_lock.format_report(icons_lock.diff_locks(previous, lock)))

    glyphs = sum(1 for e in entries if any(a[0] == "glyph" for a in e[2]))
    multi = sum(1 for e in entries if len(e[2]) > 1)
    total_assets = sum(len(e[2]) for e in entries)
    print(
        f"icons: {len(entries)} (registry {len(registry)}), "
        f"assets: {total_assets}, multi-size: {multi}, glyphs: {glyphs}, "
        f"deprecated: {sum(1 for e in entries if e[1] in deprecated)}, "
        f"buckets: {len(buckets)}"
    )


if __name__ == "__main__":
    main()
