#!/usr/bin/env python3
"""Generate the ported Carbon theme tokens from authoritative DTCG JSON.

Reads themes/src/dtcg/themes.json and the button, tag, notification, status,
and content-switcher
component files. Resolves palette/theme aliases, per-theme alpha modifiers,
and DTCG color objects into CarbonThemeData and exhaustive value tests.
Syntax and chat tokens beyond the shipped chat button remain out of scope.

Run from the repository root: python3 tool/generate_carbon_themes.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from generation_check import run_generation, write_generated, remove_generated

from generate_carbon_colors import parse as parse_colors

ROOT = Path(__file__).resolve().parent.parent
THEME_DIR = ROOT / "documentation/carbon/packages/themes/src"
THEMES = {"white": "white", "gray10": "g10", "gray90": "g90", "gray100": "g100"}
TITLES = {"white": "White", "gray10": "Gray 10", "gray90": "Gray 90", "gray100": "Gray 100"}
LIB_OUT = ROOT / "lib/src/theme/carbon_theme_data.dart"
TEST_OUT = ROOT / "test/theme/carbon_theme_data_test.dart"

HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.
//
// Built-in token values are ported verbatim from the Apache-2.0 licensed Carbon
// Design System (@carbon/themes). See the NOTICE file for attribution.
"""

# Explicit public subset and ordering; expand deliberately when porting a group.
PORTED_TOKENS = [
    'background',
    'backgroundInverse',
    'backgroundBrand',
    'backgroundActive',
    'backgroundHover',
    'backgroundInverseHover',
    'backgroundSelected',
    'backgroundSelectedHover',
    'layer01',
    'layerActive01',
    'layerBackground01',
    'layerHover01',
    'layerSelected01',
    'layerSelectedHover01',
    'layer02',
    'layerActive02',
    'layerBackground02',
    'layerHover02',
    'layerSelected02',
    'layerSelectedHover02',
    'layer03',
    'layerActive03',
    'layerBackground03',
    'layerHover03',
    'layerSelected03',
    'layerSelectedHover03',
    'layerSelectedInverse',
    'layerSelectedDisabled',
    'layerAccent01',
    'layerAccentActive01',
    'layerAccentHover01',
    'layerAccent02',
    'layerAccentActive02',
    'layerAccentHover02',
    'layerAccent03',
    'layerAccentActive03',
    'layerAccentHover03',
    'field01',
    'fieldHover01',
    'field02',
    'fieldHover02',
    'field03',
    'fieldHover03',
    'borderSubtle00',
    'borderSubtle01',
    'borderSubtleSelected01',
    'borderSubtle02',
    'borderSubtleSelected02',
    'borderSubtle03',
    'borderSubtleSelected03',
    'borderStrong01',
    'borderStrong02',
    'borderStrong03',
    'borderTile01',
    'borderTile02',
    'borderTile03',
    'borderInverse',
    'borderInteractive',
    'borderDisabled',
    'textPrimary',
    'textSecondary',
    'textPlaceholder',
    'textHelper',
    'textError',
    'textInverse',
    'textOnColor',
    'textOnColorDisabled',
    'textDisabled',
    'linkPrimary',
    'linkPrimaryHover',
    'linkSecondary',
    'linkInverse',
    'linkVisited',
    'linkInverseVisited',
    'linkInverseActive',
    'linkInverseHover',
    'iconPrimary',
    'iconSecondary',
    'iconInverse',
    'iconOnColor',
    'iconOnColorDisabled',
    'iconDisabled',
    'iconInteractive',
    'supportError',
    'supportSuccess',
    'supportWarning',
    'supportInfo',
    'supportErrorInverse',
    'supportSuccessInverse',
    'supportWarningInverse',
    'supportInfoInverse',
    'supportCautionMinor',
    'supportCautionMajor',
    'supportCautionUndefined',
    'focus',
    'focusInset',
    'focusInverse',
    'skeletonBackground',
    'skeletonElement',
    'interactive',
    'highlight',
    'overlay',
    'toggleOff',
    'shadow',
    'buttonSeparator',
    'buttonPrimary',
    'buttonSecondary',
    'buttonTertiary',
    'buttonDangerPrimary',
    'buttonDangerSecondary',
    'buttonDangerActive',
    'buttonPrimaryActive',
    'buttonSecondaryActive',
    'buttonTertiaryActive',
    'buttonDangerHover',
    'buttonPrimaryHover',
    'buttonSecondaryHover',
    'buttonTertiaryHover',
    'buttonDisabled',
    'tagBackgroundRed',
    'tagColorRed',
    'tagHoverRed',
    'tagBackgroundMagenta',
    'tagColorMagenta',
    'tagHoverMagenta',
    'tagBackgroundPurple',
    'tagColorPurple',
    'tagHoverPurple',
    'tagBackgroundBlue',
    'tagColorBlue',
    'tagHoverBlue',
    'tagBackgroundCyan',
    'tagColorCyan',
    'tagHoverCyan',
    'tagBackgroundTeal',
    'tagColorTeal',
    'tagHoverTeal',
    'tagBackgroundGreen',
    'tagColorGreen',
    'tagHoverGreen',
    'tagBackgroundGray',
    'tagColorGray',
    'tagHoverGray',
    'tagBackgroundCoolGray',
    'tagColorCoolGray',
    'tagHoverCoolGray',
    'tagBackgroundWarmGray',
    'tagColorWarmGray',
    'tagHoverWarmGray',
    'tagBorderRed',
    'tagBorderBlue',
    'tagBorderCyan',
    'tagBorderTeal',
    'tagBorderGreen',
    'tagBorderMagenta',
    'tagBorderPurple',
    'tagBorderGray',
    'tagBorderCoolGray',
    'tagBorderWarmGray',
    'notificationBackgroundError',
    'notificationBackgroundSuccess',
    'notificationBackgroundInfo',
    'notificationBackgroundWarning',
    'notificationActionHover',
    'notificationActionTertiaryInverse',
    'notificationActionTertiaryInverseActive',
    'notificationActionTertiaryInverseHover',
    'notificationActionTertiaryInverseText',
    'notificationActionTertiaryInverseTextOnColorDisabled',
    'aiInnerShadow',
    'aiAuraStartSm',
    'aiAuraStart',
    'aiAuraEnd',
    'aiBorderStrong',
    'aiBorderStart',
    'aiBorderEnd',
    'aiDropShadow',
    'aiAuraHoverBackground',
    'aiAuraHoverStart',
    'aiAuraHoverEnd',
    'aiPopoverBackground',
    'aiPopoverShadowOuter01',
    'aiPopoverShadowOuter02',
    'aiSkeletonBackground',
    'aiSkeletonElementBackground',
    'aiOverlay',
    'aiPopoverCaretCenter',
    'aiPopoverCaretBottom',
    'aiPopoverCaretBottomBackgroundActions',
    'aiPopoverCaretBottomBackground',
    'chatButton',
    'chatButtonHover',
    'chatButtonTextHover',
    'chatButtonActive',
    'chatButtonSelected',
    'chatButtonTextSelected',
]

# New groups have generated compatibility defaults, so existing callers of
# the const constructor need not add thirteen arguments to custom themes.
COMPONENT_TOKENS = [
    'statusAccessibilityBackground',
    'statusRed',
    'statusOrange',
    'statusOrangeOutline',
    'statusYellow',
    'statusYellowOutline',
    'statusPurple',
    'statusGreen',
    'statusBlue',
    'statusGray',
    'contentSwitcherSelected',
    'contentSwitcherBackground',
    'contentSwitcherBackgroundHover',
]
PORTED_TOKENS += COMPONENT_TOKENS
NULLABLE_TOKENS = {'statusOrangeOutline', 'statusYellowOutline'}


def camel(path: str) -> str:
    return re.sub(r"[.-]([a-z0-9])", lambda match: match[1].upper(), path)


def flatten_tokens(node: dict, path: tuple = ()) -> dict:
    """Keep dual-role nodes: a token may also contain child tokens."""
    tokens = {}
    if "carbon.themes" in node.get("$extensions", {}):
        tokens[".".join(path)] = node
    for key, child in node.items():
        if not key.startswith("$") and isinstance(child, dict):
            tokens.update(flatten_tokens(child, (*path, key)))
    return tokens


def resolve_token(path, theme, tokens, palette, visiting=()):
    if path in visiting:
        raise ValueError(f"cyclic token reference: {path}")
    extensions = tokens[path]["$extensions"]
    values = extensions["carbon.themes"]
    if theme not in values:
        # Upstream does not define status outlines on either dark theme.
        if camel(path) in NULLABLE_TOKENS and theme in ("g90", "g100"):
            return "null"
        # _notification.scss supplies layer-hover on dark action surfaces.
        if path != "notification.action-hover" or theme not in ("g90", "g100"):
            raise ValueError(f"missing {theme} value for {path}")
        return resolve_token("layer.hover.01", theme, tokens, palette, (*visiting, path))
    value = values[theme]
    alpha = extensions.get("org.carbon", {}).get("alphaModifiers", {}).get(theme)
    if isinstance(value, dict):
        alpha = value.get("alpha", alpha)
        value = value["value"] if "value" in value else value["hex"]
    if value.startswith("{"):
        reference = value[1:-1]
        name = camel(reference.replace(".default", ""))
        if name in palette:
            result = f"CarbonColors.{name}"
        else:
            result = resolve_token(reference, theme, tokens, palette, (*visiting, path))
    else:
        if not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
            raise ValueError(f"unsupported color: {value}")
        reverse = {hexv: name for name, hexv in reversed(list(palette.items())) if "Hover" not in name}
        name = reverse.get(value[1:].upper())
        result = f"CarbonColors.{name}" if name else f"const Color(0xFF{value[1:].upper()})"
    return f"_alpha({result}, {float(alpha)})" if alpha is not None else result


def section_of(name: str) -> str:
    match = re.match(r"^[a-z]+", name)
    return match.group(0) if match else name


def build():
    tokens = {}
    dtcg = THEME_DIR / "dtcg"
    sources = [dtcg / "themes.json"]
    sources += [dtcg / "components" / f"{name}.json" for name in ("button", "tag", "notification", "status", "content-switcher")]
    for source in sources:
        tokens.update(flatten_tokens(json.loads(source.read_text())))
    paths = {camel(path): path for path in tokens}
    palette = {name: argb[4:] for name, argb in parse_colors()}
    resolved = {
        field: {name: resolve_token(paths[name], slug, tokens, palette) for name in PORTED_TOKENS}
        for field, slug in THEMES.items()
    }
    brightness = {field: "light" if field in ("white", "gray10") else "dark" for field in THEMES}
    return PORTED_TOKENS, brightness, resolved


def constant_color(expression: str) -> str:
    """Express a resolved token as a const constructor-compatible value."""
    if not expression.startswith("_alpha("):
        return expression
    match = re.fullmatch(r"_alpha\(CarbonColors\.(\w+), ([\d.]+)\)", expression)
    if not match:
        raise ValueError(f"unsupported const color default: {expression}")
    palette = dict(parse_colors())
    rgb = palette[match[1]][4:]
    channels = [int(rgb[index:index + 2], 16) for index in (0, 2, 4)]
    return (
        f"const Color.from(alpha: {match[2]}, "
        f"red: {channels[0]} / 255, green: {channels[1]} / 255, "
        f"blue: {channels[2]} / 255)"
    )


def component_defaults(resolved, name):
    """Reject future theme divergence rather than emitting inaccurate defaults."""
    if resolved['white'][name] != resolved['gray10'][name]:
        raise ValueError(f"light compatibility defaults differ for {name}")
    if resolved['gray90'][name] != resolved['gray100'][name]:
        raise ValueError(f"dark compatibility defaults differ for {name}")
    return constant_color(resolved['white'][name]), constant_color(resolved['gray100'][name])


def emit_lib(order, brightness, resolved) -> str:
    lines = [
        HEADER,
        "import 'dart:ui' show Brightness, Color;",
        "",
        "import 'package:flutter/foundation.dart' show immutable;",
        "",
        "import '../foundations/colors.dart';",
        "",
        "/// The resolved semantic color tokens for one Carbon theme.",
        "///",
        "/// Carbon ships four themes — [white], [gray10], [gray90], and",
        "/// [gray100] — each mapping the same set of semantic tokens",
        "/// (background, layer, field, text, support, …) onto the palette. Use",
        "/// a built-in, or construct a custom theme with the constructor.",
        "@immutable",
        "class CarbonThemeData {",
        "  /// Creates a theme from an explicit set of semantic tokens.",
        "  ///",
        "  /// Status and content-switcher tokens default to the upstream light",
        "  /// or dark palette for [brightness] when omitted. All built-in",
        "  /// themes explicitly supply their generated values.",
        "  const CarbonThemeData({",
        "    required this.brightness,",
    ]
    lines += [f"    required this.{n}," for n in order if n not in COMPONENT_TOKENS]
    lines += [f"    Color? {n}," for n in order if n in COMPONENT_TOKENS]
    new_fields = [n for n in order if n in COMPONENT_TOKENS]
    if new_fields:
        lines.append("  }) :")
        for index, name in enumerate(new_fields):
            light, dark = component_defaults(resolved, name)
            end = ";" if index == len(new_fields) - 1 else ","
            lines.append(f"    {name} = {name} ?? (brightness == Brightness.dark ? {dark} : {light}){end}")
    else:
        lines.append("  });")
    lines.append("")
    lines.append("  /// Whether this is a light or dark theme.")
    lines.append("  final Brightness brightness;")
    section = None
    for n in order:
        if section_of(n) != section:
            section = section_of(n)
            lines.append("")
        lines.append(f"  /// The `{n}` token.")
        if n in NULLABLE_TOKENS:
            lines.append("  ///")
            lines.append("  /// Null on the built-in dark themes, which omit this outline.")
        lines.append(f"  final {'Color?' if n in NULLABLE_TOKENS else 'Color'} {n};")
    lines.append("")
    for field in THEMES:
        lines.append(f"  /// The {TITLES[field]} theme.")
        lines.append(f"  static final CarbonThemeData {field} = CarbonThemeData(")
        lines.append(f"    brightness: Brightness.{brightness[field]},")
        lines += [f"    {n}: {resolved[field][n]}," for n in order]
        lines.append("  );")
        lines.append("")

    # Carbide's accessibility adaptation is separate from the upstream themes.
    lines += HIGH_CONTRAST_FACTORY.strip("\n").splitlines() + [""]

    # copyWith
    lines.append("  /// A copy of this theme with the given tokens replaced.")
    lines.append("  ///")
    lines.append("  /// Null arguments retain their current values, including nullable status")
    lines.append("  /// outlines. Pass a transparent color to suppress an existing outline.")
    lines.append("  CarbonThemeData copyWith({")
    lines.append("    Brightness? brightness,")
    lines += [f"    Color? {n}," for n in order]
    lines.append("  }) {")
    lines.append("    return CarbonThemeData(")
    lines.append("      brightness: brightness ?? this.brightness,")
    lines += [f"      {n}: {n} ?? this.{n}," for n in order]
    lines.append("    );")
    lines.append("  }")
    lines.append("")

    # lerp
    lines.append("  /// Linearly interpolates between themes [a] and [b].")
    lines.append("  ///")
    lines.append("  /// [brightness] snaps to [b] from the midpoint.")
    lines.append(
        "  static CarbonThemeData lerp("
        "CarbonThemeData a, CarbonThemeData b, double t) {"
    )
    # Color.lerp(color, null, 1) returns a transparent color, not null.
    # Preserve exact theme endpoints, including genuinely absent outlines.
    lines.append("    if (t == 0) return a;")
    lines.append("    if (t == 1) return b;")
    lines.append("    return CarbonThemeData(")
    lines.append("      brightness: t < 0.5 ? a.brightness : b.brightness,")
    lines += [f"      {n}: Color.lerp(a.{n}, b.{n}, t){'' if n in NULLABLE_TOKENS else '!'}," for n in order]
    lines.append("    );")
    lines.append("  }")
    lines.append("")

    # equality
    conds = ["other.brightness == brightness"]
    conds += [f"other.{n} == {n}" for n in order]
    lines.append("  @override")
    lines.append("  bool operator ==(Object other) {")
    lines.append("    if (identical(this, other)) {")
    lines.append("      return true;")
    lines.append("    }")
    lines.append("    return other is CarbonThemeData &&")
    lines.append("        " + " &&\n        ".join(conds) + ";")
    lines.append("  }")
    lines.append("")

    # hashCode
    lines.append("  @override")
    lines.append("  int get hashCode => Object.hashAll(<Object?>[")
    lines.append("    brightness,")
    lines += [f"    {n}," for n in order]
    lines.append("  ]);")

    lines.append("}")
    lines.append("")
    lines.append("Color _alpha(Color color, double opacity) =>")
    lines.append("    color.withValues(alpha: opacity);")
    lines.append("")
    return "\n".join(lines)


def emit_test(order, brightness, resolved) -> str:
    lines = [
        "// Copyright 2026 Bizjak Tech OÜ",
        "//",
        "// This file is part of Carbide and is licensed under the Apache License,",
        "// Version 2.0. See the LICENSE file in the project root.",
        "//",
        "// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.",
        "",
        "import 'dart:ui';",
        "",
        "import 'package:carbide/carbide.dart';",
        "import 'package:flutter_test/flutter_test.dart';",
        "",
        "Color _alpha(Color color, double opacity) =>",
        "    color.withValues(alpha: opacity);",
        "",
        "void main() {",
    ]
    for field in THEMES:
        lines.append(f"  test('{field} theme tokens match the Carbon source', () {{")
        lines.append(
            f"    expect(CarbonThemeData.{field}.brightness, "
            f"Brightness.{brightness[field]});"
        )
        lines += [
            f"    expect(CarbonThemeData.{field}.{n}, {resolved[field][n]});"
            for n in order
        ]
        lines.append("  });")
        lines.append("")
    new_fields = [name for name in order if name in COMPONENT_TOKENS]
    if new_fields:
        lines += [
            "  test('component defaults preserve legacy custom theme construction', () {",
            "    for (final base in <CarbonThemeData>[",
            "      CarbonThemeData.white, CarbonThemeData.gray10,",
            "      CarbonThemeData.gray90, CarbonThemeData.gray100,",
            "    ]) {",
            "      final legacy = CarbonThemeData(",
            "        brightness: base.brightness,",
        ]
        lines += [f"        {name}: base.{name}," for name in order if name not in COMPONENT_TOKENS]
        lines += ["      );", "      expect(legacy, base);",
                  "      expect(legacy.hashCode, base.hashCode);", "    }", "  });", ""]
        for name in new_fields:
            lines += [
                f"  test('{name} participates in custom themes and value equality', () {{",
                "    const custom = Color(0xFF123456);",
                "    for (final base in <CarbonThemeData>[",
                "      CarbonThemeData.white, CarbonThemeData.gray10,",
                "      CarbonThemeData.gray90, CarbonThemeData.gray100,",
                "    ]) {",
                f"      final changed = base.copyWith({name}: custom);",
                f"      expect(changed.{name}, custom);",
                "      expect(changed, isNot(base));",
                "      expect(changed.copyWith(), changed);",
                "      expect(changed.copyWith().hashCode, changed.hashCode);",
                f"      expect(base.copyWith({name}: null), base);",
                "    }", "  });", "",
            ]
        lines += [
            "  test('new component tokens interpolate including absent outlines', () {",
            "    final themes = <CarbonThemeData>[",
            "      CarbonThemeData.white, CarbonThemeData.gray10,",
            "      CarbonThemeData.gray90, CarbonThemeData.gray100,",
            "    ];",
            "    for (final a in themes) {",
            "      for (final b in themes) {",
            "        expect(CarbonThemeData.lerp(a, b, 0), same(a));",
            "        expect(CarbonThemeData.lerp(a, b, 1), same(b));",
            "        final mid = CarbonThemeData.lerp(a, b, 0.5);",
        ]
        lines += [f"        expect(mid.{name}, Color.lerp(a.{name}, b.{name}, 0.5));" for name in new_fields]
        lines += ["      }", "    }", "  });", "",
                  "  test('high contrast preserves semantic component colors', () {",
                  "    for (final base in <CarbonThemeData>[",
                  "      CarbonThemeData.white, CarbonThemeData.gray10,",
                  "      CarbonThemeData.gray90, CarbonThemeData.gray100,",
                  "    ]) {", "      final adapted = CarbonThemeData.highContrast(base);"]
        lines += [f"      expect(adapted.{name}, base.{name});" for name in new_fields]
        lines += ["    }", "  });", "",
                  "  test('a transparent custom color can suppress a light status outline', () {",
                  "    const transparent = Color(0x00000000);",
                  "    final theme = CarbonThemeData.white.copyWith(",
                  "      statusOrangeOutline: transparent, statusYellowOutline: transparent,",
                  "    );", "    expect(theme.statusOrangeOutline, transparent);",
                  "    expect(theme.statusYellowOutline, transparent);", "  });", ""]
    lines += [
        "  test('themes carry the expected brightness', () {",
        "    expect(CarbonThemeData.white.brightness, Brightness.light);",
        "    expect(CarbonThemeData.gray10.brightness, Brightness.light);",
        "    expect(CarbonThemeData.gray90.brightness, Brightness.dark);",
        "    expect(CarbonThemeData.gray100.brightness, Brightness.dark);",
        "  });",
        "",
        "  test('themes are distinct', () {",
        "    expect(CarbonThemeData.white.background, "
        "isNot(CarbonThemeData.gray100.background));",
        "    expect(CarbonThemeData.gray90.layer01, "
        "isNot(CarbonThemeData.gray100.layer01));",
        "  });",
        "}",
        "",
    ]
    return "\n".join(lines)


HIGH_CONTRAST_FACTORY = """
  /// Derives stronger boundaries, focus indicators and inactive labels.
  ///
  /// This is Carbide's accessibility adaptation, not a fifth upstream Carbon
  /// theme. `CarbonTheme` selects it for the nearest high-contrast preference.
  /// Applications can also pass it explicitly to keep the adaptation enabled.
  ///
  /// Surfaces, brand colors, validation colors and enabled control fills remain
  /// those of [base]. Neutral secondary text and placeholders become opaque.
  /// Disabled controls retain their disabled semantics and neutral fill; their
  /// labels become readable. The dark disabled-button fill is deepened for that
  /// contrast. An opposite inset focus stroke remains available on filled
  /// controls. Custom themes must keep surfaces consistent with [brightness]
  /// and verify their own contrast pairings.
  ///
  /// Derivation is cached by base instance and is idempotent. The original
  /// [base] is never changed.
  factory CarbonThemeData.highContrast(CarbonThemeData base) {
    final cached = _highContrastCache[base];
    if (cached != null) return cached;
    final dark = base.brightness == Brightness.dark;
    final ink = dark ? CarbonColors.white : CarbonColors.black;
    final opposite = dark ? CarbonColors.black : CarbonColors.white;
    final disabled = dark ? CarbonColors.gray10 : CarbonColors.gray70;
    final result = base.copyWith(
      borderSubtle00: ink,
      borderSubtle01: ink,
      borderSubtle02: ink,
      borderSubtle03: ink,
      borderSubtleSelected01: ink,
      borderSubtleSelected02: ink,
      borderSubtleSelected03: ink,
      borderStrong01: ink,
      borderStrong02: ink,
      borderStrong03: ink,
      borderTile01: ink,
      borderTile02: ink,
      borderTile03: ink,
      borderInteractive: ink,
      borderDisabled: ink,
      borderInverse: opposite,
      layerSelectedDisabled: ink,
      focus: ink,
      focusInset: opposite,
      focusInverse: opposite,
      textSecondary: ink,
      textHelper: ink,
      textPlaceholder: ink,
      iconSecondary: ink,
      textDisabled: disabled,
      iconDisabled: disabled,
      textOnColorDisabled: disabled,
      iconOnColorDisabled: disabled,
      buttonDisabled: dark ? CarbonColors.gray70 : base.buttonDisabled,
    );
    _highContrastCache[base] = result;
    _highContrastCache[result] = result;
    return result;
  }

  static final Expando<CarbonThemeData> _highContrastCache =
      Expando<CarbonThemeData>('Carbon high-contrast themes');
"""


def main() -> None:
    order, brightness, resolved = build()
    write_generated(LIB_OUT, emit_lib(order, brightness, resolved))
    write_generated(TEST_OUT, emit_test(order, brightness, resolved))
    print(f"parsed {len(order)} semantic tokens across {len(THEMES)} themes")
    print(f"prepared {LIB_OUT.relative_to(ROOT)} and {TEST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    run_generation(main)
