#!/usr/bin/env python3
"""Generate Carbide's color tokens from the pinned Carbon source.

Reads `documentation/carbon/packages/colors/src/dtcg/colors.json` (Apache-2.0) and
emits:
  - lib/src/foundations/colors.dart   (the `CarbonColors` constants)
  - test/foundations/colors_test.dart (an exhaustive value lock)

Run from the repository root:  python3 tool/generate_carbon_colors.py
Re-run when bumping the Carbon submodule; review the diff.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from generation_check import run_generation, write_generated, remove_generated

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "documentation/carbon/packages/colors/src/dtcg/colors.json"
LIB_OUT = ROOT / "lib/src/foundations/colors.dart"
TEST_OUT = ROOT / "test/foundations/colors_test.dart"

LICENSE_HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_colors.py — do not edit by hand.
//
// Color values are ported verbatim from the Apache-2.0 licensed Carbon Design
// System (@carbon/colors). See the NOTICE file for attribution.
"""


def to_argb(hex_str: str) -> str:
    h = hex_str.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        raise ValueError(f"unexpected hex: {hex_str}")
    return "0xFF" + h.upper()


def family_of(name: str) -> str:
    return re.sub(r"(\d+)?(Hover)?$", "", name)


def doc_for(name: str, argb: str) -> str:
    """A one-line dartdoc summary for a single swatch constant."""
    hex_str = "#" + argb[len("0xFF"):]
    if name.endswith("Hover"):
        base = name[: -len("Hover")]
        return f"  /// Hover-state variant of [{base}] ({hex_str})."
    return f"  /// Carbon `{name}` swatch ({hex_str})."


def parse() -> list[tuple[str, str]]:
    entries = []

    def visit(node, path=()):
        if "$value" in node:
            name = "".join(path)
            entries.append((name, to_argb(node["$value"])))
            # Upstream js-colors.js keeps these public compatibility aliases.
            if name in ("black", "white"):
                entries.append(("black100" if name == "black" else "white0", to_argb(node["$value"])))
        for key, child in node.items():
            if not key.startswith("$") and isinstance(child, dict):
                visit(child, (*path, key))

    visit(json.loads(SRC.read_text()))
    return entries


def emit_lib(entries: list[tuple[str, str]]) -> str:
    lines = [
        LICENSE_HEADER,
        "import 'dart:ui' show Color;",
        "",
        "/// The complete Carbon color palette as immutable [Color] constants.",
        "///",
        "/// Names mirror Carbon's swatches: a family and a step from 10",
        "/// (lightest) to 100 (darkest), plus `*Hover` interaction variants —",
        "/// for example [blue60] and [blue60Hover]. These are the raw palette;",
        "/// semantic theme tokens (background, text, …) map onto them per theme.",
        "abstract final class CarbonColors {",
    ]
    current = None
    for name, argb in entries:
        fam = family_of(name)
        if fam != current:
            current = fam
            lines.append("")
            lines.append(f"  // {fam}")
        lines.append(doc_for(name, argb))
        lines.append(f"  static const Color {name} = Color({argb});")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_test(entries: list[tuple[str, str]]) -> str:
    head = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_colors.py — do not edit by hand.

import 'dart:ui';

import 'package:carbide/carbide.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('CarbonColors values match the Carbon @carbon/colors source', () {
"""
    body = []
    for name, argb in entries:
        body.append(
            f"    test('{name}', () => "
            f"expect(CarbonColors.{name}, const Color({argb})));"
        )
    fams: dict[str, list[str]] = {}
    for name, _ in entries:
        # Only the 12 chromatic/neutral families have a 10-100 ramp; black and
        # white (and their black100/white0 aliases) are single tones.
        m = re.match(r"^([a-zA-Z]+?)(\d+)$", name)
        if m and m.group(1) not in ("black", "white"):
            fams.setdefault(m.group(1), []).append(name)
    invariants = [
        "  });",
        "",
        "  test('every palette color is fully opaque', () {",
        "    const all = <Color>[",
    ]
    invariants += [f"      CarbonColors.{n}," for n, _ in entries]
    invariants += [
        "    ];",
        "    for (final color in all) {",
        "      expect((color.a * 255).round(), 255);",
        "    }",
        "  });",
        "",
        "  test('each family exposes the full 10-100 step ramp', () {",
        "    const ramps = <String, List<Color>>{",
    ]
    for fam, names in fams.items():
        steps = sorted(names, key=lambda n: int(re.match(r"^[a-zA-Z]+?(\d+)$", n).group(1)))
        joined = ", ".join(f"CarbonColors.{n}" for n in steps)
        invariants.append(f"      '{fam}': [{joined}],")
    invariants += [
        "    };",
        "    for (final ramp in ramps.values) {",
        "      expect(ramp, hasLength(10));",
        "    }",
        "  });",
        "}",
        "",
    ]
    return head + "\n".join(body) + "\n" + "\n".join(invariants)


def main() -> None:
    entries = parse()
    write_generated(LIB_OUT, emit_lib(entries))
    write_generated(TEST_OUT, emit_test(entries))
    fams = sorted({family_of(n) for n, _ in entries})
    print(f"parsed {len(entries)} colors across families: {', '.join(fams)}")
    print(f"prepared {LIB_OUT.relative_to(ROOT)} and {TEST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    run_generation(main)
