#!/usr/bin/env python3
"""Generate Carbide's type tokens from the pinned Carbon source.

Reads @carbon/type (Apache-2.0) and emits:
  - lib/src/foundations/typography.dart    (scale, weights, fixed styles)
  - test/foundations/typography_test.dart  (an exhaustive value lock)

Scope: the 23-step type scale, the three font weights, and fixed named type
styles, including expressiveHeading01/02. Responsive expressive, display and
quotation styles are generated separately by generate_carbon_fluid_type.py.

Carbon units → Flutter:
  fontSize: rem(scale[i])  -> scale[i] logical px (1rem = 16px base)
  lineHeight: <ratio>      -> TextStyle.height (unitless multiple of fontSize)
  letterSpacing: px(n)     -> n logical px
  fontWeights.x            -> FontWeight.w<n>

Run from the repository root:  python3 tool/generate_carbon_type.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TYPE_DIR = ROOT / "documentation/carbon/packages/type/src"
LIB_OUT = ROOT / "lib/src/foundations/typography.dart"
TEST_OUT = ROOT / "test/foundations/typography_test.dart"

# Fixed styles defined as objects in styles.ts, in the order we expose them.
OBJECTS = [
    "caption01", "caption02", "label01", "label02",
    "helperText01", "helperText02", "legal01", "legal02",
    "code01", "code02",
    "bodyShort01", "bodyShort02", "bodyLong01", "bodyLong02",
    "heading01", "heading02",
    "productiveHeading01", "productiveHeading02", "productiveHeading03",
    "productiveHeading04", "productiveHeading05", "productiveHeading06",
    "productiveHeading07",
    "expressiveHeading01", "expressiveHeading02",
]
# V11 fixed aliases -> the object they reference.
ALIASES = {
    "bodyCompact01": "bodyShort01",
    "bodyCompact02": "bodyShort02",
    "body01": "bodyLong01",
    "body02": "bodyLong02",
    "headingCompact01": "productiveHeading01",
    "headingCompact02": "productiveHeading02",
    "heading03": "productiveHeading03",
    "heading04": "productiveHeading04",
    "heading05": "productiveHeading05",
    "heading06": "productiveHeading06",
    "heading07": "productiveHeading07",
}

HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_type.py — do not edit by hand.
//
// Values are ported verbatim from the Apache-2.0 licensed Carbon Design System
// (@carbon/type). See the NOTICE file for attribution.
"""


def normalize_styles(text: str) -> str:
    """Normalize named v11 scale/weight exports and tree-shaking annotations."""
    text = text.replace("/*#__PURE__*/ ", "")
    text = re.sub(r"\bscale(\d{2})\b", lambda m: f"scale[{int(m[1]) - 1}]", text)
    text = re.sub(r"fontWeight: (light|regular|semibold)\b", r"fontWeight: fontWeights.\1", text)
    return re.sub(r"fontFamily: (mono|serif)\b", r"fontFamily: fontFamilies.\1", text)


def scale_steps() -> list[int]:
    text = (TYPE_DIR / "scale.ts").read_text()
    return [int(value) for value in re.findall(r"export const scale\d{2} = (\d+);", text)]


def weights() -> dict[str, int]:
    text = (TYPE_DIR / "fontWeight.ts").read_text()
    return {name: int(value) for name, value in re.findall(r"export const (light|regular|semibold) = (\d+);", text)}


def parse_objects() -> dict[str, str]:
    text = normalize_styles((TYPE_DIR / "styles.ts").read_text())
    return {
        m.group(1): m.group(2)
        for m in re.finditer(r"export const (\w+) = (\{[^{}]*\});", text)
    }


def style(raw: str, scale: list[int], wmap: dict[str, int]) -> dict[str, object]:
    fam = re.search(r"fontFamily:\s*fontFamilies\.(\w+)", raw)
    size = re.search(r"fontSize:\s*rem\(scale\[(\d+)\]\)", raw)
    weight = re.search(r"fontWeight:\s*fontWeights\.(\w+)", raw)
    height = re.search(r"lineHeight:\s*([\d.]+)", raw)
    spacing = re.search(r"letterSpacing:\s*(?:px\((-?[\d.]+)\)|(0))", raw)
    assert size and height and spacing, f"unparsed style: {raw}"
    return {
        "family": fam.group(1) if fam else "sans",
        "size": scale[int(size.group(1))],
        "weight": wmap[weight.group(1) if weight else "regular"],
        "height": height.group(1),
        "spacing": spacing.group(1) if spacing.group(1) is not None else "0",
    }


def dart_style(s: dict[str, object]) -> str:
    family = "CarbonFontFamily.mono" if s["family"] == "mono" else "CarbonFontFamily.sans"
    return (
        "TextStyle(\n"
        f"    fontFamily: {family},\n"
        f"    fontSize: {s['size']},\n"
        f"    fontWeight: FontWeight.w{s['weight']},\n"
        f"    height: {s['height']},\n"
        f"    letterSpacing: {s['spacing']},\n"
        "  )"
    )


def emit_lib(scale, wmap, styles) -> str:
    L = [
        HEADER,
        "import 'package:flutter/painting.dart' show FontWeight, TextStyle;",
        "",
        "import 'fonts.dart';",
        "",
        "/// The font weights Carbon uses.",
        "abstract final class CarbonFontWeight {",
        f"  /// Light ({wmap['light']}).",
        f"  static const FontWeight light = FontWeight.w{wmap['light']};",
        "",
        f"  /// Regular ({wmap['regular']}).",
        f"  static const FontWeight regular = FontWeight.w{wmap['regular']};",
        "",
        f"  /// SemiBold ({wmap['semibold']}).",
        f"  static const FontWeight semibold = FontWeight.w{wmap['semibold']};",
        "}",
        "",
        "/// The 23-step Carbon type scale, in logical pixels.",
        "abstract final class CarbonTypeScale {",
        "  /// The scale steps, from step 1 (index 0) to step 23.",
        "  static const List<double> steps = <double>[",
    ]
    for i in range(0, len(scale), 8):
        L.append("    " + ", ".join(str(n) for n in scale[i : i + 8]) + ",")
    L += [
        "  ];",
        "}",
        "",
        "/// The fixed (non-fluid) Carbon type styles as [TextStyle]s.",
        "///",
        "/// Each style is self-contained: it names its IBM Plex family, so it",
        "/// renders correctly without relying on an ambient default. Fluid",
        "/// (breakpoint-driven) styles are provided separately.",
        "abstract final class CarbonTypeStyles {",
    ]
    for name in OBJECTS:
        L.append(f"  /// The `{name}` type style.")
        L.append(f"  static const TextStyle {name} = {dart_style(styles[name])};")
        L.append("")
    for name, target in ALIASES.items():
        L.append(f"  /// The `{name}` type style (an alias of [{target}]).")
        L.append(f"  static const TextStyle {name} = {target};")
        L.append("")
    L.append("}")
    L.append("")
    return "\n".join(L)


def emit_test(scale, wmap, styles) -> str:
    L = [
        "// Copyright 2026 Bizjak Tech OÜ",
        "//",
        "// This file is part of Carbide and is licensed under the Apache License,",
        "// Version 2.0. See the LICENSE file in the project root.",
        "//",
        "// GENERATED by tool/generate_carbon_type.py — do not edit by hand.",
        "",
        "import 'package:carbide/carbide.dart';",
        "import 'package:flutter/painting.dart';",
        "import 'package:flutter_test/flutter_test.dart';",
        "",
        "void main() {",
        "  test('type scale matches the Carbon source', () {",
        "    expect(CarbonTypeScale.steps, <double>[",
    ]
    for i in range(0, len(scale), 8):
        L.append("      " + ", ".join(str(n) for n in scale[i : i + 8]) + ",")
    L += [
        "    ]);",
        "  });",
        "",
        "  test('font weights match the Carbon source', () {",
        f"    expect(CarbonFontWeight.light, FontWeight.w{wmap['light']});",
        f"    expect(CarbonFontWeight.regular, FontWeight.w{wmap['regular']});",
        f"    expect(CarbonFontWeight.semibold, FontWeight.w{wmap['semibold']});",
        "  });",
        "",
        "  test('fixed type styles match the Carbon source', () {",
    ]
    for name in OBJECTS:
        L.append(f"    expect(CarbonTypeStyles.{name}, const {dart_style(styles[name])});")
    for name, target in ALIASES.items():
        L.append(f"    expect(CarbonTypeStyles.{name}, CarbonTypeStyles.{target});")
    L += [
        "  });",
        "",
        "  test('every style names a bundled Plex family', () {",
        "    const families = <String>{CarbonFontFamily.sans, CarbonFontFamily.mono};",
        "    for (final TextStyle style in <TextStyle>[",
    ]
    for name in OBJECTS:
        L.append(f"      CarbonTypeStyles.{name},")
    L += [
        "    ]) {",
        "      expect(families, contains(style.fontFamily));",
        "      expect(style.fontSize, greaterThan(0));",
        "    }",
        "  });",
        "}",
        "",
    ]
    return "\n".join(L)


def main() -> None:
    scale = scale_steps()
    wmap = weights()
    objects = parse_objects()
    styles = {name: style(objects[name], scale, wmap) for name in OBJECTS}
    LIB_OUT.write_text(emit_lib(scale, wmap, styles))
    TEST_OUT.write_text(emit_test(scale, wmap, styles))
    print(f"scale: {len(scale)} steps; weights: {wmap}")
    print(f"fixed styles: {len(OBJECTS)} objects + {len(ALIASES)} aliases")
    print(f"wrote {LIB_OUT.relative_to(ROOT)} and {TEST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
