#!/usr/bin/env python3
"""Derive the documented platform verification from the actual CI conventions.

This is a focused reader of this repository's job/run structure, not a general
YAML parser. Changed orchestration that cannot be classified fails for review.
"""
import argparse
import json
from pathlib import Path
import re
from gallery_coverage import catalog
from sdk_floor import read_floor

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'docs/platform-support.md'


def job(source, name):
    match = re.search(rf'^  {re.escape(name)}:\s*\n([\s\S]*?)(?=^  [\w-]+:|\Z)', source, re.M)
    if not match:
        raise ValueError(f'Missing documented verification job {name}')
    return match[1]


def run_commands(source):
    lines = source.splitlines()
    result = []
    for i, line in enumerate(lines):
        match = re.match(r'^( *)(?:- )?run:\s*(.*)$', line)
        if not match:
            continue
        indent, value = len(match[1]), match[2]
        if value in {'|', '>'}:
            block = []
            for following in lines[i + 1:]:
                if following.strip() and len(following) - len(following.lstrip()) <= indent:
                    break
                block.append(following.strip())
            result.append('\n'.join(block))
        else:
            result.append(value)
    return result


def classify(ci, verify, gallery, canary):
    if not re.search(r'^  pull_request:\s*$', ci, re.M) or 'uses: ./.github/workflows/verify.yaml' not in job(ci, 'verify'):
        raise ValueError('PR verification orchestration changed; review platform claims')
    root = job(verify, 'analyze-and-test')
    if 'runs-on: ubuntu-latest' not in root or 'flutter test --coverage' not in run_commands(root):
        raise ValueError('Linux authoritative PR suite is no longer configured')
    if 'python3 tool/run_pr_chrome.py' not in run_commands(job(verify, 'chrome')):
        raise ValueError('Explicit PR Chrome suite runner changed')
    if 'uses: ./.github/workflows/gallery-web.yaml' not in job(verify, 'gallery-web'):
        raise ValueError('Shared native gallery browser gate changed')
    minimum = job(verify, 'minimum-sdk')
    if not re.search(r'flutter-version:\s*\$\{\{ steps\.floor\.outputs\.flutter \}\}', minimum):
        raise ValueError('Minimum SDK is no longer installed from package floors')
    if sum(command.splitlines().count('flutter test') for command in run_commands(minimum)) != 2:
        raise ValueError('Both independent packages must be tested at the minimum SDK')
    if 'working-directory: example' not in minimum:
        raise ValueError('Minimum SDK gallery package coverage missing')
    matrix = re.search(r'os:\s*\[([^\]]+)\]', job(canary, 'desktop'))
    if not matrix:
        raise ValueError('Cannot classify host canary matrix')
    hosts = [value.strip() for value in matrix[1].split(',')]
    if set(hosts) != {'macos-latest', 'windows-latest'}:
        raise ValueError('Host canary platform set changed; review matrix rows')
    schedule = re.search(r'cron:\s*"([^"]+)"', canary)
    if not schedule:
        raise ValueError('Missing canary schedule')
    commands = run_commands(gallery)
    targets = re.findall(r'--target=(integration_test/[\w/]+\.dart)', '\n'.join(commands))
    if 'integration_test/gallery_smoke_test.dart' not in targets or 'integration_test/font_resolution_test.dart' not in targets:
        raise ValueError('Native routes or consuming font verification removed')
    if not any(re.match(r'^flutter build web\b.*--wasm\b', command) for command in commands):
        raise ValueError('Deployed WASM configuration is no longer built by verification')
    groups = re.search(r'group:\s*\[([^\]]+)\]', job(canary, 'gallery-web-integration'))
    if not groups:
        raise ValueError('Cannot classify native browser canary groups')
    return {'hosts': hosts, 'schedule': schedule[1], 'nativeTargets': targets,
            'groups': [value.strip() for value in groups[1].split(',')]}


def facts(root=ROOT):
    workflows = root / '.github/workflows'
    data = classify(*[(workflows / name).read_text() for name in [
        'ci.yaml', 'verify.yaml', 'gallery-web.yaml', 'os-matrix.yaml']])
    data['floor'] = read_floor((root / 'pubspec.yaml').read_text())
    if data['floor'] != read_floor((root / 'example/pubspec.yaml').read_text()):
        raise ValueError('Root and gallery SDK floors differ')
    data['chromeSuites'] = len(json.loads((root / 'tool/pr_chrome_suites.json').read_text())['suites'])
    data['routes'] = len(catalog(root))
    return data


def render(data):
    return f'''# Platform support and verification

<!-- Generated by tool/platform_support.py from workflows, package floors and catalog. -->

Carbide targets Flutter's Android, iOS, web, Linux, macOS and Windows platforms.
The library uses base widgets/SDK rendering and no Material or Cupertino.
Platform intent and actual execution evidence are separate: host widget tests
are not proof that a native application bundle, device, screen reader or
platform file adapter was exercised.

| Platform | PR verification | Additional canary | Native application/device evidence |
| --- | --- | --- | --- |
| Linux | Full VM suite, coverage and strict authoritative goldens on ubuntu-latest | Native web contracts also run on Ubuntu | Headless test engine; gallery has no Linux desktop runner |
| Web | {data['chromeSuites']} explicitly selected Chrome widget suites; real-browser sweep of {data['routes']} gallery routes; native copy/popover/font contracts; WASM build | Broader Chrome suites plus {len(data['groups'])} native browser groups | Actual Chromium browser; no Safari/Firefox execution claim |
| macOS | Shared contracts execute on the Linux/Chrome PR gates | Full VM suite on macos-latest | Host widget engine, not a built macOS application |
| Windows | Shared contracts execute on the Linux/Chrome PR gates | Full VM suite on windows-latest | Host widget engine, not a built Windows application |
| Android | Shared contracts and touch/target policies execute through VM/browser tests | No native Android device job | No Android device/emulator execution claim |
| iOS | Shared contracts and target policies execute through VM/browser tests | No native iOS device job | No iOS device/simulator execution claim |

PR, deployment, publication and rehearsal reuse the complete verification graph.
Both independent packages are analyzed/tested at their declared minimum Flutter
{data['floor']['flutter']} / Dart {data['floor']['sdk']}; latest stable is checked separately.
The host/browser canary is scheduled with UTC cron `{data['schedule']}` and can
be dispatched manually. Editing its workflow also triggers it on that PR.
A scheduled canary passing does not mean every PR executed native desktop or
mobile apps.

## Fonts and golden authority

Linux VM images are authoritative. VM tests load the bundled Plex fonts;
macOS/Windows text comparisons permit rasterization differences and do not
replace Linux review. Regenerate committed images with the Linux workflow.
Chrome widget tests deliberately use placeholder fonts and skip pixel comparisons.
They execute behavior, not consumer font resolution or web golden fidelity.

The native consuming-app font contract reads FontManifest and independently
checks Sans/Mono/Serif rendered advances against the bundled TTFs, without a
FontLoader. Built-in styles qualify only their Plex family; application fallback
fonts keep their own names. Additional script coverage belongs to the application's
font choices. See [font resolution](testing/font-resolution.md).

The deployed build includes WASM and JavaScript outputs. Compatible browsers
can run single-threaded skwasm without cross-origin isolation; COOP/COEP allows
multi-threading. Browser capability controls fallback. Manual Chromium review
observed single-threaded skwasm; this is not a Safari/Firefox renderer validation.
See [Flutter's current WASM guidance](https://docs.flutter.dev/platform-integration/web/wasm).

## Pointer, touch and keyboard

Controls support their documented Tab/Shift+Tab order, Enter/Space activation,
control-specific arrows, Home/End and typeahead. Horizontal navigation follows
RTL where appropriate. Menus and overlays define Escape/return-focus behavior;
native browser contracts check Dart focus, DOM focus and action geometry.

ContextMenu opens from a secondary pointer press, a long press, or a scoped
Context Menu key / Shift+F10 while its target owns focus. Desktop conventions
are not evidence of a mobile keyboard. A long press is the touch alternative;
applications should retain another discoverable action when appropriate.
The source and widget/native contracts cover these routes; platform-native
screen-reader gestures and hardware combinations still need host-app validation.

## Target-size policy

Flutter's test guidelines require 48×48 logical pixels for Android and 44×44 for
iOS ([SDK source](https://github.com/flutter/flutter/blob/3.47.6/packages/flutter_test/lib/src/accessibility.dart)).
Carbide's interactive family tests use the stricter Android guideline for full
controls. Compact Carbon sizes can be below it: reviewed axis overrides name
the pinned Carbon specification beside the test. They are intentional density
choices, not a claim that all sm controls meet a mobile target guideline.

Choose comfortable sizes for touch and check the application's actual semantic
hit regions. The [accessibility inventory](../tool/accessibility_inventory.json)
records families, states and composition exemptions; the adjacent test
overrides cite compact geometry. A
waiver for one family/axis does not exempt unrelated controls or prove native
Android/iOS assistive-technology behavior.

## High contrast and localization

High contrast is implemented through CarbonThemeData.highContrast and the
nearest MediaQuery.highContrast preference, including live updates and local
overrides. Shared tests/native browser preferences exercise this adaptation;
there is no native Windows/macOS screen-reader or OS-setting execution claim.
Custom content must still use suitable tokens and semantic labels.

Date/time policies, pagination formatters, control labels and read-only/active
option announcements expose localization inputs. RTL/scaling and localized
calendar contracts are tested. This is partial package localization: English
default strings remain, and Carbide does not provide a package-wide translation
catalog or automatic application locale management. Applications supply their
labels/formatters and fonts for the scripts they ship.

## Checked workflow sources

The generator reads the PR/shared verification, gallery browser and OS matrix
workflows, package floors and gallery catalog. It fails when their orchestration
cannot support these claims. Update it and run `python3 tool/platform_support.py`
when changing coverage; CI checks the generated document with `--check`.
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = render(facts())
    if args.check:
        if not REPORT.is_file() or REPORT.read_text() != generated:
            raise SystemExit('Stale platform matrix: run python3 tool/platform_support.py')
    else: REPORT.write_text(generated)
    print('Platform matrix matches PR, canary, gallery, SDK and catalog configuration.')

if __name__ == '__main__': main()
