#!/usr/bin/env python3
"""Spike #29: extract representative Carbon icons and upstream references.

Parses a feature-exercising sample of Carbon icon/pictogram SVGs into shape
data, emits a Dart test fixture, and rasterizes the *upstream SVGs* with
rsvg-convert into reference PNGs. The Dart spike test then renders the
extracted data via dart:ui and compares it pixel-wise against those
references — establishing the empirical fidelity numbers for the icon
rendering ADR.

Run from the repository root:  python3 tool/spike_icon_fidelity.py
Requires rsvg-convert (librsvg) for reference rasterization.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from carbon_svg import IDENTITY, extract, fnum

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "documentation/carbon/packages/icons/src/svg"
PICTOS = ROOT / "documentation/carbon/packages/pictograms/src/svg"
FIXTURE = ROOT / "test/spike/spike_icon_data.dart"
REF_DIR = ROOT / "test/spike/references"

# (logical name, source file, render sizes). Chosen to exercise: polygons,
# bespoke 16px artwork, invisible-element normalization, evenodd fill rule,
# real rotate transforms, namespaces (watson-health, Q), circles, pictograms.
# Icons get the Carbon sizes (16/20/24/32) plus 64 (2x); pictograms render at
# native size and up only (their display sizes are 48px+, never 16).
ICON_SIZES = [16, 20, 24, 32, 64]
ASSETS = [
    ("add", ICONS / "32/add.svg", ICON_SIZES),
    ("apps_16", ICONS / "16/apps.svg", [16, 32]),
    ("apps_32", ICONS / "32/apps.svg", ICON_SIZES),
    ("arrow_down_16", ICONS / "16/arrow--down.svg", [16, 32]),
    ("arrow_down_32", ICONS / "32/arrow--down.svg", ICON_SIZES),
    ("misuse", ICONS / "32/misuse.svg", ICON_SIZES),
    ("logo_wechat", ICONS / "32/logo--wechat.svg", ICON_SIZES),
    ("airport_location", ICONS / "32/airport-location.svg", ICON_SIZES),
    ("wh_3d_cursor_alt", ICONS / "32/watson-health/3D-cursor--alt.svg", ICON_SIZES),
    ("q_bloch_sphere", ICONS / "32/Q/bloch-sphere.svg", ICON_SIZES),
    ("accessibility_alt", ICONS / "32/accessibility--alt.svg", ICON_SIZES),
    ("picto_solar_panel", PICTOS / "solar--panel.svg", [32, 64, 128]),
]

# Render sizes per artwork: native, 2x native; for 32px masters also 16
# (the downscale path CarbonIcon will take) and 64 covers 2x.
def emit_dart(extracted) -> str:
    lines = [
        "// Copyright 2026 Bizjak Tech OÜ",
        "//",
        "// This file is part of Carbide and is licensed under the Apache License,",
        "// Version 2.0. See the LICENSE file in the project root.",
        "//",
        "// GENERATED by tool/spike_icon_fidelity.py — do not edit by hand.",
        "// Shape data extracted from the Apache-2.0 licensed Carbon Design",
        "// System icon sources; see NOTICE.",
        "",
        "import 'support.dart';",
        "",
        "/// The representative icon sample for the rendering spike.",
        "const List<SpikeIcon> spikeIcons = <SpikeIcon>[",
    ]
    for name, viewbox, sizes, shapes in extracted:
        lines.append("  SpikeIcon(")
        lines.append(f"    name: '{name}',")
        lines.append(f"    viewBox: {fnum(viewbox)},")
        lines.append(f"    renderSizes: <int>[{', '.join(map(str, sizes))}],")
        lines.append("    shapes: <SpikeShape>[")
        for d, evenodd, matrix in shapes:
            lines.append("      SpikeShape(")
            lines.append(f"        d: '{d}',")
            if evenodd:
                lines.append("        evenOdd: true,")
            if matrix != IDENTITY:
                values = ", ".join(fnum(v) for v in matrix)
                lines.append(f"        matrix: <double>[{values}],")
            lines.append("      ),")
        lines.append("    ],")
        lines.append("  ),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    REF_DIR.mkdir(parents=True, exist_ok=True)
    extracted = []
    for name, svg_file, sizes in ASSETS:
        viewbox, viewbox_h, shapes = extract(svg_file)
        assert viewbox == viewbox_h, f"spike assets must be square: {svg_file}"
        extracted.append((name, viewbox, sizes, shapes))
        for size in sizes:
            out = REF_DIR / f"{name}_{size}.png"
            subprocess.run(
                [
                    "rsvg-convert",
                    "-w", str(size),
                    "-h", str(size),
                    str(svg_file),
                    "-o", str(out),
                ],
                check=True,
            )
        print(f"{name}: {len(shapes)} shapes, sizes {sizes}")
    FIXTURE.write_text(emit_dart(extracted))
    print(f"wrote {FIXTURE.relative_to(ROOT)} and {len(list(REF_DIR.iterdir()))} references")


if __name__ == "__main__":
    main()
