// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_colors.py — do not edit by hand.

import 'dart:ui';

import 'package:carbide/carbide.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('CarbonColors values match the Carbon @carbon/colors source', () {
    test('black', () => expect(CarbonColors.black, const Color(0xFF000000)));
    test(
      'black100',
      () => expect(CarbonColors.black100, const Color(0xFF000000)),
    );
    test(
      'blackHover',
      () => expect(CarbonColors.blackHover, const Color(0xFF212121)),
    );
    test('white', () => expect(CarbonColors.white, const Color(0xFFFFFFFF)));
    test('white0', () => expect(CarbonColors.white0, const Color(0xFFFFFFFF)));
    test(
      'whiteHover',
      () => expect(CarbonColors.whiteHover, const Color(0xFFE8E8E8)),
    );
    test(
      'yellow10',
      () => expect(CarbonColors.yellow10, const Color(0xFFFCF4D6)),
    );
    test(
      'yellow20',
      () => expect(CarbonColors.yellow20, const Color(0xFFFDDC69)),
    );
    test(
      'yellow30',
      () => expect(CarbonColors.yellow30, const Color(0xFFF1C21B)),
    );
    test(
      'yellow40',
      () => expect(CarbonColors.yellow40, const Color(0xFFD2A106)),
    );
    test(
      'yellow50',
      () => expect(CarbonColors.yellow50, const Color(0xFFB28600)),
    );
    test(
      'yellow60',
      () => expect(CarbonColors.yellow60, const Color(0xFF8E6A00)),
    );
    test(
      'yellow70',
      () => expect(CarbonColors.yellow70, const Color(0xFF684E00)),
    );
    test(
      'yellow80',
      () => expect(CarbonColors.yellow80, const Color(0xFF483700)),
    );
    test(
      'yellow90',
      () => expect(CarbonColors.yellow90, const Color(0xFF302400)),
    );
    test(
      'yellow100',
      () => expect(CarbonColors.yellow100, const Color(0xFF1C1500)),
    );
    test(
      'yellow10Hover',
      () => expect(CarbonColors.yellow10Hover, const Color(0xFFF8E6A0)),
    );
    test(
      'yellow20Hover',
      () => expect(CarbonColors.yellow20Hover, const Color(0xFFFCCD27)),
    );
    test(
      'yellow30Hover',
      () => expect(CarbonColors.yellow30Hover, const Color(0xFFDDB00E)),
    );
    test(
      'yellow40Hover',
      () => expect(CarbonColors.yellow40Hover, const Color(0xFFBC9005)),
    );
    test(
      'yellow50Hover',
      () => expect(CarbonColors.yellow50Hover, const Color(0xFF9E7700)),
    );
    test(
      'yellow60Hover',
      () => expect(CarbonColors.yellow60Hover, const Color(0xFF755800)),
    );
    test(
      'yellow70Hover',
      () => expect(CarbonColors.yellow70Hover, const Color(0xFF806000)),
    );
    test(
      'yellow80Hover',
      () => expect(CarbonColors.yellow80Hover, const Color(0xFF5C4600)),
    );
    test(
      'yellow90Hover',
      () => expect(CarbonColors.yellow90Hover, const Color(0xFF3D2E00)),
    );
    test(
      'yellow100Hover',
      () => expect(CarbonColors.yellow100Hover, const Color(0xFF332600)),
    );
    test(
      'orange10',
      () => expect(CarbonColors.orange10, const Color(0xFFFFF2E8)),
    );
    test(
      'orange20',
      () => expect(CarbonColors.orange20, const Color(0xFFFFD9BE)),
    );
    test(
      'orange30',
      () => expect(CarbonColors.orange30, const Color(0xFFFFB784)),
    );
    test(
      'orange40',
      () => expect(CarbonColors.orange40, const Color(0xFFFF832B)),
    );
    test(
      'orange50',
      () => expect(CarbonColors.orange50, const Color(0xFFEB6200)),
    );
    test(
      'orange60',
      () => expect(CarbonColors.orange60, const Color(0xFFBA4E00)),
    );
    test(
      'orange70',
      () => expect(CarbonColors.orange70, const Color(0xFF8A3800)),
    );
    test(
      'orange80',
      () => expect(CarbonColors.orange80, const Color(0xFF5E2900)),
    );
    test(
      'orange90',
      () => expect(CarbonColors.orange90, const Color(0xFF3E1A00)),
    );
    test(
      'orange100',
      () => expect(CarbonColors.orange100, const Color(0xFF231000)),
    );
    test(
      'orange10Hover',
      () => expect(CarbonColors.orange10Hover, const Color(0xFFFFE2CC)),
    );
    test(
      'orange20Hover',
      () => expect(CarbonColors.orange20Hover, const Color(0xFFFFC69E)),
    );
    test(
      'orange30Hover',
      () => expect(CarbonColors.orange30Hover, const Color(0xFFFF9D57)),
    );
    test(
      'orange40Hover',
      () => expect(CarbonColors.orange40Hover, const Color(0xFFFA6800)),
    );
    test(
      'orange50Hover',
      () => expect(CarbonColors.orange50Hover, const Color(0xFFCC5500)),
    );
    test(
      'orange60Hover',
      () => expect(CarbonColors.orange60Hover, const Color(0xFF9E4200)),
    );
    test(
      'orange70Hover',
      () => expect(CarbonColors.orange70Hover, const Color(0xFFA84400)),
    );
    test(
      'orange80Hover',
      () => expect(CarbonColors.orange80Hover, const Color(0xFF753300)),
    );
    test(
      'orange90Hover',
      () => expect(CarbonColors.orange90Hover, const Color(0xFF522200)),
    );
    test(
      'orange100Hover',
      () => expect(CarbonColors.orange100Hover, const Color(0xFF421E00)),
    );
    test('red10', () => expect(CarbonColors.red10, const Color(0xFFFFF1F1)));
    test('red20', () => expect(CarbonColors.red20, const Color(0xFFFFD7D9)));
    test('red30', () => expect(CarbonColors.red30, const Color(0xFFFFB3B8)));
    test('red40', () => expect(CarbonColors.red40, const Color(0xFFFF8389)));
    test('red50', () => expect(CarbonColors.red50, const Color(0xFFFA4D56)));
    test('red60', () => expect(CarbonColors.red60, const Color(0xFFDA1E28)));
    test('red70', () => expect(CarbonColors.red70, const Color(0xFFA2191F)));
    test('red80', () => expect(CarbonColors.red80, const Color(0xFF750E13)));
    test('red90', () => expect(CarbonColors.red90, const Color(0xFF520408)));
    test('red100', () => expect(CarbonColors.red100, const Color(0xFF2D0709)));
    test(
      'red100Hover',
      () => expect(CarbonColors.red100Hover, const Color(0xFF540D11)),
    );
    test(
      'red90Hover',
      () => expect(CarbonColors.red90Hover, const Color(0xFF66050A)),
    );
    test(
      'red80Hover',
      () => expect(CarbonColors.red80Hover, const Color(0xFF921118)),
    );
    test(
      'red70Hover',
      () => expect(CarbonColors.red70Hover, const Color(0xFFC21E25)),
    );
    test(
      'red60Hover',
      () => expect(CarbonColors.red60Hover, const Color(0xFFB81922)),
    );
    test(
      'red50Hover',
      () => expect(CarbonColors.red50Hover, const Color(0xFFEE0713)),
    );
    test(
      'red40Hover',
      () => expect(CarbonColors.red40Hover, const Color(0xFFFF6168)),
    );
    test(
      'red30Hover',
      () => expect(CarbonColors.red30Hover, const Color(0xFFFF99A0)),
    );
    test(
      'red20Hover',
      () => expect(CarbonColors.red20Hover, const Color(0xFFFFC2C5)),
    );
    test(
      'red10Hover',
      () => expect(CarbonColors.red10Hover, const Color(0xFFFFE0E0)),
    );
    test(
      'magenta10',
      () => expect(CarbonColors.magenta10, const Color(0xFFFFF0F7)),
    );
    test(
      'magenta20',
      () => expect(CarbonColors.magenta20, const Color(0xFFFFD6E8)),
    );
    test(
      'magenta30',
      () => expect(CarbonColors.magenta30, const Color(0xFFFFAFD2)),
    );
    test(
      'magenta40',
      () => expect(CarbonColors.magenta40, const Color(0xFFFF7EB6)),
    );
    test(
      'magenta50',
      () => expect(CarbonColors.magenta50, const Color(0xFFEE5396)),
    );
    test(
      'magenta60',
      () => expect(CarbonColors.magenta60, const Color(0xFFD02670)),
    );
    test(
      'magenta70',
      () => expect(CarbonColors.magenta70, const Color(0xFF9F1853)),
    );
    test(
      'magenta80',
      () => expect(CarbonColors.magenta80, const Color(0xFF740937)),
    );
    test(
      'magenta90',
      () => expect(CarbonColors.magenta90, const Color(0xFF510224)),
    );
    test(
      'magenta100',
      () => expect(CarbonColors.magenta100, const Color(0xFF2A0A18)),
    );
    test(
      'magenta100Hover',
      () => expect(CarbonColors.magenta100Hover, const Color(0xFF53142F)),
    );
    test(
      'magenta90Hover',
      () => expect(CarbonColors.magenta90Hover, const Color(0xFF68032E)),
    );
    test(
      'magenta80Hover',
      () => expect(CarbonColors.magenta80Hover, const Color(0xFF8E0B43)),
    );
    test(
      'magenta70Hover',
      () => expect(CarbonColors.magenta70Hover, const Color(0xFFBF1D63)),
    );
    test(
      'magenta60Hover',
      () => expect(CarbonColors.magenta60Hover, const Color(0xFFB0215F)),
    );
    test(
      'magenta50Hover',
      () => expect(CarbonColors.magenta50Hover, const Color(0xFFE3176F)),
    );
    test(
      'magenta40Hover',
      () => expect(CarbonColors.magenta40Hover, const Color(0xFFFF57A0)),
    );
    test(
      'magenta30Hover',
      () => expect(CarbonColors.magenta30Hover, const Color(0xFFFF94C3)),
    );
    test(
      'magenta20Hover',
      () => expect(CarbonColors.magenta20Hover, const Color(0xFFFFBDDA)),
    );
    test(
      'magenta10Hover',
      () => expect(CarbonColors.magenta10Hover, const Color(0xFFFFE0EF)),
    );
    test(
      'purple10',
      () => expect(CarbonColors.purple10, const Color(0xFFF6F2FF)),
    );
    test(
      'purple20',
      () => expect(CarbonColors.purple20, const Color(0xFFE8DAFF)),
    );
    test(
      'purple30',
      () => expect(CarbonColors.purple30, const Color(0xFFD4BBFF)),
    );
    test(
      'purple40',
      () => expect(CarbonColors.purple40, const Color(0xFFBE95FF)),
    );
    test(
      'purple50',
      () => expect(CarbonColors.purple50, const Color(0xFFA56EFF)),
    );
    test(
      'purple60',
      () => expect(CarbonColors.purple60, const Color(0xFF8A3FFC)),
    );
    test(
      'purple70',
      () => expect(CarbonColors.purple70, const Color(0xFF6929C4)),
    );
    test(
      'purple80',
      () => expect(CarbonColors.purple80, const Color(0xFF491D8B)),
    );
    test(
      'purple90',
      () => expect(CarbonColors.purple90, const Color(0xFF31135E)),
    );
    test(
      'purple100',
      () => expect(CarbonColors.purple100, const Color(0xFF1C0F30)),
    );
    test(
      'purple100Hover',
      () => expect(CarbonColors.purple100Hover, const Color(0xFF341C59)),
    );
    test(
      'purple90Hover',
      () => expect(CarbonColors.purple90Hover, const Color(0xFF40197B)),
    );
    test(
      'purple80Hover',
      () => expect(CarbonColors.purple80Hover, const Color(0xFF5B24AD)),
    );
    test(
      'purple70Hover',
      () => expect(CarbonColors.purple70Hover, const Color(0xFF7C3DD6)),
    );
    test(
      'purple60Hover',
      () => expect(CarbonColors.purple60Hover, const Color(0xFF7822FB)),
    );
    test(
      'purple50Hover',
      () => expect(CarbonColors.purple50Hover, const Color(0xFF9352FF)),
    );
    test(
      'purple40Hover',
      () => expect(CarbonColors.purple40Hover, const Color(0xFFAE7AFF)),
    );
    test(
      'purple30Hover',
      () => expect(CarbonColors.purple30Hover, const Color(0xFFC5A3FF)),
    );
    test(
      'purple20Hover',
      () => expect(CarbonColors.purple20Hover, const Color(0xFFDCC7FF)),
    );
    test(
      'purple10Hover',
      () => expect(CarbonColors.purple10Hover, const Color(0xFFEDE5FF)),
    );
    test('blue10', () => expect(CarbonColors.blue10, const Color(0xFFEDF5FF)));
    test('blue20', () => expect(CarbonColors.blue20, const Color(0xFFD0E2FF)));
    test('blue30', () => expect(CarbonColors.blue30, const Color(0xFFA6C8FF)));
    test('blue40', () => expect(CarbonColors.blue40, const Color(0xFF78A9FF)));
    test('blue50', () => expect(CarbonColors.blue50, const Color(0xFF4589FF)));
    test('blue60', () => expect(CarbonColors.blue60, const Color(0xFF0F62FE)));
    test('blue70', () => expect(CarbonColors.blue70, const Color(0xFF0043CE)));
    test('blue80', () => expect(CarbonColors.blue80, const Color(0xFF002D9C)));
    test('blue90', () => expect(CarbonColors.blue90, const Color(0xFF001D6C)));
    test(
      'blue100',
      () => expect(CarbonColors.blue100, const Color(0xFF001141)),
    );
    test(
      'blue100Hover',
      () => expect(CarbonColors.blue100Hover, const Color(0xFF001F75)),
    );
    test(
      'blue90Hover',
      () => expect(CarbonColors.blue90Hover, const Color(0xFF00258A)),
    );
    test(
      'blue80Hover',
      () => expect(CarbonColors.blue80Hover, const Color(0xFF0039C7)),
    );
    test(
      'blue70Hover',
      () => expect(CarbonColors.blue70Hover, const Color(0xFF0053FF)),
    );
    test(
      'blue60Hover',
      () => expect(CarbonColors.blue60Hover, const Color(0xFF0050E6)),
    );
    test(
      'blue50Hover',
      () => expect(CarbonColors.blue50Hover, const Color(0xFF1F70FF)),
    );
    test(
      'blue40Hover',
      () => expect(CarbonColors.blue40Hover, const Color(0xFF5C97FF)),
    );
    test(
      'blue30Hover',
      () => expect(CarbonColors.blue30Hover, const Color(0xFF8AB6FF)),
    );
    test(
      'blue20Hover',
      () => expect(CarbonColors.blue20Hover, const Color(0xFFB8D3FF)),
    );
    test(
      'blue10Hover',
      () => expect(CarbonColors.blue10Hover, const Color(0xFFDBEBFF)),
    );
    test('cyan10', () => expect(CarbonColors.cyan10, const Color(0xFFE5F6FF)));
    test('cyan20', () => expect(CarbonColors.cyan20, const Color(0xFFBAE6FF)));
    test('cyan30', () => expect(CarbonColors.cyan30, const Color(0xFF82CFFF)));
    test('cyan40', () => expect(CarbonColors.cyan40, const Color(0xFF33B1FF)));
    test('cyan50', () => expect(CarbonColors.cyan50, const Color(0xFF1192E8)));
    test('cyan60', () => expect(CarbonColors.cyan60, const Color(0xFF0072C3)));
    test('cyan70', () => expect(CarbonColors.cyan70, const Color(0xFF00539A)));
    test('cyan80', () => expect(CarbonColors.cyan80, const Color(0xFF003A6D)));
    test('cyan90', () => expect(CarbonColors.cyan90, const Color(0xFF012749)));
    test(
      'cyan100',
      () => expect(CarbonColors.cyan100, const Color(0xFF061727)),
    );
    test(
      'cyan10Hover',
      () => expect(CarbonColors.cyan10Hover, const Color(0xFFCCEEFF)),
    );
    test(
      'cyan20Hover',
      () => expect(CarbonColors.cyan20Hover, const Color(0xFF99DAFF)),
    );
    test(
      'cyan30Hover',
      () => expect(CarbonColors.cyan30Hover, const Color(0xFF57BEFF)),
    );
    test(
      'cyan40Hover',
      () => expect(CarbonColors.cyan40Hover, const Color(0xFF059FFF)),
    );
    test(
      'cyan50Hover',
      () => expect(CarbonColors.cyan50Hover, const Color(0xFF0F7EC8)),
    );
    test(
      'cyan60Hover',
      () => expect(CarbonColors.cyan60Hover, const Color(0xFF005FA3)),
    );
    test(
      'cyan70Hover',
      () => expect(CarbonColors.cyan70Hover, const Color(0xFF0066BD)),
    );
    test(
      'cyan80Hover',
      () => expect(CarbonColors.cyan80Hover, const Color(0xFF00498A)),
    );
    test(
      'cyan90Hover',
      () => expect(CarbonColors.cyan90Hover, const Color(0xFF013360)),
    );
    test(
      'cyan100Hover',
      () => expect(CarbonColors.cyan100Hover, const Color(0xFF0B2947)),
    );
    test('teal10', () => expect(CarbonColors.teal10, const Color(0xFFD9FBFB)));
    test('teal20', () => expect(CarbonColors.teal20, const Color(0xFF9EF0F0)));
    test('teal30', () => expect(CarbonColors.teal30, const Color(0xFF3DDBD9)));
    test('teal40', () => expect(CarbonColors.teal40, const Color(0xFF08BDBA)));
    test('teal50', () => expect(CarbonColors.teal50, const Color(0xFF009D9A)));
    test('teal60', () => expect(CarbonColors.teal60, const Color(0xFF007D79)));
    test('teal70', () => expect(CarbonColors.teal70, const Color(0xFF005D5D)));
    test('teal80', () => expect(CarbonColors.teal80, const Color(0xFF004144)));
    test('teal90', () => expect(CarbonColors.teal90, const Color(0xFF022B30)));
    test(
      'teal100',
      () => expect(CarbonColors.teal100, const Color(0xFF081A1C)),
    );
    test(
      'teal10Hover',
      () => expect(CarbonColors.teal10Hover, const Color(0xFFACF6F6)),
    );
    test(
      'teal20Hover',
      () => expect(CarbonColors.teal20Hover, const Color(0xFF57E5E5)),
    );
    test(
      'teal30Hover',
      () => expect(CarbonColors.teal30Hover, const Color(0xFF25CAC8)),
    );
    test(
      'teal40Hover',
      () => expect(CarbonColors.teal40Hover, const Color(0xFF07ABA9)),
    );
    test(
      'teal50Hover',
      () => expect(CarbonColors.teal50Hover, const Color(0xFF008A87)),
    );
    test(
      'teal60Hover',
      () => expect(CarbonColors.teal60Hover, const Color(0xFF006B68)),
    );
    test(
      'teal70Hover',
      () => expect(CarbonColors.teal70Hover, const Color(0xFF007070)),
    );
    test(
      'teal80Hover',
      () => expect(CarbonColors.teal80Hover, const Color(0xFF005357)),
    );
    test(
      'teal90Hover',
      () => expect(CarbonColors.teal90Hover, const Color(0xFF033940)),
    );
    test(
      'teal100Hover',
      () => expect(CarbonColors.teal100Hover, const Color(0xFF0F3034)),
    );
    test(
      'green10',
      () => expect(CarbonColors.green10, const Color(0xFFDEFBE6)),
    );
    test(
      'green20',
      () => expect(CarbonColors.green20, const Color(0xFFA7F0BA)),
    );
    test(
      'green30',
      () => expect(CarbonColors.green30, const Color(0xFF6FDC8C)),
    );
    test(
      'green40',
      () => expect(CarbonColors.green40, const Color(0xFF42BE65)),
    );
    test(
      'green50',
      () => expect(CarbonColors.green50, const Color(0xFF24A148)),
    );
    test(
      'green60',
      () => expect(CarbonColors.green60, const Color(0xFF198038)),
    );
    test(
      'green70',
      () => expect(CarbonColors.green70, const Color(0xFF0E6027)),
    );
    test(
      'green80',
      () => expect(CarbonColors.green80, const Color(0xFF044317)),
    );
    test(
      'green90',
      () => expect(CarbonColors.green90, const Color(0xFF022D0D)),
    );
    test(
      'green100',
      () => expect(CarbonColors.green100, const Color(0xFF071908)),
    );
    test(
      'green10Hover',
      () => expect(CarbonColors.green10Hover, const Color(0xFFB6F6C8)),
    );
    test(
      'green20Hover',
      () => expect(CarbonColors.green20Hover, const Color(0xFF74E792)),
    );
    test(
      'green30Hover',
      () => expect(CarbonColors.green30Hover, const Color(0xFF36CE5E)),
    );
    test(
      'green40Hover',
      () => expect(CarbonColors.green40Hover, const Color(0xFF3BAB5A)),
    );
    test(
      'green50Hover',
      () => expect(CarbonColors.green50Hover, const Color(0xFF208E3F)),
    );
    test(
      'green60Hover',
      () => expect(CarbonColors.green60Hover, const Color(0xFF166F31)),
    );
    test(
      'green70Hover',
      () => expect(CarbonColors.green70Hover, const Color(0xFF11742F)),
    );
    test(
      'green80Hover',
      () => expect(CarbonColors.green80Hover, const Color(0xFF05521C)),
    );
    test(
      'green90Hover',
      () => expect(CarbonColors.green90Hover, const Color(0xFF033B11)),
    );
    test(
      'green100Hover',
      () => expect(CarbonColors.green100Hover, const Color(0xFF0D300F)),
    );
    test(
      'coolGray10',
      () => expect(CarbonColors.coolGray10, const Color(0xFFF2F4F8)),
    );
    test(
      'coolGray20',
      () => expect(CarbonColors.coolGray20, const Color(0xFFDDE1E6)),
    );
    test(
      'coolGray30',
      () => expect(CarbonColors.coolGray30, const Color(0xFFC1C7CD)),
    );
    test(
      'coolGray40',
      () => expect(CarbonColors.coolGray40, const Color(0xFFA2A9B0)),
    );
    test(
      'coolGray50',
      () => expect(CarbonColors.coolGray50, const Color(0xFF878D96)),
    );
    test(
      'coolGray60',
      () => expect(CarbonColors.coolGray60, const Color(0xFF697077)),
    );
    test(
      'coolGray70',
      () => expect(CarbonColors.coolGray70, const Color(0xFF4D5358)),
    );
    test(
      'coolGray80',
      () => expect(CarbonColors.coolGray80, const Color(0xFF343A3F)),
    );
    test(
      'coolGray90',
      () => expect(CarbonColors.coolGray90, const Color(0xFF21272A)),
    );
    test(
      'coolGray100',
      () => expect(CarbonColors.coolGray100, const Color(0xFF121619)),
    );
    test(
      'coolGray10Hover',
      () => expect(CarbonColors.coolGray10Hover, const Color(0xFFE4E9F1)),
    );
    test(
      'coolGray20Hover',
      () => expect(CarbonColors.coolGray20Hover, const Color(0xFFCDD3DA)),
    );
    test(
      'coolGray30Hover',
      () => expect(CarbonColors.coolGray30Hover, const Color(0xFFADB5BD)),
    );
    test(
      'coolGray40Hover',
      () => expect(CarbonColors.coolGray40Hover, const Color(0xFF9199A1)),
    );
    test(
      'coolGray50Hover',
      () => expect(CarbonColors.coolGray50Hover, const Color(0xFF757B85)),
    );
    test(
      'coolGray60Hover',
      () => expect(CarbonColors.coolGray60Hover, const Color(0xFF585E64)),
    );
    test(
      'coolGray70Hover',
      () => expect(CarbonColors.coolGray70Hover, const Color(0xFF5D646A)),
    );
    test(
      'coolGray80Hover',
      () => expect(CarbonColors.coolGray80Hover, const Color(0xFF434A51)),
    );
    test(
      'coolGray90Hover',
      () => expect(CarbonColors.coolGray90Hover, const Color(0xFF2B3236)),
    );
    test(
      'coolGray100Hover',
      () => expect(CarbonColors.coolGray100Hover, const Color(0xFF222A2F)),
    );
    test('gray10', () => expect(CarbonColors.gray10, const Color(0xFFF4F4F4)));
    test('gray20', () => expect(CarbonColors.gray20, const Color(0xFFE0E0E0)));
    test('gray30', () => expect(CarbonColors.gray30, const Color(0xFFC6C6C6)));
    test('gray40', () => expect(CarbonColors.gray40, const Color(0xFFA8A8A8)));
    test('gray50', () => expect(CarbonColors.gray50, const Color(0xFF8D8D8D)));
    test('gray60', () => expect(CarbonColors.gray60, const Color(0xFF6F6F6F)));
    test('gray70', () => expect(CarbonColors.gray70, const Color(0xFF525252)));
    test('gray80', () => expect(CarbonColors.gray80, const Color(0xFF393939)));
    test('gray90', () => expect(CarbonColors.gray90, const Color(0xFF262626)));
    test(
      'gray100',
      () => expect(CarbonColors.gray100, const Color(0xFF161616)),
    );
    test(
      'gray10Hover',
      () => expect(CarbonColors.gray10Hover, const Color(0xFFE8E8E8)),
    );
    test(
      'gray20Hover',
      () => expect(CarbonColors.gray20Hover, const Color(0xFFD1D1D1)),
    );
    test(
      'gray30Hover',
      () => expect(CarbonColors.gray30Hover, const Color(0xFFB5B5B5)),
    );
    test(
      'gray40Hover',
      () => expect(CarbonColors.gray40Hover, const Color(0xFF999999)),
    );
    test(
      'gray50Hover',
      () => expect(CarbonColors.gray50Hover, const Color(0xFF7A7A7A)),
    );
    test(
      'gray60Hover',
      () => expect(CarbonColors.gray60Hover, const Color(0xFF5E5E5E)),
    );
    test(
      'gray70Hover',
      () => expect(CarbonColors.gray70Hover, const Color(0xFF636363)),
    );
    test(
      'gray80Hover',
      () => expect(CarbonColors.gray80Hover, const Color(0xFF474747)),
    );
    test(
      'gray90Hover',
      () => expect(CarbonColors.gray90Hover, const Color(0xFF333333)),
    );
    test(
      'gray100Hover',
      () => expect(CarbonColors.gray100Hover, const Color(0xFF292929)),
    );
    test(
      'warmGray10',
      () => expect(CarbonColors.warmGray10, const Color(0xFFF7F3F2)),
    );
    test(
      'warmGray20',
      () => expect(CarbonColors.warmGray20, const Color(0xFFE5E0DF)),
    );
    test(
      'warmGray30',
      () => expect(CarbonColors.warmGray30, const Color(0xFFCAC5C4)),
    );
    test(
      'warmGray40',
      () => expect(CarbonColors.warmGray40, const Color(0xFFADA8A8)),
    );
    test(
      'warmGray50',
      () => expect(CarbonColors.warmGray50, const Color(0xFF8F8B8B)),
    );
    test(
      'warmGray60',
      () => expect(CarbonColors.warmGray60, const Color(0xFF726E6E)),
    );
    test(
      'warmGray70',
      () => expect(CarbonColors.warmGray70, const Color(0xFF565151)),
    );
    test(
      'warmGray80',
      () => expect(CarbonColors.warmGray80, const Color(0xFF3C3838)),
    );
    test(
      'warmGray90',
      () => expect(CarbonColors.warmGray90, const Color(0xFF272525)),
    );
    test(
      'warmGray100',
      () => expect(CarbonColors.warmGray100, const Color(0xFF171414)),
    );
    test(
      'warmGray10Hover',
      () => expect(CarbonColors.warmGray10Hover, const Color(0xFFF0E8E6)),
    );
    test(
      'warmGray20Hover',
      () => expect(CarbonColors.warmGray20Hover, const Color(0xFFD8D0CF)),
    );
    test(
      'warmGray30Hover',
      () => expect(CarbonColors.warmGray30Hover, const Color(0xFFB9B3B1)),
    );
    test(
      'warmGray40Hover',
      () => expect(CarbonColors.warmGray40Hover, const Color(0xFF9C9696)),
    );
    test(
      'warmGray50Hover',
      () => expect(CarbonColors.warmGray50Hover, const Color(0xFF7F7B7B)),
    );
    test(
      'warmGray60Hover',
      () => expect(CarbonColors.warmGray60Hover, const Color(0xFF605D5D)),
    );
    test(
      'warmGray70Hover',
      () => expect(CarbonColors.warmGray70Hover, const Color(0xFF696363)),
    );
    test(
      'warmGray80Hover',
      () => expect(CarbonColors.warmGray80Hover, const Color(0xFF4C4848)),
    );
    test(
      'warmGray90Hover',
      () => expect(CarbonColors.warmGray90Hover, const Color(0xFF343232)),
    );
    test(
      'warmGray100Hover',
      () => expect(CarbonColors.warmGray100Hover, const Color(0xFF2C2626)),
    );
  });

  test('every palette color is fully opaque', () {
    const all = <Color>[
      CarbonColors.black,
      CarbonColors.black100,
      CarbonColors.blackHover,
      CarbonColors.white,
      CarbonColors.white0,
      CarbonColors.whiteHover,
      CarbonColors.yellow10,
      CarbonColors.yellow20,
      CarbonColors.yellow30,
      CarbonColors.yellow40,
      CarbonColors.yellow50,
      CarbonColors.yellow60,
      CarbonColors.yellow70,
      CarbonColors.yellow80,
      CarbonColors.yellow90,
      CarbonColors.yellow100,
      CarbonColors.yellow10Hover,
      CarbonColors.yellow20Hover,
      CarbonColors.yellow30Hover,
      CarbonColors.yellow40Hover,
      CarbonColors.yellow50Hover,
      CarbonColors.yellow60Hover,
      CarbonColors.yellow70Hover,
      CarbonColors.yellow80Hover,
      CarbonColors.yellow90Hover,
      CarbonColors.yellow100Hover,
      CarbonColors.orange10,
      CarbonColors.orange20,
      CarbonColors.orange30,
      CarbonColors.orange40,
      CarbonColors.orange50,
      CarbonColors.orange60,
      CarbonColors.orange70,
      CarbonColors.orange80,
      CarbonColors.orange90,
      CarbonColors.orange100,
      CarbonColors.orange10Hover,
      CarbonColors.orange20Hover,
      CarbonColors.orange30Hover,
      CarbonColors.orange40Hover,
      CarbonColors.orange50Hover,
      CarbonColors.orange60Hover,
      CarbonColors.orange70Hover,
      CarbonColors.orange80Hover,
      CarbonColors.orange90Hover,
      CarbonColors.orange100Hover,
      CarbonColors.red10,
      CarbonColors.red20,
      CarbonColors.red30,
      CarbonColors.red40,
      CarbonColors.red50,
      CarbonColors.red60,
      CarbonColors.red70,
      CarbonColors.red80,
      CarbonColors.red90,
      CarbonColors.red100,
      CarbonColors.red100Hover,
      CarbonColors.red90Hover,
      CarbonColors.red80Hover,
      CarbonColors.red70Hover,
      CarbonColors.red60Hover,
      CarbonColors.red50Hover,
      CarbonColors.red40Hover,
      CarbonColors.red30Hover,
      CarbonColors.red20Hover,
      CarbonColors.red10Hover,
      CarbonColors.magenta10,
      CarbonColors.magenta20,
      CarbonColors.magenta30,
      CarbonColors.magenta40,
      CarbonColors.magenta50,
      CarbonColors.magenta60,
      CarbonColors.magenta70,
      CarbonColors.magenta80,
      CarbonColors.magenta90,
      CarbonColors.magenta100,
      CarbonColors.magenta100Hover,
      CarbonColors.magenta90Hover,
      CarbonColors.magenta80Hover,
      CarbonColors.magenta70Hover,
      CarbonColors.magenta60Hover,
      CarbonColors.magenta50Hover,
      CarbonColors.magenta40Hover,
      CarbonColors.magenta30Hover,
      CarbonColors.magenta20Hover,
      CarbonColors.magenta10Hover,
      CarbonColors.purple10,
      CarbonColors.purple20,
      CarbonColors.purple30,
      CarbonColors.purple40,
      CarbonColors.purple50,
      CarbonColors.purple60,
      CarbonColors.purple70,
      CarbonColors.purple80,
      CarbonColors.purple90,
      CarbonColors.purple100,
      CarbonColors.purple100Hover,
      CarbonColors.purple90Hover,
      CarbonColors.purple80Hover,
      CarbonColors.purple70Hover,
      CarbonColors.purple60Hover,
      CarbonColors.purple50Hover,
      CarbonColors.purple40Hover,
      CarbonColors.purple30Hover,
      CarbonColors.purple20Hover,
      CarbonColors.purple10Hover,
      CarbonColors.blue10,
      CarbonColors.blue20,
      CarbonColors.blue30,
      CarbonColors.blue40,
      CarbonColors.blue50,
      CarbonColors.blue60,
      CarbonColors.blue70,
      CarbonColors.blue80,
      CarbonColors.blue90,
      CarbonColors.blue100,
      CarbonColors.blue100Hover,
      CarbonColors.blue90Hover,
      CarbonColors.blue80Hover,
      CarbonColors.blue70Hover,
      CarbonColors.blue60Hover,
      CarbonColors.blue50Hover,
      CarbonColors.blue40Hover,
      CarbonColors.blue30Hover,
      CarbonColors.blue20Hover,
      CarbonColors.blue10Hover,
      CarbonColors.cyan10,
      CarbonColors.cyan20,
      CarbonColors.cyan30,
      CarbonColors.cyan40,
      CarbonColors.cyan50,
      CarbonColors.cyan60,
      CarbonColors.cyan70,
      CarbonColors.cyan80,
      CarbonColors.cyan90,
      CarbonColors.cyan100,
      CarbonColors.cyan10Hover,
      CarbonColors.cyan20Hover,
      CarbonColors.cyan30Hover,
      CarbonColors.cyan40Hover,
      CarbonColors.cyan50Hover,
      CarbonColors.cyan60Hover,
      CarbonColors.cyan70Hover,
      CarbonColors.cyan80Hover,
      CarbonColors.cyan90Hover,
      CarbonColors.cyan100Hover,
      CarbonColors.teal10,
      CarbonColors.teal20,
      CarbonColors.teal30,
      CarbonColors.teal40,
      CarbonColors.teal50,
      CarbonColors.teal60,
      CarbonColors.teal70,
      CarbonColors.teal80,
      CarbonColors.teal90,
      CarbonColors.teal100,
      CarbonColors.teal10Hover,
      CarbonColors.teal20Hover,
      CarbonColors.teal30Hover,
      CarbonColors.teal40Hover,
      CarbonColors.teal50Hover,
      CarbonColors.teal60Hover,
      CarbonColors.teal70Hover,
      CarbonColors.teal80Hover,
      CarbonColors.teal90Hover,
      CarbonColors.teal100Hover,
      CarbonColors.green10,
      CarbonColors.green20,
      CarbonColors.green30,
      CarbonColors.green40,
      CarbonColors.green50,
      CarbonColors.green60,
      CarbonColors.green70,
      CarbonColors.green80,
      CarbonColors.green90,
      CarbonColors.green100,
      CarbonColors.green10Hover,
      CarbonColors.green20Hover,
      CarbonColors.green30Hover,
      CarbonColors.green40Hover,
      CarbonColors.green50Hover,
      CarbonColors.green60Hover,
      CarbonColors.green70Hover,
      CarbonColors.green80Hover,
      CarbonColors.green90Hover,
      CarbonColors.green100Hover,
      CarbonColors.coolGray10,
      CarbonColors.coolGray20,
      CarbonColors.coolGray30,
      CarbonColors.coolGray40,
      CarbonColors.coolGray50,
      CarbonColors.coolGray60,
      CarbonColors.coolGray70,
      CarbonColors.coolGray80,
      CarbonColors.coolGray90,
      CarbonColors.coolGray100,
      CarbonColors.coolGray10Hover,
      CarbonColors.coolGray20Hover,
      CarbonColors.coolGray30Hover,
      CarbonColors.coolGray40Hover,
      CarbonColors.coolGray50Hover,
      CarbonColors.coolGray60Hover,
      CarbonColors.coolGray70Hover,
      CarbonColors.coolGray80Hover,
      CarbonColors.coolGray90Hover,
      CarbonColors.coolGray100Hover,
      CarbonColors.gray10,
      CarbonColors.gray20,
      CarbonColors.gray30,
      CarbonColors.gray40,
      CarbonColors.gray50,
      CarbonColors.gray60,
      CarbonColors.gray70,
      CarbonColors.gray80,
      CarbonColors.gray90,
      CarbonColors.gray100,
      CarbonColors.gray10Hover,
      CarbonColors.gray20Hover,
      CarbonColors.gray30Hover,
      CarbonColors.gray40Hover,
      CarbonColors.gray50Hover,
      CarbonColors.gray60Hover,
      CarbonColors.gray70Hover,
      CarbonColors.gray80Hover,
      CarbonColors.gray90Hover,
      CarbonColors.gray100Hover,
      CarbonColors.warmGray10,
      CarbonColors.warmGray20,
      CarbonColors.warmGray30,
      CarbonColors.warmGray40,
      CarbonColors.warmGray50,
      CarbonColors.warmGray60,
      CarbonColors.warmGray70,
      CarbonColors.warmGray80,
      CarbonColors.warmGray90,
      CarbonColors.warmGray100,
      CarbonColors.warmGray10Hover,
      CarbonColors.warmGray20Hover,
      CarbonColors.warmGray30Hover,
      CarbonColors.warmGray40Hover,
      CarbonColors.warmGray50Hover,
      CarbonColors.warmGray60Hover,
      CarbonColors.warmGray70Hover,
      CarbonColors.warmGray80Hover,
      CarbonColors.warmGray90Hover,
      CarbonColors.warmGray100Hover,
    ];
    for (final color in all) {
      expect((color.a * 255).round(), 255);
    }
  });

  test('each family exposes the full 10-100 step ramp', () {
    const ramps = <String, List<Color>>{
      'yellow': [
        CarbonColors.yellow10,
        CarbonColors.yellow20,
        CarbonColors.yellow30,
        CarbonColors.yellow40,
        CarbonColors.yellow50,
        CarbonColors.yellow60,
        CarbonColors.yellow70,
        CarbonColors.yellow80,
        CarbonColors.yellow90,
        CarbonColors.yellow100,
      ],
      'orange': [
        CarbonColors.orange10,
        CarbonColors.orange20,
        CarbonColors.orange30,
        CarbonColors.orange40,
        CarbonColors.orange50,
        CarbonColors.orange60,
        CarbonColors.orange70,
        CarbonColors.orange80,
        CarbonColors.orange90,
        CarbonColors.orange100,
      ],
      'red': [
        CarbonColors.red10,
        CarbonColors.red20,
        CarbonColors.red30,
        CarbonColors.red40,
        CarbonColors.red50,
        CarbonColors.red60,
        CarbonColors.red70,
        CarbonColors.red80,
        CarbonColors.red90,
        CarbonColors.red100,
      ],
      'magenta': [
        CarbonColors.magenta10,
        CarbonColors.magenta20,
        CarbonColors.magenta30,
        CarbonColors.magenta40,
        CarbonColors.magenta50,
        CarbonColors.magenta60,
        CarbonColors.magenta70,
        CarbonColors.magenta80,
        CarbonColors.magenta90,
        CarbonColors.magenta100,
      ],
      'purple': [
        CarbonColors.purple10,
        CarbonColors.purple20,
        CarbonColors.purple30,
        CarbonColors.purple40,
        CarbonColors.purple50,
        CarbonColors.purple60,
        CarbonColors.purple70,
        CarbonColors.purple80,
        CarbonColors.purple90,
        CarbonColors.purple100,
      ],
      'blue': [
        CarbonColors.blue10,
        CarbonColors.blue20,
        CarbonColors.blue30,
        CarbonColors.blue40,
        CarbonColors.blue50,
        CarbonColors.blue60,
        CarbonColors.blue70,
        CarbonColors.blue80,
        CarbonColors.blue90,
        CarbonColors.blue100,
      ],
      'cyan': [
        CarbonColors.cyan10,
        CarbonColors.cyan20,
        CarbonColors.cyan30,
        CarbonColors.cyan40,
        CarbonColors.cyan50,
        CarbonColors.cyan60,
        CarbonColors.cyan70,
        CarbonColors.cyan80,
        CarbonColors.cyan90,
        CarbonColors.cyan100,
      ],
      'teal': [
        CarbonColors.teal10,
        CarbonColors.teal20,
        CarbonColors.teal30,
        CarbonColors.teal40,
        CarbonColors.teal50,
        CarbonColors.teal60,
        CarbonColors.teal70,
        CarbonColors.teal80,
        CarbonColors.teal90,
        CarbonColors.teal100,
      ],
      'green': [
        CarbonColors.green10,
        CarbonColors.green20,
        CarbonColors.green30,
        CarbonColors.green40,
        CarbonColors.green50,
        CarbonColors.green60,
        CarbonColors.green70,
        CarbonColors.green80,
        CarbonColors.green90,
        CarbonColors.green100,
      ],
      'coolGray': [
        CarbonColors.coolGray10,
        CarbonColors.coolGray20,
        CarbonColors.coolGray30,
        CarbonColors.coolGray40,
        CarbonColors.coolGray50,
        CarbonColors.coolGray60,
        CarbonColors.coolGray70,
        CarbonColors.coolGray80,
        CarbonColors.coolGray90,
        CarbonColors.coolGray100,
      ],
      'gray': [
        CarbonColors.gray10,
        CarbonColors.gray20,
        CarbonColors.gray30,
        CarbonColors.gray40,
        CarbonColors.gray50,
        CarbonColors.gray60,
        CarbonColors.gray70,
        CarbonColors.gray80,
        CarbonColors.gray90,
        CarbonColors.gray100,
      ],
      'warmGray': [
        CarbonColors.warmGray10,
        CarbonColors.warmGray20,
        CarbonColors.warmGray30,
        CarbonColors.warmGray40,
        CarbonColors.warmGray50,
        CarbonColors.warmGray60,
        CarbonColors.warmGray70,
        CarbonColors.warmGray80,
        CarbonColors.warmGray90,
        CarbonColors.warmGray100,
      ],
    };
    for (final ramp in ramps.values) {
      expect(ramp, hasLength(10));
    }
  });
}
