// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_fluid_type.py — do not edit.

import 'package:carbide/carbide.dart';
import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('expressiveHeading01 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading01.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading01.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading01.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading01.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading01.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
  });

  test('expressiveHeading02 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading02.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading02.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading02.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading02.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading02.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
  });

  test('expressiveHeading03 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading03.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading03.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading03.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading03.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading03.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        height: 1.334,
        letterSpacing: 0,
      ),
    );
  });

  test('expressiveHeading04 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading04.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading04.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading04.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading04.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading04.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
  });

  test('expressiveHeading05 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading05.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading05.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 36,
        fontWeight: FontWeight.w300,
        height: 1.22,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading05.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading05.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 48,
        fontWeight: FontWeight.w300,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading05.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
  });

  test('expressiveHeading06 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveHeading06.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading06.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 36,
        fontWeight: FontWeight.w600,
        height: 1.22,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading06.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w600,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading06.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 48,
        fontWeight: FontWeight.w600,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveHeading06.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w600,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
  });

  test('expressiveParagraph01 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.expressiveParagraph01.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 24,
        fontWeight: FontWeight.w300,
        height: 1.334,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveParagraph01.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 24,
        fontWeight: FontWeight.w300,
        height: 1.334,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveParagraph01.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w300,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveParagraph01.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w300,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.expressiveParagraph01.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w300,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
  });

  test('quotation01 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.quotation01.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.3,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation01.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.3,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation01.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        height: 1.334,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation01.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation01.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
  });

  test('quotation02 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.quotation02.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 32,
        fontWeight: FontWeight.w300,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation02.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 36,
        fontWeight: FontWeight.w300,
        height: 1.22,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation02.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation02.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 48,
        fontWeight: FontWeight.w300,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.quotation02.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.serif,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
  });

  test('display01 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.display01.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display01.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display01.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 54,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display01.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        height: 1.17,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display01.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 76,
        fontWeight: FontWeight.w300,
        height: 1.13,
        letterSpacing: 0,
      ),
    );
  });

  test('display02 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.display02.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w600,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display02.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w600,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display02.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 54,
        fontWeight: FontWeight.w600,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display02.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w600,
        height: 1.16,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display02.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 76,
        fontWeight: FontWeight.w600,
        height: 1.13,
        letterSpacing: 0,
      ),
    );
  });

  test('display03 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.display03.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display03.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 54,
        fontWeight: FontWeight.w300,
        height: 1.18,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display03.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        height: 1.16,
        letterSpacing: -0.64,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display03.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 76,
        fontWeight: FontWeight.w300,
        height: 1.13,
        letterSpacing: -0.64,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display03.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 84,
        fontWeight: FontWeight.w300,
        height: 1.11,
        letterSpacing: -0.96,
      ),
    );
  });

  test('display04 cascades correctly across breakpoints', () {
    expect(
      CarbonFluidTypeStyles.display04.resolve(320),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.19,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display04.resolve(672),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 68,
        fontWeight: FontWeight.w300,
        height: 1.15,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display04.resolve(1056),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 92,
        fontWeight: FontWeight.w300,
        height: 1.11,
        letterSpacing: -0.64,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display04.resolve(1312),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 122,
        fontWeight: FontWeight.w300,
        height: 1.07,
        letterSpacing: -0.64,
      ),
    );
    expect(
      CarbonFluidTypeStyles.display04.resolve(1584),
      const TextStyle(
        fontFamily: CarbonFontFamily.sans,
        package: CarbonFontFamily.package,
        fontSize: 156,
        fontWeight: FontWeight.w300,
        height: 1.05,
        letterSpacing: -0.96,
      ),
    );
  });

  test('fluid aliases reference their base style', () {
    expect(
      CarbonFluidTypeStyles.fluidHeading03,
      same(CarbonFluidTypeStyles.expressiveHeading03),
    );
    expect(
      CarbonFluidTypeStyles.fluidHeading04,
      same(CarbonFluidTypeStyles.expressiveHeading04),
    );
    expect(
      CarbonFluidTypeStyles.fluidHeading05,
      same(CarbonFluidTypeStyles.expressiveHeading05),
    );
    expect(
      CarbonFluidTypeStyles.fluidHeading06,
      same(CarbonFluidTypeStyles.expressiveHeading06),
    );
    expect(
      CarbonFluidTypeStyles.fluidParagraph01,
      same(CarbonFluidTypeStyles.expressiveParagraph01),
    );
    expect(
      CarbonFluidTypeStyles.fluidQuotation01,
      same(CarbonFluidTypeStyles.quotation01),
    );
    expect(
      CarbonFluidTypeStyles.fluidQuotation02,
      same(CarbonFluidTypeStyles.quotation02),
    );
    expect(
      CarbonFluidTypeStyles.fluidDisplay01,
      same(CarbonFluidTypeStyles.display01),
    );
    expect(
      CarbonFluidTypeStyles.fluidDisplay02,
      same(CarbonFluidTypeStyles.display02),
    );
    expect(
      CarbonFluidTypeStyles.fluidDisplay03,
      same(CarbonFluidTypeStyles.display03),
    );
    expect(
      CarbonFluidTypeStyles.fluidDisplay04,
      same(CarbonFluidTypeStyles.display04),
    );
  });
}
