// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the Apache License,
// Version 2.0. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_type.py — do not edit by hand.

import 'package:carbide/carbide.dart';
import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('type scale matches the Carbon source', () {
    expect(CarbonTypeScale.steps, <double>[
      12,
      14,
      16,
      18,
      20,
      24,
      28,
      32,
      36,
      42,
      48,
      54,
      60,
      68,
      76,
      84,
      92,
      102,
      112,
      122,
      132,
      144,
      156,
    ]);
  });

  test('font weights match the Carbon source', () {
    expect(CarbonFontWeight.light, FontWeight.w300);
    expect(CarbonFontWeight.regular, FontWeight.w400);
    expect(CarbonFontWeight.semibold, FontWeight.w600);
  });

  test('fixed type styles match the Carbon source', () {
    expect(
      CarbonTypeStyles.caption01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.33333,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.caption02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.label01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.33333,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.label02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.helperText01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.33333,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.helperText02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.legal01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.33333,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.legal02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.code01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.mono}',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.33333,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.code02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.mono}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.42857,
        letterSpacing: 0.32,
      ),
    );
    expect(
      CarbonTypeStyles.bodyShort01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.bodyShort02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        height: 1.375,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.bodyLong01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.42857,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.bodyLong02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.heading01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.42857,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.heading02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.28572,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.375,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading03,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading04,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.28572,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading05,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.25,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading06,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 42,
        fontWeight: FontWeight.w300,
        height: 1.199,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.productiveHeading07,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 54,
        fontWeight: FontWeight.w300,
        height: 1.199,
        letterSpacing: 0,
      ),
    );
    expect(
      CarbonTypeStyles.expressiveHeading01,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0.16,
      ),
    );
    expect(
      CarbonTypeStyles.expressiveHeading02,
      const TextStyle(
        fontFamily:
            'packages/${CarbonFontFamily.package}/${CarbonFontFamily.sans}',
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        letterSpacing: 0,
      ),
    );
    expect(CarbonTypeStyles.bodyCompact01, CarbonTypeStyles.bodyShort01);
    expect(CarbonTypeStyles.bodyCompact02, CarbonTypeStyles.bodyShort02);
    expect(CarbonTypeStyles.body01, CarbonTypeStyles.bodyLong01);
    expect(CarbonTypeStyles.body02, CarbonTypeStyles.bodyLong02);
    expect(
      CarbonTypeStyles.headingCompact01,
      CarbonTypeStyles.productiveHeading01,
    );
    expect(
      CarbonTypeStyles.headingCompact02,
      CarbonTypeStyles.productiveHeading02,
    );
    expect(CarbonTypeStyles.heading03, CarbonTypeStyles.productiveHeading03);
    expect(CarbonTypeStyles.heading04, CarbonTypeStyles.productiveHeading04);
    expect(CarbonTypeStyles.heading05, CarbonTypeStyles.productiveHeading05);
    expect(CarbonTypeStyles.heading06, CarbonTypeStyles.productiveHeading06);
    expect(CarbonTypeStyles.heading07, CarbonTypeStyles.productiveHeading07);
  });

  test('every style names a bundled Plex family', () {
    const families = <String>{
      'packages/carbide/${CarbonFontFamily.sans}',
      'packages/carbide/${CarbonFontFamily.mono}',
    };
    for (final TextStyle style in <TextStyle>[
      CarbonTypeStyles.caption01,
      CarbonTypeStyles.caption02,
      CarbonTypeStyles.label01,
      CarbonTypeStyles.label02,
      CarbonTypeStyles.helperText01,
      CarbonTypeStyles.helperText02,
      CarbonTypeStyles.legal01,
      CarbonTypeStyles.legal02,
      CarbonTypeStyles.code01,
      CarbonTypeStyles.code02,
      CarbonTypeStyles.bodyShort01,
      CarbonTypeStyles.bodyShort02,
      CarbonTypeStyles.bodyLong01,
      CarbonTypeStyles.bodyLong02,
      CarbonTypeStyles.heading01,
      CarbonTypeStyles.heading02,
      CarbonTypeStyles.productiveHeading01,
      CarbonTypeStyles.productiveHeading02,
      CarbonTypeStyles.productiveHeading03,
      CarbonTypeStyles.productiveHeading04,
      CarbonTypeStyles.productiveHeading05,
      CarbonTypeStyles.productiveHeading06,
      CarbonTypeStyles.productiveHeading07,
      CarbonTypeStyles.expressiveHeading01,
      CarbonTypeStyles.expressiveHeading02,
    ]) {
      expect(families, contains(style.fontFamily));
      expect(style.fontSize, greaterThan(0));
    }
  });
}
